### ISSUE TITLE
Server crashes when trying to access the Socket.io with external software

### ISSUE THREAD

**Issue by johan12345** [sharelatex/sharelatex#149]
I am trying to connect to the Socket.io socket using a Java program. I first POST the login data to the `/login` page and save the `sharelatex.sid` cookie. After that, I can correctly access, for example, the `project/53b2b183e04c310b8ecdf491` page, but when I try to connect to the Socket.io using the same cookie and then send the `joinProject` event, the socket disconnects and the `web` component of the server crashes with the following log:
```
[2014-07-02T06:56:54.457Z]  INFO: web-sharelatex/57530 on Mac-mini.local: Checking if can access
    user: {
      "id": "53b1e08f45627cc8280fbc92",
      "email": "my-email@example.com"
    }
    --
    project: {
      "id": "53b2b183e04c310b8ecdf491",
      "name": "Test Project"
    }
Exception: TypeError: undefined is not a function
    at /Users//sharelatex/sharelatex/web/app/js/Features/Editor/EditorController.js:98:22
    at /Users//sharelatex/sharelatex/web/app/js/Features/Security/AuthorizationManager.js:13:18
    at Object.module.exports.userCanAccessProject (/Users//sharelatex/sharelatex/web/app/js/managers/SecurityManager.js:153:18)
    at Object.module.exports.AuthorizationManager.getPrivilegeLevelForProject (/Users//sharelatex/sharelatex/web/app/js/Features/Security/AuthorizationManager.js:11:30)
    at /Users//sharelatex/sharelatex/web/app/js/Features/Editor/EditorController.js:83:39
    at /Users//sharelatex/sharelatex/web/app/js/Features/Project/ProjectGetter.js:119:16
    at /Users//sharelatex/sharelatex/web/node_modules/async/lib/async.js:240:13
    at /Users//sharelatex/sharelatex/web/node_modules/async/lib/async.js:196:33
    at /Users//sharelatex/sharelatex/web/node_modules/async/lib/async.js:237:17
    at /Users//sharelatex/sharelatex/web/node_modules/async/lib/async.js:560:34
    at /Users//sharelatex/sharelatex/web/app/js/Features/Project/ProjectGetter.js:110:20
    at /Users//sharelatex/sharelatex/web/app/js/Features/Project/ProjectGetter.js:65:18
    at /Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:158:16
    at commandHandler (/Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/cursor.js:651:16)
    at /Users//sharelatex/sharelatex/web/node_modules/metrics-sharelatex/mongodb.coffee:42:29
    at /Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1670:9
    at Server.Base._callHandler (/Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
    at /Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
    at MongoReply.parseBody (/Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users//sharelatex/sharelatex/web/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)
-> completed /Users//sharelatex/sharelatex/web/app.js (38681688ms)

>> 1 file and 0 calls executed (38681704ms)

Done, without errors.
```
Is there another method of authentication I'm missing? Or is it a bug in the server?

**Comment by johan12345** [comment]
I currently have a partially (with a very basic feature set) working Android client for ShareLaTeX and it succeeds in connecting to my own server running the open source version of ShareLaTeX, but I cannot get it to connect to the sharelatex.com server. As soon as I connect to the Socket.IO service, the server sends a `7:::1+0` message, which causes the client to disconnect. Is there any additional kind of authentication you use on sharelatex.com compared to the open source version which can cause this failure?
I am already sending the session Cookies with the Socket.IO handshake (`sharelatex_session`, which seems to be called `sharelatex.sid` in the open source version; and `SERVERID`).

**Comment by henryoswald** [comment]
One thing to watch out for is we regenerate the cookie name after login.

**Comment by johan12345** [comment]
So you mean the name of the cookie (`sharelatex_session`) changes after the login? Obviously the cookie value changes, but that shouldn't be the problem since my client clears the cookie store before logging in and then sends all the cookies it gets (which are the two I previously mentioned) when handshaking with the Socket.IO service.

**Comment by jpallen** [comment]
No, only the cookie value changes. I don't know why you can't connect to www.sharelatex.com, but we don't support this use case at the moment, sorry. Our terms and conditions ask that you not access ShareLaTeX via 'robots' for a number of reasons:

1) The APIs are not stable and liable to change at any time, and we don't want to be 'blamed' for disrupting anything by doing so;
2) Runaway or misbehaving scripts have the potential to cause a lot more trouble than a user ever could.

We're working towards a proper stable API designed for machine access with the appropriate safe guards in place, but it's still in the early stages of planning, sorry.

**Comment by johan12345** [comment]
@henryoswald, @jpallen 
After some more testing, it seems that the connection to the socket.io only succeeds when the program is assigned the `SERVERID` cookie with a value of `web-0`. If I clear the cookies and reload the login page until I get the correct `SERVERID` cookie and only then proceed with logging in and connecting to the socket.io service, it works every time. Are there any differences between your servers that can cause this behavior?

As to the terms and conditions: I don't intend to connect to ShareLaTeX or register for accounts with an automated script, I am just trying to create a client to use ShareLaTeX on Android devices in a similar fashion to the web version or projects like the [https://github.com/thomashn/Vim-ShareLaTeX-Plugin](Vim plugin) from other people. And of course, I wouldn't blame you if you change the APIs at some point in the future since they're not documented anywhere.

**Comment by jpallen** [comment]
@johan12345 That's odd, every server should behave the same.

We're starting to think about an official API, so I'd appreciate if you could weight in at sharelatex/sharelatex#299
