### ISSUE TITLE
Dropbox sur installation privé

### ISSUE THREAD

**Issue by SimonBHB** [sharelatex/sharelatex#192]
Bonjours, j'ai installer ShareLatex sur mon serveur et quand je clique sur le bouton: Lier à Dropbox, une page m'affiche: 
Oops, something went wrong with your request, sorry. If this continues, please contact us at support@sharelatex.com

Dropbox peut être utilisé seulement avec sharelatex.com ?

**Comment by sisonath** [comment]
Hello
