### ISSUE TITLE
users without a name causes a graphical bug

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/sharelatex#197]
I noticed that when collaborating with a new user who had not specified their name in options, the user icon has a problem (displaced upwards) as shown in the pic:

![2014-10-09 11 14 53 am](https://cloud.githubusercontent.com/assets/415981/4570941/d9206e4a-4f68-11e4-8553-3c25c2317176.png)

**Comment by henryoswald** [comment]
This should be fixed now.
