### ISSUE TITLE
Spell checking words with diacritics

### ISSUE THREAD

**Issue by kleszcz** [sharelatex/sharelatex#203]
I'm writing my LaTeX document in polish. When I use diacritics they divide a word and spell checker treat it like two words. So even if I write a correct word its part might be underlined and if I make a mistake only a part of a word would by underlined. 

![image](https://cloud.githubusercontent.com/assets/1691815/4628211/378741fa-5394-11e4-9582-6e826fbcf829.png)

**Comment by kleszcz** [comment]
It's now work swell! THX

**Comment by bsacharski** [comment]
I'm having same problem when running ShareLaTeX from official docker image.
