### ISSUE TITLE
sharelatex-web service always shutdown after a few seconds

### ISSUE THREAD

**Issue by egeu5** [sharelatex/sharelatex#204]
I tried to install sharelatex on an Ubuntu server 14.04. I used the dpkg file and install mongodb-org, nodejs and redis-server from the repo. After that i executed the dpkg file. Nothing is there at port 3000. I tried to restart the service 
xxx:~$ sudo start sharelatex-web 
sharelatex-web start/running, process 6808

and another try after a few seconds:
xxx:~$ sudo start sharelatex-web 
sharelatex-web start/running, process 6866

So I think that the service is always shutdown after a few seconds. 

While installing it I get a few strange lines:
stop: Unknown instance: 
sharelatex-web start/running, process 13864
stop: Unknown instance: 
sharelatex-document-updater start/running, process 13875
stop: Unknown instance: 
sharelatex-clsi start/running, process 13889
stop: Unknown instance: 
sharelatex-filestore start/running, process 13907
stop: Unknown instance: 
sharelatex-track-changes start/running, process 13957
stop: Unknown instance: 
sharelatex-docstore start/running, process 14011
stop: Unknown instance: 
sharelatex-chat start/running, process 14101
stop: Unknown instance: 
sharelatex-tags start/running, process 14222
stop: Unknown instance: 
sharelatex-spelling start/running, process 14278
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by egeu5** [comment]
Where are they located?
Why is it the issue closed?

**Comment by jpallen** [comment]
In /var/log/sharelatex I think... need to refresh my memory, but likely somewhere in /var/log

**Comment by egeu5** [comment]
You're right. e.g.  /var/log/sharelatex/web.log
In this file is only a hundert times:
```env: node: No such file or directory```

**Comment by har-wradim** [comment]
There is a naming conflict in Ubuntu: node's executable is called nodejs. On our server I solved the problem by creating a symlink:

    sudo ln -s /usr/bin/nodejs /usr/bin/node

but there are also [other options](http://stackoverflow.com/a/18130296/2832716).

**Comment by egeu5** [comment]
It is working! The process is not terminating after a few seconds anymore. I'm now able to see the web interface. But on the login and register page aren't any textboxes. Is a reinstall a solution?

**Comment by henryoswald** [comment]
if you can't see the text boxes then your javascript probably isn't loading up

**Comment by egeu5** [comment]
On my client javascript is working (I tried some test websites).

**Comment by egeu5** [comment]
Solution: AddBlock Plus thought it was an add. Just disable it and it seems to work fine! 

Thank you all for youre kindly response!
