### ISSUE TITLE
basic management of templates

### ISSUE THREAD

**Issue by littlejo** [sharelatex/sharelatex#214]
Hello,

here is a basic mangement of template:
https://github.com/littlejo/web-sharelatex.git
branch: ldap-auth

# how to use it

Before installation:
 * change repo in Gruntfile.coffee
        name: "web"
        repo: "https://github.com/littlejo/web-sharelatex.git"
        version: "ldap-auth"
 * And after that, it classic installation.

# How to add a template
 * add the template in the directory $SHARELATEX/web/app/templates/
 * Modify the variable templates2 in consequence in $SHARELATEX/web/config/settings.defaults.coffee
 * add an entry to ul.dropdown-menu(role="menu") $SHARELATEX/web/app/views/project/list/side-bar.jade
eg:

                li
                        a(
                                href,
                                ng-click="openCreateProjectModal('cv_or_resume')"
                        ) #{translate("cv_project")}

# How to view the list of templates
connection>New Project

And you all your templates

# TODO
* to be able to add template with directory: it doesn't accept template with directories
* to be able to add template with several tex files
* to create a page $URL/templates
* to fix bug of compiling of example project, i don't know why sharelatex try to compil .bib file instead of .tex file.

**Comment by henryoswald** [comment]
Thanks for you input, we want to keep improving templates. Closing this for now to keep the place tidy.
