### ISSUE TITLE
Github theme broken

### ISSUE THREAD

**Issue by isakkarlsson** [sharelatex/sharelatex#218]
The github theme is broken since it bold-faces certain key-words. This means that visually the cursor is moved away from its actual position. 

If I start to write as of the example here:
 ![Example](http://i.imgur.com/ZNawiND.png)

The cursor indicates that it will be written before {, but in reality the character is written between { and  }.

Changing the color theme to not include bold-facing resolves the issue.

Browsers tested. Chromium 38 and Safari in OS X yosemite

**Comment by henryoswald** [comment]
This should be fixed now.
