### ISSUE TITLE
Building/Installation instructions for Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by moschlar** [sharelatex/sharelatex#223]
Since there is already a new Ubuntu LTS version, I tried how to run ShareLaTeX in it.

Short story: It works and there's no need for any external repository.
I've written up the steps I took here: https://gist.github.com/moschlar/2b941f75a44fbac69993

Maybe someone would like to integrate those into the wiki or - even better - provide an updated .deb (necessary because of the package name change of mongodb) in the release section.

**Comment by henryoswald** [comment]
Thanks for the docs, going to close this to keep the place tidy, google will still find it. We are recommending people use docker rather than setup the system themselves now which should help the situation - https://github.com/sharelatex/sharelatex-docker-image
