### ISSUE TITLE
sharelatex api documentation

### ISSUE THREAD

**Issue by fellek** [sharelatex/sharelatex#231]
Hi there, 

thanks for great work at sharelatex. As I would like to implement an extension on this project I wonder if there is any documentation about the core of sharelatex api? or do I have to reproduce everything to make something new?

Thanks for any information about it!

**Comment by okennedy** [comment]
Documentation would be quite useful.  I'd be interested in trying to add some functionality for bibliography management.  I've gotten quite used to the organizational capabilities of [BibDesk](http://bibdesk.sourceforge.net), and it would be nice to have a tabular, searchable view of my bibliography. (in a pop up window for bonus points)

**Comment by jpallen** [comment]
@fellek @okennedy Thanks for the input. We don't have any immediate API plans yet, and there's nothing to document yet either since we have no 'stable' interfaces that we'd be happy to support long term. We're still working towards this sort of thing though.

**Comment by fellek** [comment]
@jpallen Thanks for the answer. Of course, I understand thats not on top of your priority list... nevertheless I do not understand how to make any changes for the frontend.. if you have some sources / tutorials that helped you to develop the frontend, it could be that what I am looking for (as long there is no API :+1: )

**Comment by jpallen** [comment]
We don't really have anything other than the code as documentation, sorry. I'm happy to answer any specific questions as best I can though.

**Comment by jpallen** [comment]
Closing this in favour of #299 where we're starting a discussion about what's needed from a ShareLaTeX API.
