### ISSUE TITLE
Folder Deletion is not available 

### ISSUE THREAD

**Issue by awasthi** [sharelatex/sharelatex#233]
I created a folder. and save some files to it. I deleted files. Now when I go for folder delete. there is no option.

**Comment by henryoswald** [comment]
no response. Cleaning up

**Comment by awasthi** [comment]
Sorry, I replied email and was waiting for your response.
I explain here again.
Go (After login)
https://www.sharelatex.com/project

There on left navigation

    All projects
        Your Projects
        Shared with you
        Deleted Projects
  Folders
        New Folder

So here create a new folder. How to delete this created folder? Deletion not possible. This was a bug (I feel)

![capture](https://cloud.githubusercontent.com/assets/124547/5759548/b19bfbb2-9cf4-11e4-9fc3-b56c6a02d556.PNG)

**Comment by henryoswald** [comment]
Folders are auto cleared up when there are no projects in them. The issue you have there is some old bad data, drop us an email at support and we will fix it for you.

**Comment by sisonath** [comment]
Hello
