### ISSUE TITLE
ShareLaTeX got stuck while loading a project

### ISSUE THREAD

**Issue by marcAC** [sharelatex/sharelatex#239]
Hello everybody,

I installed the ShareLaTeX and all its dependencies and everything seems fine, but while loading a project it got stuck all the time.
The progress bar appears and below the L of "Loading" it freezes and nothing happens anymore.
In the log I got no error.

I'm running the ShareLaTeX on centOS 7.

**Comment by henryoswald** [comment]
no response, closed.
