### ISSUE TITLE
New users with no first name

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/sharelatex#246]
When sharing a document, new users can sign up without entering any name details.
This means that the changed edist are shown but with no name.
Would it be possible to force new users to at least enter a first name field?

**Comment by henryoswald** [comment]
When did you last update web-sharelatex, we show the email if they have no first name as of about 6 weeks ago.

**Comment by sisonath** [comment]
Hello

**Comment by zeigerpuppy** [comment]
It's been longer than 6 weeks since I updated, good to hear it's fixed
