### ISSUE TITLE
Not sending email despite being enabled?

### ISSUE THREAD

**Issue by slhck** [sharelatex/sharelatex#250]
I'm using the latest release of ShareLaTeX on Debian 7 (according to the installation instructions for production), with exim4 as MTA configured and working fine. For example, running
```bash
echo "This is the body" | mail -s "This is the subject" user@gmail.com
```
will sucessfully deliver the mail.

In my `/etc/sharelatex/settings.coffee`:

```coffee
# Sending Email
# -------------
#
# You must configure a mail server to be able to send invite emails from
# ShareLaTeX. The config settings are passed to nodemailer. See the nodemailer
# documentation for available options:
#
#     http://www.nodemailer.com/docs/transports
#
email:
        fromAddress: "noreply@example.com"
        replyTo: "noreply@example.com"
        transport: "sendmail"
```

I try to reset the password using the e-mail I signed up with. However, in my web log, I get the contents of the message shown in HTML, and then:

```json
{"name":"web-sharelatex","hostname":"dev","pid":3240,"level":30,"options":{"to":"recipient@example.com","from":"noreply@example.com","subject":"Password Reset - ShareLatex.com","html":"......", "msg":"Would send email if enabled.","time":"2015-01-14T14:29:34.565Z","v":0}
{"name":"web-sharelatex","hostname":"dev","pid":3240,"level":30,"msg":"Message sent to recipient@example.com","time":"2015-01-14T14:29:34.566Z","v":0}
```
So why is email not enabled? I should add, I do not get the email, of course. It's not in spam either.

I start the services with
```bash
exec env SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee NODE_ENV=production node app.js >> /var/log/sharelatex/$SERVICE.log 2>&1 &
```
so I'm sure that the settings file is read. I've also restarted the server.

Exim is not getting the message at all, at least when checking the stats with `eximstats`.

Looking at [`EmailSender.coffee`](https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Email/EmailSender.coffee) I'm not sure if that's not a bug, since the message will be logged regardless of whether I set e-mail options in the `settings.coffee` or not.

**Comment by henryoswald** [comment]
under the hood it is just nodemailer, from the look of it sendmail is not a transport which is available by default. https://github.com/andris9/Nodemailer#available-transports can you use smtp with sendmail?

**Comment by slhck** [comment]
I can try to use SMTP, but I don't know yet. 

However, there are several open problems with ShareLaTeX regarding this:

- The description in the settings file does not mention that a certain transport isn't available.
-  It should report a failure to send the e-mail (saying that the transport isn't available or a config error, etc.)
- `Would send email if enabled.` is misleading. Should it read `Will send email if enabled`? This line is always called, I suppose.

**Comment by henryoswald** [comment]
We do have this wiki page on sending emails https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email 

We rely on node mailer to say if there is an error with the send https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Email/EmailSender.coffee#L41 you could open an issue there.

The "Would send email if enabled" is actually correct as its saying that if email was enable an email would have been sent. I guess it could be, "Email not enabled, would have sent an email now"

**Comment by slhck** [comment]
But I get the message **even when email is enabled** -- see my logs above. When you look at the code, I don't see a check for whether e-mail is enabled or not:

```coffee
if Settings.email? and Settings.email.fromAddress?
	defaultFromAddress = Settings.email.fromAddress
else
	defaultFromAddress = ""

# provide dummy mailer unless we have a better one configured.
client =
	sendMail: (options, callback = (err,status) ->) ->
		logger.log options:options, "Would send email if enabled."
		callback()
```

**Comment by henryoswald** [comment]
It will be doing that because you have not set any of the parameters (SES or SMTP) in your options  

	if Settings.email.transport? and Settings.email.parameters?
		nm_client = nodemailer.createTransport( Settings.email.transport, Settings.email.parameters )
		if nm_client
			client = nm_client

**Comment by slhck** [comment]
Now it works with SMTP.

Perhaps it would make sense to explicitly state that **only** SMTP works and that parameters **have** to be entered? localhost and port 25 are defaults in Nodemailer, so in theory you would not have to specify them.

**Comment by slhck** [comment]
I updated the wiki page with some info. Hopefully this should clear up the problems I had for future visitor.
