### ISSUE TITLE
Stuck while creating a project

### ISSUE THREAD

**Issue by atugores** [sharelatex/sharelatex#252]
hi all,

Last december I installed sharelatex in production (https://github.com/sharelatex/sharelatex/wiki/Production-Installation-Instructions). It's on a Ubuntu 14.04 and behind a nginx.

One of our users cannot create projects, sharelatex gets stuck in "loading....". When he logs in again, the project extists but if he tries to open it he gets the loading page again.

In the logs there is this suspicious error:
{"name":"web-sharelatex","hostname":"sharelatex","pid":897,"level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n  at errnoException (net.js:901:11)\n  at Object.afterConnect [as oncomplete] (net.js:892:19)\n","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"","time":"2015-01-19T11:00:14.585Z","v":0}

He uses Windows7, and we have the same error with Firefox, Chrome and IE. Then we tried removing sharelatex* cookies but the error persists. This same user tried using another computer and he could create a project without errors.
Moreover, when using another computer with Win7 and Firefox (same version) we had no problems creating a project, so, we still think it might be a browser issue.

I've seen that issues #230 and #239 are similar to this one, but you've closed them. I've checked out configuration file, and it is quite similar to the default one, we just changed the paths to the data, the siteUrl and behindProxy is set to true in our case. We are going to move to https, but we have not done it yet, so secureCookie is false.

Any clue?
Thanks

**Comment by henryoswald** [comment]
I would check all services are running, but the fact other computer works is strange. I would check they don't have any errors in their console. It could be a piece of malware called 'superfish'. We're seeing this a lot on new or updated Windows 8.1 computers. Can you check your system to see if you have anything like this installed, and if so please uninstall or disable it.

You can find out more about superfish at: http://malwaretips.com/blogs/superfish-window-shopper-adware/

**Comment by atugores** [comment]
After checking all services were running and checking the system had no virus, we discovered there was a timeout and the error in the chromium console was: 
socket.io.js:2 GET http://sharelatex....../socket.io/1/xhr-polling/wJLp21C__ibI14NGVeY?t=142182898932 502 (Bad Gateway) 
4bf6372ec38a3470ff10a94:1 Sending to GA ["send", "event", "editor-interaction", "disconnect"] 

There was no firewall, but we tried stopping the antivirus (Trnd Micro) and the user could finally create a project, edit and compile correctly.
Is there any "strange" communication between the web client and the server? We are not able to understand why the antivirus was denying the access.

**Comment by jpallen** [comment]
Our experience with anti-virus software is that they block things for no obvious reason, and you can't find out why, or how to stop it happening beyond disabling them. It's a very frustrating thing to debug sorry, but I don't know if there's much we can do to help avoid this sort of problem :(.
