### ISSUE TITLE
Stuck at loading a Project, Upload not working

### ISSUE THREAD

**Issue by ceriathstudios** [sharelatex/sharelatex#253]
Hey folks,

i just managed to install ShareLaTeX yesterday and now wanted to test it, but i found a few problems here. 
First of all, when i try to create a new project, it freezes in the creating-screen, but when i reload the site, i can see the project. Maybe that's only a bug?
The second thing is, that i can't upload a project. (I have a project locally written and exported it to zip file.) ShareLaTeX says it is not a valid zip file, but i am pretty sure it is.
And the third thing, my main problem, i can't open a project. In the loading screen it gets stuck at about 1/3 and doesn't do anything.
I have no idea what those problems causes, because i can't even find an error message in the log files. (web.log http://paste.debian.net/141255)
I am running it on a debian virtual machine. 

I hope you can help me soon.

**Comment by henryoswald** [comment]
I would check all services are running, also have a look in the javascript console.

**Comment by ceriathstudios** [comment]
They are all running without any Errors, js console has none too..any other suggestions?

**Comment by ceriathstudios** [comment]
And this happens when trying to upload something:

POST http://192.168.0.198/project/new/upload?_csrf=OzjPto_bdK-N07awi8Ewo3le&qquuid=3faf4df4-2277-4077-a005-5b5675779b1e&qqtotalfilesize=13783979 502 (Bad Gateway) fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:3627
handleStandardFileUpload fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:3627
api.upload fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:3708
upload fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:2769
qq.FineUploaderBasic._upload fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:1250
qq.FineUploaderBasic._uploadFileOrBlobDataList fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:1230
qq.FineUploaderBasic.addFiles fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:928
qq.FineUploaderBasic._onInputChange fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:1161
qq.UploadButton.onChange fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:990
(anonymous function) fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:656

[FineUploader] Error when attempting to parse xhr response text (SyntaxError: Unexpected token <) fineuploader.js?fingerprint=037410da7db8e4ea4bbcc38eead3e005-5e52def76813cfe5e57f33a77dcea81d:156

**Comment by henryoswald** [comment]
I would guess there must be something wrong with your service higher up, do you have nginx running in front of it?

**Comment by ceriathstudios** [comment]
Yes, i just copied your example out of the wiki.

**Comment by rubenmoor** [comment]
I got stuck after project creation, right at the loading screen with a friendly lion. Loaded at 1/3. I can't make out any error message in the logs. But Chrome says 4 errors:

    Uncaught ReferenceError: ace is not defined ... /js/ace/ext-language_tools.js?...
    TypeError: Cannot read property 'Autocomplete' of undefined
        at AutoCompleteManager.monkeyPatchAutocomplete (...) angular-1.3.0-beta.14.min.js:94
    TypeError: Cannot read property 'Autocomplete' of undefined
        at AutoCompleteManager.monkeyPatchAutocomplete (...) angular-1.3.0-beta.14.min.js:94
    Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by henryoswald** [comment]
it looks like static assets are not being served up correctly for some reason.

**Comment by ceriathstudios** [comment]
Any idea how to fix that?

**Comment by ceriathstudios** [comment]
I searched a bit in your code and i am pretty sure the problem is this line: 
Autocomplete = ace.require("ace/autocomplete").Autocomplete;
It seems like require does not return anything, it would be nice if you would take a look on it.

**Comment by henryoswald** [comment]
Are you running minified client side assets? If not can you try turning that on.

**Comment by knutmagnus** [comment]
Got the same problem. Freezes when trying to open a project, 2/3s into the loading. 

Any suggestions? Should I upload anything to make it possible for anyone to help?

**Comment by knutmagnus** [comment]
Never mind, fixed it. Deleted a software called Superfish, then it worked.

**Comment by rubenmoor** [comment]
I have the same problem. @knutmagnus do you mind elaborating how you fixed it?

**Comment by henryoswald** [comment]
We're seeing this a lot on new or updated Windows 8.1 computers. 

You can find out more about superfish at: http://malwaretips.com/blogs/superfish-window-shopper-adware/

**Comment by ceriathstudios** [comment]
Does not seem like this gonna fix my problem. I cannot find this software and even on linux and android the website does not load correctly. The minified assests could not help too..
v0.1.0 has the same problem. I have no idea what causes those problems.

**Comment by jpallen** [comment]
Have you run `grunt compile:minify` in the web directory to generate the minified assets?

It sounds like you might be hitting a max upload size with your file. How big is it? Have a look into your Nginx(?) config (or whichever reverse proxy you have) to see if you can increase/disable it as needed.

**Comment by rubenmoor** [comment]
Hey @jpallen , tried your hint with `grunt compile:minify` in the web dir, but to no avail. Same problem, stuck loading with the lion at around 33%.

**Comment by jpallen** [comment]
@rubenmoor which version of ShareLaTeX are you running? Is it a release version or some point on the master branch?

**Comment by rubenmoor** [comment]
I checked out the master branch from 13 days ago.

**Comment by jpallen** [comment]
Can you update to the latest release branch please? Then we'll know which version of the code you're working with and be able to debug more effectively.

**Comment by rubenmoor** [comment]
After now having switched to release v0.1.2 I see a different error when I try to load a project. After seeing the read progress bar for a short moment, I get the following message on my screen:

    You need to upgrade your account to use the History feature.

    Start Free Trial!

    Please refresh this page after starting your free trial.

And

    Please ask the project owner to upgrade to use the History feature.

Along with text fragments:

    {{ project.name }}
    Watch out! We had to undo some of your collaborators changes before we could undo yours. Dismiss
    Watch out! We had to undo some of your collaborators changes before we could undo yours. Dismiss

    {{ unreadMessages }}

    {{ updateLabels.highlightsAfter }} more update{{ ...

**Comment by jpallen** [comment]
Can you run `grunt install:real-time` please.

Are you running behind a proxy? If so you will need to add a new end point that sends any requests to /socket.io to localhost:3026, and create a `websocketsUrl` entry in your settings file with the same value as `siteUrl`.

**Comment by rubenmoor** [comment]
> Are you running behind a proxy?

This, indeed, might be the source of my troubles. I use a set-up with nginx as reverse proxy. Gotta check out your suggestions.

**Comment by jpallen** [comment]
Have a look at https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy for updated instructions about that.

**Comment by jpallen** [comment]
@rubenmoor I've added release notes for the latest version which explains this problem and how to update your config for it: https://github.com/sharelatex/sharelatex/wiki/Release-Notes---0.1.2. Let me know how you get on!

**Comment by ceriathstudios** [comment]
Hey there, i could finally fix my problem.
In my case the problem was the virtual machine. Somehow there was a problem with the IP.
I had to change it in the config file from "localhost" to "x.x.x.x". Somewhere around here is another solved issue with that problem where i found the fix. But i can't find it here, maybe someone can give a link to all the others ;)
Thank you anyways!

**Comment by jpallen** [comment]
@ceriathstudios Great, glad you got it working! If there's anything we could add to our documentation that would have stopped your tripping up on this then let me know.

**Comment by Kidswiss** [comment]
Hi there

I just installed sharelatex via the official docker image and I see the same error as rubenmoor. Is the docker image not yet updated?

**Comment by jpallen** [comment]
@Kidswiss Can you check that you've passed the correct value to SHARELATEX_SITE_URL as an environment variable to the docker container please. It should match whatever the URL is that you're accessing ShareLaTeX through.

**Comment by Kidswiss** [comment]
@jpallen Ah thank you very much I seem to have overlooked that variable. Works like a charm now!

I think it would make sense that there should be a note for this variable's importance right on top of the readme.md since it wasn't clear (at least to me) that this one is mandatory since version 1.2.

**Comment by jpallen** [comment]
I'm glad you got it working. I've got the missing unzip package in our bug tracker now and will get that fixed soon, thanks for letting me know.

**Comment by floriangeigl** [comment]
Hy I'm having the same problem as @rubenmoor after updateting to version v0.1.2. When I try to open a project Sharelatex keeps saying "You need to upgrade your account to use the History feature..." I already tried registering a new user and creating a new project with this user...same problem.
* I updated my settings.coffee as following:
```
        siteUrl : 'http://localhost:3000'
        websocketsUrl: 'http://localhost:3000'
```
 (I also tried 'http://localhost:3026' for the websocketsUrl)
* I inserted the location /socekt.io block into the nginx config.
```
        listen         443;
        server_name    _; # Catch all, see http://nginx.org/en/docs/http/server_names.html

        set $static_path /var/www/sharelatex/web/public;
        client_max_body_size 50M;

        ssl on;
        ssl_certificate /path/to//server.crt;
        ssl_certificate_key /path/to/server.key;

        location / {
                proxy_pass http://localhost:3000;
                proxy_set_header Host $http_x_forwarded_host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_read_timeout 3m;
                proxy_send_timeout 3m;
        }

        location /socket.io {
                proxy_pass http://localhost:3026;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_x_forwarded_host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_read_timeout 3m;
                proxy_send_timeout 3m;
        }
```
* I executed `grunt install:real-time` and `grunt compile:minify`.

Any ideas?
I'm running sharelatex on ubuntu 14.04.01 and nginx. The last version was the one you offered as deb-package. To update to the new release I removed the /var/www/sharelatex folder and cloned the git-repo. Afterwards I followed the instructions from https://github.com/sharelatex/sharelatex/wiki/Updating and modified the stuff mentioned above.
`grunt check --force` says latexmk is too old? Could this cause the problem?

**Comment by jpallen** [comment]
You need to set `siteUrl` and `websocketsUrl` to wherever Nginx is listening, like `https://mysharelatex.example.com`.

**Comment by floriangeigl** [comment]
wow thanks for the fast answer... unfortunately I still get the same error...
```
 siteUrl : 'https://mypage.at'
 websocketsUrl: 'https://mypage.at'
```
To I also have to change the `url` in the same config at apis:web: from 'http://localhost:3000' to 'https://mypage.at'?

**Comment by jpallen** [comment]
Can you post the output of your javascript console in your browser please?

**Comment by floriangeigl** [comment]
I found out that the real-time service is not started during normal startup... starting it using grunt run:real-time leads shows "warn: websocket connection invalid" as soon as i try to open a project on the web front-end

Where can i activate the auto-start for the real-time service?
Any ideas concerning the websocket error?

**Comment by jpallen** [comment]
How have you installed ShareLaTeX? You'll need to add an extra upstart script for it, or whichever method you've used to start the other services.

**Comment by floriangeigl** [comment]
First I installed it using the .deb package. That time everything run nicely. Yesterday I wanted to update to the new version so I...
* cleaned my /var/www/sharelatex folder (`rm -r`)
* cloned the release branch using `sudo git clone -b release https://github.com/sharelatex/sharelatex.git /var/www/sharelatex` into /var/www/sharelatex
* followed the update instructions from https://github.com/sharelatex/sharelatex/wiki/Updating (`sudo npm install && sudo grunt install`).
* updated my config as described in https://github.com/sharelatex/sharelatex/wiki/Release-Notes---0.1.2
* updated nginx config as described in https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy
* run `grunt install:real-time` and `grunt compile:minify`

However, upstart scripts are minor problems. Probably if I just copy them from `https://github.com/sharelatex/sharelatex/tree/master/package/upstart` everything is fine. 
The major problem I'm currently having is: If I start the real-time service by myself and try to open a project, I always get "warn: websocket connection invalid" in the server console and a "502/Bad Gateway" in my browsers javascript console.

The server is behind a physical proxy which provides a valid certificate and forwards the connection to my 443 Port (SSL/nginx1.4.6). Do I have to use the ip of the physical proxy as `websocketUrl` or the real url `https://mypage.at`? Any other ideas what could cause this problem? I found a lot of threads in online forums where people have issues with nginx and websockets. Nevertheless, none of the suggested changes of the nginx-config fixed my problem.

thanks in advance!

**Comment by jpallen** [comment]
It sounds like there might be a problem at the Nginx layer. What do the Nginx logs say about these connections?

The `websocketsUrl` should be whichever URL you access in your browser (since it is passed to the client as the place to connect the websockets from your browser to the server).

**Comment by floriangeigl** [comment]
Thanks for all your efforts. We fixed it but we are not quite sure where the problem was. In the end we tried to get it running without nginx and without ssl. Than we added ssl and afterwards activated nginx. It could be that restarting all service via ´service restart sharelatex-...´ fixed the problem. One minor comment regarding the upstart files. Currently they are named in the repo without the .conf extension. As far as I know, upstart searches for files having a .conf extensions and thus doesn't load yours.  Thanks again!

**Comment by nortexoid** [comment]
This is supposed to be solved but still crops up for me (e.g. just now) on my Chromebook running Chrome OS version 55.0.2858.0 dev (64-bit), but has been happening on previous versions as well. It has never happened to me on my linux computer using Firefox.

**Comment by MichaelBuss** [comment]
Had the same error. Solution: Delete all hidden git-related files before zipping.
