### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by rubenmoor** [sharelatex/sharelatex#254]
It should be

        add-apt-repository

instead of `apt-add-repository`

Great project, I'm excited!

**Comment by jpallen** [comment]
Thanks, but where is this typo? I can't find anything like that in main README.

**Comment by rom1504** [comment]
I guess there https://github.com/sharelatex/sharelatex/wiki/Dependencies#redis

**Comment by jpallen** [comment]
Thanks, I've updated it now.
