### ISSUE TITLE
issues with nodemailer - unable to email

### ISSUE THREAD

**Issue by ilpepe** [sharelatex/sharelatex#257]
Hi,

I'm unable to send emails from sharelatex.

I wonder if nodemailer is installed  when installing sharelatex
Is there a way to test the installation of nodemailer?

I'm using the following setup.

 email:
#these are fictive e-mailadresses, as they don't exist
                fromAddress: "noreply@inbiosharelatex.be"
               replyTo: "noreply@inbiosharelatex.be"

                transport: "SMTP"
                parameters:

                        host: "smtp.foo.bar"
                        port: "25"
                        # Authentication
                       authMethod: "STARTTLS"
#my collegue said there was no login stuff needed?
                       auth: {
                                user: '',
                                pass: ''
                              }
                        # Secure connections:
                        # NB: nodemailer can have some issues with SSLv3
                        secureConnection: false

**Comment by jpallen** [comment]
Yes, nodemailer should be installed and get this config passed to it. Any problems should show up in the logs - what do they say when you try to send an email?

**Comment by hulk1st** [comment]
Just uncomment the four lines. This worked for me.

**Comment by hulk1st** [comment]
So:

        email:
                fromAddress: "ShareLaTeX@XY.Z"
                replyTo: "noreply"
                transport: "SMTP"
                parameters:
                        host: "host.xy.z"
                        port: "25"
                        # Authentication
                        #authMethod: "PLAIN"
                        #auth: {
                        #       user: '',
                        #       pass: ''
                        #       }
                        # Secure connections:
                        # NB: nodemailer can have some issues with SSLv3
                        secureConnection: false
        #               AWSAccessKeyID: ""
        #               AWSSecretKey: ""
