### ISSUE TITLE
Citation undefined

### ISSUE THREAD

**Issue by knutmagnus** [sharelatex/sharelatex#258]
Hi,

I used sharelatex last semester for a project, and I will reuse some of that in a new document, so I copy-pasted the input into a new sharelatex-document. I keep getting "Citation 'xx' on page x is undefined", which don't make any sense to me, because the main document is exactly the same as the last one. 

Any tips?

**Comment by jpallen** [comment]
Can you send us a link to the project at team@sharelatex.com please? We'll look into it. I'll close this since GitHub issues are for the open source code.
