### ISSUE TITLE
Custom config file does not change apis urls

### ISSUE THREAD

**Issue by atd** [sharelatex/sharelatex#260]
I am setting sharelatex with passenger's apache module. I want to change the default api urls for using virtual hosts, but sharelatex does not get the changes in my custom `settings.coffee`.

Changing them in `web/config/settings.defaults.coffee` does work

Changing the mongo database in my custom `settings.coffee` does also work.

**Comment by jpallen** [comment]
Can you post your settings file please (with sensitive parts redacted) and point out which parts you would like to change/aren't working? Pastebin might be the best place for the settings file.

**Comment by atd** [comment]
Sure! It is at http://pastebin.com/HTnxwFzY

All apis.* are not working

**Comment by jpallen** [comment]
The 'internal' part of the config tells each service where to listen. You've got them all trying to listen on port 80, which they can't do. Only one service can listen on one port. You'll need to have each service listen 'internally' on different ports, and then forward requests to them based on the host name in apache, which is listening on port 80. Keep the 'apis' entries as they are, since this tells the services where to look for each other externally, and in this case you probably want to them to go through apache. I hope that's clear.

**Comment by atd** [comment]
LOOOOOOOOL 

:flushed: :flushed: :flushed: 

I am using Apache, Phusion Passenger and Virtual Hosts. Trust me that you can have several services listening in port 80 with these tools.

Anyway, the issue is not about different services listening in the same port. It is that Sharelatex has a problem with configuration settings.

**Comment by jpallen** [comment]
We've never had problems with the config like this, so I suspect it is some interplay between Apache/Passenger that one or both of us doesn't understand. When you say it doesn't work, what does that look like? Are there errors in the logs? Is the web service still listening on port 3000?

**Comment by atd** [comment]
I am using `NODE_DEBUG=request` and I can see the requests.

They change when I change them in `web/config/settings.defaults.coffee` but not when I change them in  in my custom `settings.coffee`, as I posted in the top of the issue.

Sorry, but I don't have more time for this.

**Comment by jpallen** [comment]
Ok, well I'm really stumped why some of the config settings (mongo etc) get through but not the API stuff. The file must be being read and loaded so I don't understand why the api stuff isn't being read, sorry.

> Sorry, but I don't have more time for this.

No worries. Until we can figure out how to reproduce/get a bit more insight from things on your end I'll mark this as closed.
