### ISSUE TITLE
socket.io 404s

### ISSUE THREAD

**Issue by okennedy** [sharelatex/sharelatex#262]
I'm installing sharelatex on Redhat 5.8 with an apache reverse proxy on a virtual host.  I'm having difficulty getting past the document loading stage -- sharelatex crashes at this point.  The web developer console indicates that socket.io/socket.io.js is 404ing

![screen shot 2015-02-11 at 4 47 29 pm](https://cloud.githubusercontent.com/assets/3641553/6157308/54468dae-b20e-11e4-8c3f-c630e782c43a.png)

It doesn't look like this is a proxy issue, as curling from localhost seems to raise the same issue:
```
curl localhost:3000/socket.io/socket.io.js
<!DOCTYPE html><html itemscope itemtype="http://schema.org/Product"><head>
...
```

Any help would be greatly appreciated.

**Comment by jpallen** [comment]
In your reverse proxy you need to forward any /socket.io end point to the real-time service running at port 3026. We have documentation for this in the wiki for Nginx, but it should be possible to adapt for Apache easily: https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy

Did you follow any instructions for setting up Apache? If so can you let me know where so that I can get them updated?

**Comment by okennedy** [comment]
Thanks.  That seems to have (mostly) done it (my version of Redis seems to be out of date).  A few suggestions for improved documentation though...

* All of your startup scripts and documentation /etc... neglect to include the real-time service.  Took me a bit of digging to figure out how to get the 3026 service up and running.
   * https://github.com/sharelatex/sharelatex/wiki/Production-Installation-Instructions
   * https://github.com/sharelatex/sharelatex/tree/master/package/upstart
* Your default config file doesn't include the websocketsUrl parameter.  The default is localhost:3026 (which isn't useful unless you're running it locally)
* Attached is a few lines of apache config that create a virtual host analogous to the Nginx config you posted.

```
<Directory "[[[PATH TO SHARELATEX HERE]]]/web/public">
    Options Indexes MultiViews
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>

<VirtualHost *:80>
    ServerName [[[YOUR VIRTUAL HOST NAME HERE]]]
    ProxyPreserveHost On

    <LocationMatch "/socket.io">
      ProxyPass http://localhost:3026/socket.io
      ProxyPassReverse http://localhost:3026/socket.io
    </LocationMatch>

    Alias /stylesheets [[[PATH TO SHARELATEX HERE]]]/web/public/stylesheets
    Alias /minjs [[[PATH TO SHARELATEX HERE]]]/web/public/minjs
    Alias /img [[[PATH TO SHARELATEX HERE]]]/web/public/img

    <LocationMatch "/">
      ProxyPass http://localhost:3000/
      ProxyPassReverse http://localhost:3000/
    </LocationMatch>
</VirtualHost>
```

**Comment by jpallen** [comment]
Thanks, I've updated the upstart scripts and settings file now. If you'd like to create a page in the wiki about using Apache as a reverse proxy that would be great. I don't have much experience with Apache unfortunately otherwise I would.

**Comment by okennedy** [comment]
https://github.com/sharelatex/sharelatex/wiki/Apache-as-a-Reverse-Proxy

It doesn't handle static asset hosting --- I'm not sure how to pull that off without some crazy self-redirection.  Still, it should help people get started.

**Comment by jpallen** [comment]
Thanks!

**Comment by zeakey** [comment]
> 

Where is the example Nginx config about forward proxy? I'm setting up local overleaf service without docker and wanted to know how to setup the nginx forward proxy.

Thanks
