### ISSUE TITLE
You need to upgrade your account to use the History feature.

### ISSUE THREAD

**Issue by sennierer** [sharelatex/sharelatex#264]
Hi,

I installed sharelatex on a Debian server and it seems to run fine so far. However, I can't edit or even view projects because whenever I start or edit a project sharelatex complains: "You need to upgrade your account to use the History feature." There is a link to start a trial below that doesn't help. I tried to edit the user profile in mongo but setting "confirmed" to true didn't help either.

Anyone an idea? Thanks!

**Comment by jpallen** [comment]
You likely don't have the real-time service running (or at least not available via your proxy). Have a look at https://github.com/sharelatex/sharelatex/wiki/Release-Notes---0.1.2 for more info.

**Comment by sennierer** [comment]
thanks very much for your fast reply! I hadn't installed the real-time service! Its working now Thanks for the great software!!
