### ISSUE TITLE
Editing the standard emails doesn't work

### ISSUE THREAD

**Issue by marcAC** [sharelatex/sharelatex#266]
Hello everybody,

my ShareLaTeX is running fine now, but when I edit the EmailBuilder.coffee like it is described [here] (https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email) to format the "Share & reset password"-Emails nothing happens. I can do what I want with this file and I always get the standard-email.

Is the given information incorrect and I have to edit an other file?

Thanks in advance!

Best regards
Marc

**Comment by henryoswald** [comment]
You will need to recompile the coffee or you could just edit the JS but recompile is a better option.

grunt compile:server inside the web project would do the job.
