### ISSUE TITLE
Fix vertical scroll jumping (feature improvement)

### ISSUE THREAD

**Issue by tialis** [sharelatex/sharelatex#267]
Hi all, 

I found a bit bothering the "scroll jump" that appears when you change the width of the editor window. If you close the right panel (the compiled pdf document) the scroll "jumps" nearly 200 lines of code.

Is quite usual to open/close the file panel (left), specially if you have a small monitor. I think it would be interesting if changing editor width would leave the scroll in the same line of code.

Thank you for this great tool!

Cheers.

**Comment by henryoswald** [comment]
Hi,

we have not had anyone else report this, is it on all browsers for you? Closing for the moment, re open if it is still an issue.
