### ISSUE TITLE
Add all supported hot keys to the "Show hotkeys" panel

### ISSUE THREAD

**Issue by TarekHC** [sharelatex/sharelatex#268]
Hi all, 

I'm super happy with the new hotkeys Cntrl + I for Italic and Cntrl + B for Bold. (I discovered them by chance).

Could you please add all hotkeys to the "Show hotkeys" panel? 

Thank you! Cheers!

**Comment by yxliang01** [comment]
As this is implemented, @jpallen please close this issue.
