### ISSUE TITLE
job aborted, no legal \end found

### ISSUE THREAD

**Issue by maeishoj** [sharelatex/sharelatex#271]
So I am getting this annoying error for no reason.

My project compiles just fine on my machine, so I took an old template that used to compile on sharelatex and duplicated it. Then I proceeded to edit the individual pages, at least it would compile.

Then I modified a file "preamble.tex" where I do all my styling and I got that error.

I reverted to the previous preamble.tex version but it still wont compile now. 

I wonder why would it compile fine on my machine and not on sharelatex.

**Comment by jpallen** [comment]
Likely ShareLaTeX is trying to compile the preamble on its own when you have it open since it detects the \documentclass declaration. If you open one of your content files when you compile, and change the main document in the left menu then it should work.

**Comment by rabelonf** [comment]
Check in the Menu button  (above file explorer) if the option Main Document is correctly set to main.tex

**Comment by bhomaidan1990** [comment]
Hi,

I have the same issue and tried the upper solution, but it didn't work!
Here is my [overleaf document](https://www.overleaf.com/read/ndrpbtzgnqkr)

**Comment by kingchou007** [comment]
> 

Thanks
