### ISSUE TITLE
Cannot see login input box on chrome broswer

### ISSUE THREAD

**Issue by AntonOsika** [sharelatex/sharelatex#272]
Keeps loading. Can only see the following:
![image](https://cloud.githubusercontent.com/assets/4467025/6392339/014a080c-bdc0-11e4-9b06-96d1fdc60bb6.png)

Does not work after refreshing or in incognito. Does work on Safari.

Source code:
http://piratepad.net/t4wbmhYUbg

**Comment by henryoswald** [comment]
Your javascript is probably not loading. Can you look in your javascript
console. Its often todo with a reverse proxy you might have in front of it.

On Thu, Feb 26, 2015 at 1:04 PM, Anton Osika <notifications@github.com>
wrote:

> Keeps loading. Can only see the following:
> [image: image]
> <https://cloud.githubusercontent.com/assets/4467025/6392339/014a080c-bdc0-11e4-9b06-96d1fdc60bb6.png>
>
> Does not work after refreshing or in incognito. Does work on Safari.
>
> Source code:
>
> <!DOCTYPE html>
> Login - ShareLaTeX, Online LaTeX Editor
> ×
>  Click here to use ShareLaTeX in *Swedish*
> <https://sv.sharelatex.com/login>×Close
>
>    - Plans & Pricing <http:///user/subscription/plans>
>    - Help
>       - Documentation <http:///learn>
>       - Contact us <#14bc5fd42a2a82d5_>
>     - Register <http:///register>
>    - Log In <http:///login>
>
>  Log In
> Must be an email address
> <input type="password" name="password" required placeholder="*******"
> ng-model="password" class="form-control">required
> LoginLogging in...Forgot your password? <http:///user/password/reset>
>
>    -  <#14bc5fd42a2a82d5_>
>       - Language
>       - English <https://www.sharelatex.com/login>
>       - Spanish <https://es.sharelatex.com/login>
>       - Portuguese <https://pt.sharelatex.com/login>
>       - German <https://de.sharelatex.com/login>
>       - French <https://fr.sharelatex.com/login>
>       - Czech <https://cs.sharelatex.com/login>
>       - Dutch <https://nl.sharelatex.com/login>
>       - Swedish <https://sv.sharelatex.com/login>
>       - Italian <https://it.sharelatex.com/login>
>       - Turkish <https://tr.sharelatex.com/login>
>       - Chinese (Simplified) <https://cn.sharelatex.com/login>
>       - Norwegian <https://no.sharelatex.com/login>
>       - Danish <https://da.sharelatex.com/login>
>       - Russian <https://ru.sharelatex.com/login>
>       - Korean <https://ko.sharelatex.com/login>
>       - Japanese <https://ja.sharelatex.com/login>
>     - © 2015 ShareLaTeX
>    - Terms <http:///tos>
>    - Privacy <http:///privacy_policy>
>    - Security <http:///security>
>    - Contact <#14bc5fd42a2a82d5_>
>    - About <http:///about>
>    - Blog <http:///blog>
>    - Universities <http:///university?ref=footer>
>
>
>    -  <http://www.twitter.com/sharelatex>
>    -  <http://www.facebook.com/pages/ShareLaTeX/301671376556660>
>    -  <https://plus.google.com/115074691861228882827>
>    -  <https://github.com/sharelatex/sharelatex>
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/272>.
>



-- 
Henry Oswald
shareLaTeX.com creator

**Comment by floriangeigl** [comment]
Had the same problem. Solved it by deactivating AdBlock
