### ISSUE TITLE
Counting words using TeXcount (Improvement)

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#273]
Hi,

I think the integration of TeXcount ( http://app.uio.no/ifi/texcount/ ) would be a nice improvement, since many conferences have a word limit when submitting an abstract. Unfortunately I'm not skilled enough to do so.

Cheers

**Comment by jpallen** [comment]
+1

**Comment by henryoswald** [comment]
duplicate of this https://github.com/sharelatex/web-sharelatex/issues/4
