### ISSUE TITLE
Changing the log level / large log files

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#277]
Hi, this might be the wrong place but I did not know where else to post it:

I figured that the log files grow quite a lot, for example:
-rw-r--r-- 1 root root 343M Mar  3 00:20 document-updater.log
-rw-r--r-- 1 root root 372M Mar  3 08:01 web.log

Is there a way to change the log level to avoid getting such large log files so quickly?

Thanks!

**Comment by jpallen** [comment]
We don't really have 'log levels', sorry, it's just one big firehose. You could either log rotate them, or send them to /dev/null.
