### ISSUE TITLE
upgrade to 0.12/0.13: real-time error 403

### ISSUE THREAD

**Issue by blubbsy** [sharelatex/sharelatex#278]
Hi once again,

I updated the developer version after some time and now the editor does not load, but the pdf viewer does (and compiles fine etc.). 

What i found in the log is this error that i think may be the cause: 

```
ERROR: real-time-sharelatex/1108 on vmachine2: server side error in joinProject (project_id=547d84db067d7e122752bcca, doc_id=null, client_id=VK6J09610Mx-pDB6w$
    Error: non-success status code from web: 403
      at Request._callback (/var/www/sharelatex/real-time/app/js/WebApiManager.js:41:17)
      at Request.self.callback (/var/www/sharelatex/real-time/node_modules/request/request.js:121:22)
      at Request.EventEmitter.emit (events.js:98:17)
      at Request.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:978:14)
      at Request.EventEmitter.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:929:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)
```

I applied the things that are mentioned in the relase notes for 0.12, but iam not sure why i receive this error. 403 normally means forbidden access Oo

Happens to existing project and when creating new ones.

Sincerely
Blubbsy

**Comment by jpallen** [comment]
How have you installed ShareLaTeX? Can you check that the http auth credentials for the web api are the same in the settings file that is used for both real-time and web please?

**Comment by blubbsy** [comment]
Ok, after you said so i checked around and found in sharelatex\real-time\config is an additional config file which has to be configurated. Is this somewhere described in the wiki? 

So what i did was copying from the configfile in sharelatex/config/ the part "httpAuthUser", "httpAuthPass" and "sessionSecret" to replace the values in the sharelatex\real-time\config. Its still not working but now i noticed two other errors that come before the earlier one (fyi. the error still appears but later in the log):

```
 error passed to top level next middlewear (method=POST)
    Error: Forbidden

```
```
error accessing web api (project_id=54f57489461a5d6004c5b75e, user_id=5474494860b1e5b8494fec55)
    Error: non-success status code from web: 403
```
As far as i understand these are only for web, where/how do i set these for the real-time ?

**Comment by jpallen** [comment]
I think this is the same issue as here in #276. Let me know if you still trouble after following through the steps there.

**Comment by blubbsy** [comment]
apperently it was quite similar, but still i have trouble. now i dont get any errors but the GUI elements are not loading at all (i mean e.g. the menus; see screenshot) 
![unbenannt](https://cloud.githubusercontent.com/assets/8658377/6481280/6b8891c0-c25c-11e4-93fa-5381cd15f04f.png)

but the log does not give any error as far as i can see. everything is declared with INFO, no WARNING or ERROR at all. The modules pass the unit tests without any trouble. 
I think my error is related to the nginx configuration. i will check the config if it is related to the ssl configuration im running (even if it worked before the update)

**Comment by jpallen** [comment]
Can you check your Javascript console for errors, and also that you don't have Adblock or something similar blocking the javascript scripts.

**Comment by blubbsy** [comment]
ahh crap forgot about the console

![unbenannt](https://cloud.githubusercontent.com/assets/8658377/6483759/05a4ba82-c275-11e4-82fb-3645a9783293.png)

![unbenannt2](https://cloud.githubusercontent.com/assets/8658377/6483780/3374603e-c275-11e4-87ff-c64f0eed439d.png)

Okay here what you see is the lack of the minijs things. so i did a grund compile:minify to correct this issue. 

Whats interessting is that since the update i have to strictly use the adress as written in the config. Before i could access without trouble everything with http://*.domain.tld or https://*.domain.tld , independently if i put the www or not before it. now it gives a problem (in https://github.com/sharelatex/sharelatex/issues/276 its already mentioned) . So what iam doing now is changing everything directly to https and add to the nginx config a forward to the https domain.

**Comment by jpallen** [comment]
Is this all working for you now then?

**Comment by blubbsy** [comment]
so far it does. thanks ;)
