### ISSUE TITLE
Sharelatex started hanging with latest firefox?

### ISSUE THREAD

**Issue by ilpepe** [sharelatex/sharelatex#280]
Hi,

It seems sharelatex hangs and is slow with the latest firefox edition? It hangs at the 'lion screen'.

two errors pop up.
Warning: missing space before text for line 24 of jade file "/opt/sharelatex/web/app/views/project/list/side-bar.jade"
Warning: missing space before text for line 58 of jade file "/opt/sharelatex/web/app/views/project/editor/left-menu.jade"

However under chrome it seems to work...

any help?

**Comment by jpallen** [comment]
Can you post any errors from the javascript console please.

**Comment by ilpepe** [comment]
Hi, 
I will need somepointers how to do this.

I restarted the redis-server and it seems to work faster again, however the error/warnings seems to be there...

**Comment by jpallen** [comment]
The warnings are not a problem. If it's faster after restarting then redis then it doesn't sound like a javascript problem, so don't worry. Is your redis instance under a lot of load/memory usage?

**Comment by ilpepe** [comment]
after restarting it seems to be owkay, so I guess it is solved somehow.
Thanks for the help anyway!
