### ISSUE TITLE
Message "You need to upgrade your account to use the History feature."

### ISSUE THREAD

**Issue by ericvm** [sharelatex/sharelatex#281]
I keep getting this message whenever I try to open a project.

I have managed to install sharelatex on my Ubuntu 14.04 server, following this set of instructions: https://gist.github.com/moschlar/2b941f75a44fbac69993

I have checked issue https://github.com/sharelatex/sharelatex/issues/264  that says that the real-time service could not be running or I may have a problem in the reverse proxy configuration. The real-time service is running. My Apache server reverse proxy configuration is like this (following this example: https://github.com/sharelatex/sharelatex/wiki/Apache-as-a-Reverse-Proxy):

>listen 2000
>
>\<VirtualHost *:80>
>        ServerAdmin webmaster@localhost
>        DocumentRoot /var/www/html
>        ErrorLog ${APACHE_LOG_DIR}/error.log
>        CustomLog ${APACHE_LOG_DIR}/access.log combined
>\</VirtualHost>
>
>\<VirtualHost *:2000>
>    ServerName localhost
>    ProxyPreserveHost On
>
>    \<LocationMatch "/socket.io">
>      ProxyPass http://localhost:3026/socket.io
>      ProxyPassReverse http://localhost:3026/socket.io
>    \</LocationMatch>
>
>    \<LocationMatch "/">
>      ProxyPass http://localhost:3000/
>      ProxyPassReverse http://localhost:3000/
>    \</LocationMatch>
>\</VirtualHost>

**Comment by bauerj** [comment]
Look at the javascript console. You'll see, what's wrong there.

**Comment by ericvm** [comment]
I got this error from the console:

> http://10.10.27.208:2000/socket.io/socket.io.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by rica01** [comment]
Hello.

Im having similar problem.

I run into this problem when opening any project.

Any idea?

![image1](https://cloud.githubusercontent.com/assets/11340563/6516232/e3541ac2-c355-11e4-9ac3-42fd394ad835.png)

**Comment by jpallen** [comment]
Please make sure that you have `websocketsUrl` configured in your settings to point to wherever you are accessing sharelatex, e.g. `sharelatex.example.com`.

If that doesn't fix it, please post any errors you have on your javascript console.

Regards,
James

**Comment by PandaScience** [comment]
Hi again, same issue for me...still. Unfortunately, the old thread got closed.

The last 3 days I tried almost every combination of redis/mongodb/sharelatex-config on debian jessie and ubuntu 14.04 LTS and couldn't get any of these versions to work :( . Seems like my virtual machines don't like me. They always ended up with that history notification.

The JavaScript Console tells sth like "io not defined"
http://pastebin.com/a7PRnRkN

My config files for coffee and nginx are:
http://pastebin.com/G88PtaCC
http://pastebin.com/e8VzEb7J

As far as I understood the installation instructions, these config files should be ok?

Btw. you shouldn't use the official tutorial (http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/) for mongodb anymore since 2 days ago the new version 3.0.0 got released and the current sharelatex will throw an error on startup. 

Thanks for the help.

**Comment by jpallen** [comment]
@PandaScience Which URL are you accessing your ShareLaTeX install at? Is it `http://139.20.12.5:3000`?

**Comment by PandaScience** [comment]
nope, I wanted it to be simply 139.20.12.5, therefore I used nginx as reverse proxy listening in port 80

**Comment by jpallen** [comment]
Ok, can you change websocketsUrl to `http://139.20.12.5` please? (Drop the :3000 from it)

**Comment by PandaScience** [comment]
nothing has changed. still get the "...undefined" in js-console and the "history feature" notification

**Comment by jpallen** [comment]
You Nginx config is passing /socket.io to port 3000, but it needs to be port 3026.

**Comment by PandaScience** [comment]
hm, yes I changed this because settings.coffee line 101 reads 
"for nginx, websocketsURL should be the same as siteUrl".

the default setting was 
>siteUrl : 'http://localhost:3000'
>websocketsURL: 'http://localhost:3026'

which I changed according to instructions to
>siteUrl : 'http://139.20.12.5:3000'
>websocketsURL: 'http://139.20.12.5:3000'

and after your suggested changes it became
>siteUrl : 'http://139.20.12.5:3000'
>websocketsURL: 'http://139.20.12.5'

so I thought I also have to change this in nginx config. but anyways, I just tried it again with 
>location /socket.io {
>        proxy_pass http://localhost:3026;

but still doesn't seem to work, sry :(

**Comment by jpallen** [comment]
Can you test (curl) whether socket.io is available at localhost:3026/socket.io and http://139.20.12.5/socket.io please?

**Comment by PandaScience** [comment]
ah I should have mentioned that. I also tried that one before in the browser (found it in some other closed issue here) .

curl gives:
$ curl localhost:3026: 
> curl: (7) Failed to connect to localhost port 3026: Connection refused

$ curl http://139.20.12.5/socket.io
```HTML
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

**Comment by jpallen** [comment]
Do you have the real-time service running on port 3026?

**Comment by PandaScience** [comment]
hm, actually I don't really know how to check this. I had a look at [this](https://github.com/sharelatex/sharelatex/issues/264) issue and found [these](https://github.com/sharelatex/sharelatex/issues/264) instructions and only checked if it has been installed at all.

**Comment by jpallen** [comment]
How are you running the other services? Make sure there is a real-time
service set up in the same way.

**Comment by PandaScience** [comment]
for testing purposes, I've always done a 
> cd /var/www/sharelatex 
> grunt run

for later, I would have started searching how your provided upstart script has to be changed to work with debians sysvinit. I thought running 'grunt run' in the root directory would also spawn processes for all other services? seems not to be the case...

**Comment by ericvm** [comment]
@jpallen I'm accessing sharelatex through 10.10.27.208:2000 and my apache is set to reverse proxy localhost:3000 and localhost:3026 as in the configuration above. In my settings.cofee file, siteUrl is set to 10.10.27.208:2000 and my websocketsUrl is also set to 10.10.27.208:2000.

> curl 10.10.27.208:2000

Does not return a 404 message: http://pastebin.com/xcJ6JNpV

But the javascript console errors say http://10.10.27.208:2000/socket.io/socket.io.js responded with a 404 error: (http://pastebin.com/Mg342vPg)

I'm running there requests outside the server. Inside the server, curl localhost:3026/socket.io returns

>Welcome to socket.io.

**Comment by rica01** [comment]
Hi. 

My problem remains. i have checked the socketIO lines at the nginx and it appears to be ok.

Sharelatex works on localhost but not from the web; the curl from localhost returns a looooooong list of parameters and such: "/*! Socket.IO.min.js build:0.9.16, production. Copyright(c) 2011 LearnBoost <dev@learnboost.com> MIT Licensed */
var io="undefined"==typeof module?{}:module.exports;(function(){(function(a,b){var c=a;c.version="0.9.....ypeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this),typeof define=="function"&&define.amd&&define([],function(){return io})})()"

and curl from the web returns: curl: (7) Failed connect to 163.178.80.44:3026; Connection timed out

**Comment by PandaScience** [comment]
Hi again. Finally got it to work. Thanks a lot for all the help - best support ever! 
If you ever come to germany, I'll buy you a beer ;)

For everyone else trying to install the release branch on Debian 8, I'll summarize what I've learned so far here: https://pandascience.net/doku.php?id=tut:sharelatex

(just give me another few days since I'm really busy right now....)

**Comment by mickaelbaron** [comment]
Hi everybody,

I have the same problem. When i try to open any project i have also this message: "You need to upgrade your account to use the History feature". 

I use the ShareLatex docker image for installing it. I can register user, do any operation from the start page.

I notice when i register a user and when there is no project yet, the welcome message is uncomplete. It's written "Welcome to __appName__!". Normally, from my previous version it was written "Welcome to ShareLatex".

Any idea about this problem ?

Mickael

**Comment by jpallen** [comment]
@mickaelbaron Hmm, I recently updated our translations package and it may not be locked down properly in older versions, sorry. I'll look into this.

Which Docker image did you use? This should have had the translations installed when created so shouldn't have this problem.

**Comment by mickaelbaron** [comment]
@jpallen i'm using the official Docker image from here : https://github.com/sharelatex/sharelatex-docker-image/tree/master. When i browse the content of the Dockerfile file, it is the current release of ShareLatex which is used. I'm going to try with the master version of ShareLatex for building Docker image. 

Mickael

**Comment by mickaelbaron** [comment]
@jpallen it's working when i'm using the ShareLatex master version to build the ShareLatex Docker container. Do you want i create a pull request for this issue ?

**Comment by PandaScience** [comment]
speaking of translations...I just had a look at the german online version and you might want to correct the text there on occasion:

>Willkommen bei ShareLatex! Neu bei Sharelatex? Starte, indem du einen Blick auf unsere Vorlagen oder die Latex-Anleitung wirfst, oder erstelle dein erstes Projekt auf der linken Seite.

or even better 

>[...] Starte dein erstes Projekt, indem du einen Blick auf unsere Vorlagen[link] oder die Latex-Anleitung[link] wirfst, oder nutze einfach den Button auf der linken Seite.

**Comment by jpallen** [comment]
The translations package should now be locked down when using new release versions. The error with web sockets and 'free trial' showing up should also be fixed in the new release version. This issue has got large and with a few different topics, but I think the main request is now fixed, so I will close it. Please open new issues with any outstanding problems.
