### ISSUE TITLE
real-time app does not use the sharelatex config file

### ISSUE THREAD

**Issue by asirinelli** [sharelatex/sharelatex#283]
From the release branch, following the wiki instructions, I realised the real-time app is not reading the main sharelatex config file.

Here is what I have in my config file (`/etc/sharelatex/settings.coffee`):
```CoffeeScript
        internal:
                web:
                        port: webPort = 3000
                        host: "10.42.42.69"
                realTime:
                        port: realTimePort = 3026
                        host: "10.42.42.69"
```

I run the real-time app with the following command line:
```sh
SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee node /var/www/sharelatex/real-time/app.js
```

The output confirms the `netstat` report:
```json
{"name":"real-time-sharelatex","hostname":"latex","pid":1291,"level":30,"msg":"real-time-sharelatex listening on localhost:3026","time":"2015-03-08T19:51:59.453Z","v":0}
```

It is listening on loopback instead of one of the network interfaces. The web app works correctly.

**Comment by jpallen** [comment]
Hmm, this is odd, sorry. Can you double check that the `internal.realTime.host` config doesn't appear elsewhere in your settings file? Does changing the port work?

**Comment by asirinelli** [comment]
On Wed, Mar 11, 2015 at 04:32:58AM -0700, James Allen wrote:
> Hmm, this is odd, sorry. Can you double check that the
> `internal.realTime.host` config doesn't appear elsewhere in your
> settings file? Does changing the port work?

The only other place where it is configured is in
real-time/config/settings.defaults.coffee:

[...]
        internal:
                realTime:
                        port: 3026
                        host: "localhost"
[...]

And the only way to change the interface binding is to change this file.

Antoine

**Comment by jpallen** [comment]
Sorry for the slow reply. Can you check the whitespace in the settings file (tabs vs spaces)? Coffeescript is sensitive to this, and it's the only thing I can think that might be throwing the settings file off for some reason.

**Comment by henryoswald** [comment]
close due to inactivity.
