### ISSUE TITLE
List of all registered users

### ISSUE THREAD

**Issue by marcAC** [sharelatex/sharelatex#285]
Hello everybody,

is there somewhere a file with a list of all registered users? I don't want to change something on these users, I just want to get a small overview over the existing users.

Thanks for answers and best regards,
Marc

**Comment by devster31** [comment]
I believe users are stored in the users collection in MongoDB

**Comment by jpallen** [comment]
Yes, the easiest way will be something like:

```
mongoexport -d sharelatex -c users -f email --csv > sharelatex-emails.csv
```

**Comment by zeigerpuppy** [comment]
just a note for those interested.
If you are running mongodb on a separate docker container, you may need to access the mongodb instance on a different port.

check the port that sharemongo docker is redirecting to:
```bash
sudo docker ps
```

then include the port in the export statement
```bash
mongoexport -h localhost:32778 -d sharelatex -c users -f email --type=csv > sharelatex-emails.csv
```

**Comment by crockeea** [comment]
This either no longer works, or there is insufficient detail to reproduce.

**Comment by tsnowak** [comment]
> This either no longer works, or there is insufficient detail to reproduce.
> 
> I was able to do this:
> `docker exec <container name> sh -c 'exec mongoexport -d sharelatex -c users -f email --type=csv' > sharelatex-emails.csv`

Where `<container name>` is `mongo`. Just to clarify.

**Comment by iggygeek** [comment]
??

**Comment by lytex** [comment]
The port has changed. Now the command is something like:
`docker exec -it mongo mongoexport -h localhost:27017 -d sharelatex -c users -f email --type=csv`
