### ISSUE TITLE
Remove the Dropbox-Sync-Button in projects

### ISSUE THREAD

**Issue by marcAC** [sharelatex/sharelatex#286]
Hello everybody,

is it possible to remove the marked area of code? We don't want to use the Dropbox-Sync and the link goes into nothing because of that. So to avoid misunderstanding of our colleagues we want to remove this part completely out of the web-interface and I don't find this section of code by myself.

![dropbox](https://cloud.githubusercontent.com/assets/10206202/6688882/01185b8a-ccb7-11e4-9a03-fe093d4df92e.JPG)

Thanks for help and best regards,
Marc

**Comment by jpallen** [comment]
If you run the latest version of ShareLaTeX, this button has been removed when not in use.
