### ISSUE TITLE
Socket.io still target localhost

### ISSUE THREAD

**Issue by mickaelbaron** [sharelatex/sharelatex#287]
Hi,

I'm installing ShareLaTeX through Docker. Three docker containers are used: one for Redis, one for MongoDB and one for ShareLatex. For the last one i exposed the port: 80. This configuration based on Docker is working on localhost (for local test i used Vagrant).

When i tried to deploy this configuration on host server i.e. not in localhost (with a specific domain: http://mydomain for example) ShareLatex wants to acces to socket.io by localhost. In fact, i noticed that thanks the Chrome console.

```
GET http://localhost/socket.io/1/?t=1426689041229 net::ERR_CONNECTION_REFUSED
```

Any idea about my problem ?

Mickael

**Comment by ceriathstudios** [comment]
Yes indeed, i had the same problem two weeks ago.
You just have to change the siteUrl and websocketsUrl in your settings.coffee file. They should point on the domain you are using, not to localhost.
Hope this will fix it.

**Comment by mickaelbaron** [comment]
Good idea and it's working.

In fact, i changed the siteUrl by the SHARELATEX_SITE_URL docker environment: 

```
$ sudo docker run -d -v /var/sharelatex:/var/lib/sharelatex -p 80:80 --link redis:redis --link mongodb:mongodb --name=sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongodb/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_SITE_URL=http://mydomain lias/sharelatex
```

However, no need to change the value of websocketsUrl.

Thanks a lot

Mickael
