### ISSUE TITLE
Recover from bad backup?

### ISSUE THREAD

**Issue by barracks510** [sharelatex/sharelatex#289]
I restored a broken installation from a disk backup but lost Redis and MongoDB databases. I only have `/var/lib/sharelatex/` recovered. There should be a way to scan that folder and recover the data to an admin account (create a database entry for every "unknown/alien" object with ownership of the admin and display recoverable files in a lost+found tab in the admin interface).

**Comment by jpallen** [comment]
I'm really sorry to hear you've had data loss. I'm afraid there's no way to easily recover the state of these files, sorry. The data is /var/lib/sharelatex only contains the binary files that were uploaded, not any of the text files (these are stored in the Mongo database).

What happened to cause the broken installation/data loss? Is it something we could have helped to prevent?

**Comment by barracks510** [comment]
I'm not sure what caused the bad backup. But it makes sense that all text is in the database. Perhaps a better backup solution is all.

**Comment by henryoswald** [comment]
With mongo you can look at mms which offers free backups for smaller dbs. We are not going to be writing any custom backup tools I'm afraid.
