### ISSUE TITLE
ShareLaTeX stopped working / Stuck at loading project

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#290]
For some reason ShareLaTeX doesn't work anymore. It stops when clicking on a Project. The loading bar progresses to about one third and then stops. In Firebug I get:

Error: Script error for: mathjax http://requirejs.org/docs/errors.html#scripterror

c,d,m)):b[l]=c});return b}function v(b,c){return function(){return c.apply(b,arguments)}}function ca(b){throw b;}function da(b){if(!b)return b;var c=ba;z(b.split("."),function(b){c=c[b]});return c}function B(b,c,d,m){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=m;d&&(c.originalError=d);return c}function ia(b){function c(a,f,C){var e,n,b,c,d,T,k,g=f&&f.split("/");e=g;var l=j.map,h=l&&l["*"];if(a&&"."===a.charAt(0))if(f){e=m(j.pkgs,f)?g=[f]:g.slice(0,g.length-

Any ideas?

Thanks in advance!

Update:

Safari spits out a little more information:

https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML&fingerprint=7a7cc81facdcc49cbaefc5295a83b0a4-5e52def76813cfe5e57f33a77dcea81d
[Error] Failed to load resource: Server not found. (MathJax.js, line 0)

Error: Script error for: mathjax
http://requirejs.org/docs/errors.html#scripterror

I guess that already explains the problem. I had no idea ShareLaTeX depends on external resources like MathJax. It looks like their website is currently offline but sporadically comes back.

So case closed, I guess.

**Comment by jpallen** [comment]
Is this a local install, or on www.sharelatex.com? Are you on a network that might be blocking https://cdn.mathjax.org? We've found it to be very reliable in general.

**Comment by hulk1st** [comment]
It's a local installation but connected to a university network, so pretty reliable in general as well. It has been running now for months without problems and I only experienced it yesterday for some hours. But because it partly worked but only got stuck at the loading bar, I suspected it might be a problem either on the server or on the client side instead of a third party issue. Later on I also noticed, I could not access mathjax.org from home, so it might have been a routing problem or the page indeed was down for some time.

Nevertheless, now everything works fine again. The reason what made me suspicious was the fact, that immediately before a firefox update got released and I first thought, it might be related to this.

**Comment by jpallen** [comment]
Thanks for the update. I think we actually moved to a local version of mathjax in a recent ShareLaTeX update. Are you running an older version? (The latest is 0.1.4, but 0.1.2 should also have the local mathjax I believe).

Regards,
James

**Comment by hulk1st** [comment]
It might still be 0.1.0, i.e., the first one where a package was provided for Ubuntu 12.04.

**Comment by jpallen** [comment]
We've stopped providing packages for Ubuntu now I'm sorry to say (they were hard to maintain and lots of people didn't use Ubuntu), but there are up to date installation instructions at https://github.com/sharelatex/sharelatex/wiki, and a Docker container available at https://github.com/sharelatex/sharelatex-docker-image

**Comment by hulk1st** [comment]
I am heavily flirting with the latest version especially due to the added user management capabilities which really is an exceptionally great improvement but I am still a little afraid because I fear something might go wrong in the process of update and I might lose some data.

**Comment by jpallen** [comment]
If you're worried, then it should be possible to install the new version on a new server, and then copy the data across by copying the Mongo database and files in the ShareLaTeX data directory on disk.

**Comment by hulk1st** [comment]
Great! Thanks a lot for this hint, I'll try that and keep you posted. We wanted to move the system to a stronger server anyway, so I'll keep this in mind. Again, thanks a lot, I'll keep you posted! Best regards
