### ISSUE TITLE
Misspelings in Russian translation

### ISSUE THREAD

**Issue by yourconscience** [sharelatex/sharelatex#293]
Hi there!

First of all, thank you a lot for an opportunity to use ShareLatex in my native language. This is really nice. However, i've noticed a couple of misspellings in error messages.
1) "Ошибка сервера К сожалению, что-то пошло не так и мы не смогли скомпелировать Ваш проект. Попробуйте еще раз через пару минут.", while the correct spelling is "Ошибка сервера. К сожалению, что-то пошло не так, и мы не смогли скомпилировать Ваш проект. Попробуйте еще раз через пару минут."
2) "Ошибка компиляции. К сожалению Ваш LaTeX документ не может быть скомпилирован. Пожалуйста, проверьте сообщения об ошибках внизу, или просмотрите лог-файл.", while the correct spelling is "Ошибка компиляции. К сожалению, Ваш LaTeX документ не может быть скомпилирован. Пожалуйста, проверьте сообщения об ошибках ниже или просмотрите лог-файл."
Thanks for your attention.

**Comment by henryoswald** [comment]
Thanks, we actually rely on aspell dictionaries if you could open an issue with them that would be great.
