### ISSUE TITLE
Wrong link in invitation email

### ISSUE THREAD

**Issue by PandaScience** [sharelatex/sharelatex#295]
Hi, it's me again :)
Just set up the new v0.1.4 and encountered a little problem. Maybe it's worth an improvement.
In case the user decided to use a reverse proxy, the links for password setting and login are wrong since the email builder uses `siteUrl` which is not necessary the same as the URL used to access the server.

In my case nginx listens to http://My.Ip while in the invitation email, the user is asked to visit http://My.Ip:3000/...

For now I just hard-coded the correct address, but you maybe want to introduce a new variable in e.g. appUrl which can also be set in `/web/config/settings.defaults.coffee` or even better in `/etc/sharelatex/settings.coffee` ? Sry I didn't provide a pull request, but I'm not much of a coffeescript/node.js/whatever-you-used-here programmer.

Best regards

**Comment by ilpepe** [comment]
Hi,
As a temporary fix, where have you hardcoded it?

Pieter

**Comment by PandaScience** [comment]
Hi, 
you have to modify `sharelatex/web/app/js/Features/Email/EmailBuilder.js` as I described [here](https://pandascience.net/doku.php?id=tut:sharelatex&#email_per_exim4).

**Comment by hulk1st** [comment]
Hi,

I am wondering: why would siteUrl not coincide with the URL from your server?

**Comment by PandaScience** [comment]
Hi, 

In the exact case I described above. If your proxy listens to say FQDN:80 (http) or FQDN:443 (https) and redirects to FQDN:3000 (sharelatex). Not giving a port in a link uses the standard port of the protocol, for http -> 80. Therefore http://FQDN:3000 is not the same as http://FQDN. Ok, I could also enable ingoing port 3000 but then where is the point in using a reverse proxy at all. :wink:

**Comment by jpallen** [comment]
@PandaScience The `siteUrl` should be set to wherever you access your site publicly, so in this case it should be "http://FQDN". This is exactly what `siteUrl` is used for: to populate things like public links where we need to know where the site is accessible.
