### ISSUE TITLE
Mongo: Driver is incompatible with this server version

### ISSUE THREAD

**Issue by redfern314** [sharelatex/sharelatex#296]
When installing from the Docker image and using the latest Mongo version (3.0.1), I got the following error when creating the initial admin user:
*Fatal error: driver is incompatible with this server version*

For reference, this is the command I used to get the error: 
*$ docker exec sharelatex /bin/bash -c "cd /var/www/sharelaex/web; grunt create-admin-user --email joe@example.com"*

This install was on a fresh Google Cloud instance running Ubuntu 14.04.

No debug information was provided (even after adding verbose flags to the docker command and grunt command), but the issue was fixed by using an older Mongo release (2.6.9). A Google search of the error reveals very little - the only reason I suspected Mongo was the issue was several Meteor-related threads that referenced Mongo as the issue. Unclear whether this is reproducible by other users since I don't see any other issues opened on this topic.

**Comment by Delphinator** [comment]
Just ran into this issue as well. I tried the docker image and used the mongo and redis docker images for the two databases. Using mongodb 2.6.9 instead of 3.0.1 works.

**Comment by jpallen** [comment]
I've updated our dependencies page to document this. It should just be a case of upgrading the driver we are using. We're planning our upgrade to Mongo 3 at sharelatex.com, so this will be supported in the future.

**Comment by Andymic** [comment]
Using db version : 3.0.2 and driver version :1.3.x, I get the same error on Ubuntu 14.04

**Comment by calent** [comment]
db version:3.0.2;
MongoError: driver is incompatible with this server version
on window 7, 64 bit

**Comment by henryoswald** [comment]
we should have this updated in the next few weeks.

**Comment by namdevk** [comment]
update your moongoos

**Comment by henryoswald** [comment]
fixed https://github.com/sharelatex/web-sharelatex/commit/d97e2b35f6b56a6b5589cdf6993a2cde7b9bd913

**Comment by zzoru** [comment]
Dockerfile has a problem by this issue.
Because, release version of sharelatex's file: sharelatex/Gruntfile.coffee
clones sharelatex/web-sharelatex's v0.20! 

We must refine a dockerfile.

**Comment by exislow** [comment]
When will you fix the Dockerfile?
