### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by dpasqualin** [sharelatex/sharelatex#298]
Hello, I'm not sure where to post feature requests, but I would like to know if there is any intention to enable kerberos support on sharelatex anytime soon. If not, could someone give me a hint where should I look to develop it?

Thanks

**Comment by jpallen** [comment]
We've got a successful prototype LDAP module developed, and it should be possible to add Kerberos support in a similar way. Our LDAP code isn't public at the moment, but if you drop us an email at team@sharelatex.com, we discuss this further and provide you with support for developing something. What's your use case for this?

**Comment by dpasqualin** [comment]
I work in a research group in a public University in Brazil and we would love to provide an instance of this great project called Sharelatex for our students! Our labs are equipped with Linux using a remote boot system with kerberos for authentication. Would be nice to allow them to log into Sharelatex using the same id as in our labs.

I'm aware of the [Sharelatex for Universities](https://pt.sharelatex.com/university?ref=footer) project, which is really cool, but unfortunately there is no budget (and probably never will be) for anything like that here.

**Comment by henryoswald** [comment]
closing as this is about to become available as part of ShareLaTeX server pro.
