### ISSUE TITLE
Stuck at 'Sorry, something went wrong and your project could not be compiled.'

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#300]
Dear all,

I have a project I am unable to compile. No error message etc. besides the "Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments."

The user data folder is readable by the sharelatex user, latexmk is installed and working. It is a new server and this happens only at one out of four projects I have uploaded so far. Here are the sharelatex-web.log and the clsi.log:

sharelatex-web.log:

{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"Generating file fingerprints...","time":"2015-04-16T12:16:30.471Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/libs/require.js: 0cb51c1a5e8e978cbe069c07f3b8d16d","time":"2015-04-16T12:16:30.474Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/ide.js: 4482fdc26aed93fc4b510660c08cabe4","time":"2015-04-16T12:16:30.477Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/main.js: 837f0822448d88de87ada30622197de9","time":"2015-04-16T12:16:30.478Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/libs.js: 7fcc5ec2b49dde4ee318dba8871b8bfe","time":"2015-04-16T12:16:30.479Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/ace/ace.js: 51eeec551a4ee9c3a27e02208c2b3c5b","time":"2015-04-16T12:16:30.482Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/libs/pdfjs-1.0.712/pdf.js: 92166e6b2d08654676b0d8cd9626e3bf","time":"2015-04-16T12:16:30.483Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/libs/pdfjs-1.0.712/pdf.worker.js: 210811c9e9352ad6a85d17bd9fec15ce","time":"2015-04-16T12:16:30.488Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/minjs/libs/pdfjs-1.0.712/compatibility.js: b77271860c12ab8774593f7aee8e6dbf","time":"2015-04-16T12:16:30.488Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"/var/www/sharelatex/web/public/stylesheets/style.css: 027cf2f86c546e7ab2b30d70a3c55420","time":"2015-04-16T12:16:30.489Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"Production Enviroment","time":"2015-04-16T12:16:32.636Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"","time":"2015-04-16T12:16:32.699Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"web-sharelatex listening on port 3000","time":"2015-04-16T12:16:32.719Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"msg":"300 sockets enabled","time":"2015-04-16T12:16:32.719Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"ns":"sharelatex.subscriptions"},"query_type":"query","collection":"sharelatex.system.indexes","response-time":2,"msg":"mongo request","time":"2015-04-16T12:16:32.777Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{},"query_type":"query","collection":"sharelatex.systemmessages","response-time":2,"msg":"mongo request","time":"2015-04-16T12:16:50.374Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:50.390Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55244c42f112c97008264bd3"},"query_type":"query","collection":"sharelatex.users","response-time":2,"msg":"mongo request","time":"2015-04-16T12:16:50.454Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"user":{"id":"55244c42f112c97008264bd3","email":"jimbo.jones@xyz.edu"},"project":{"id":"552f3b9fa9f645c304d49ddc","name":"Website for IMT"},"msg":"Checking if can access","time":"2015-04-16T12:16:50.456Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"user_id":"55244c42f112c97008264bd3","msg":"getting users subscription","time":"2015-04-16T12:16:50.460Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":8,"msg":"mongo request","time":"2015-04-16T12:16:50.467Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55244c42f112c97008264bd3"},"query_type":"query","collection":"sharelatex.users","response-time":8,"msg":"mongo request","time":"2015-04-16T12:16:50.468Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"admin_id":"55244c42f112c97008264bd3"},"query_type":"query","collection":"sharelatex.subscriptions","response-time":12,"msg":"mongo request","time":"2015-04-16T12:16:50.473Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":{"$in":["55244c42f112c97008264bd3"]}},"query_type":"query","collection":"sharelatex.users","response-time":2,"msg":"mongo request","time":"2015-04-16T12:16:50.473Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":{"$in":["55256dd52f29e2a1123e555c"]}},"query_type":"query","collection":"sharelatex.users","response-time":4,"msg":"mongo request","time":"2015-04-16T12:16:50.477Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"user":{"id":"55244c42f112c97008264bd3","email":"jimbo.jones@xyz.edu"},"project":{"id":"552f3b9fa9f645c304d49ddc","name":"Website for IMT"},"msg":"Checking if can access","time":"2015-04-16T12:16:50.489Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"req":{"url":"/project/552f3b9fa9f645c304d49ddc","method":"GET","referrer":"http://sharelatex.imt.xyz.edu/project","remote-addr":"100.200.200.78","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"},"res":{"statusCode":304},"response-time":2138,"msg":"http request","time":"2015-04-16T12:16:52.516Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"user_id":"55244c42f112c97008264bd3","project_id":"552f3b9fa9f645c304d49ddc","msg":"join project request","time":"2015-04-16T12:16:53.512Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":4,"msg":"mongo request","time":"2015-04-16T12:16:53.519Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55256dd52f29e2a1123e555c"},"query_type":"query","collection":"sharelatex.users","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.523Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55244c42f112c97008264bd3"},"query_type":"query","collection":"sharelatex.users","response-time":2,"msg":"mongo request","time":"2015-04-16T12:16:53.524Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55244c42f112c97008264bd3"},"query_type":"query","collection":"sharelatex.users","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.526Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"user":{"id":"55244c42f112c97008264bd3"},"project":{"id":"552f3b9fa9f645c304d49ddc","name":"Website for IMT"},"msg":"Checking if can access","time":"2015-04-16T12:16:53.526Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"req":{"url":"/project/552f3b9fa9f645c304d49ddc/join?user_id=55244c42f112c97008264bd3","method":"POST","remote-addr":"127.0.0.1","content-length":"0"},"res":{"statusCode":200},"response-time":23,"msg":"http request","time":"2015-04-16T12:16:53.534Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":2,"msg":"mongo request","time":"2015-04-16T12:16:53.559Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55244c42f112c97008264bd3"},"query_type":"query","collection":"sharelatex.users","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.561Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"user":{"id":"55244c42f112c97008264bd3","email":"jimbo.jones@xyz.edu"},"project":{"id":"552f3b9fa9f645c304d49ddc","name":"Website for IMT"},"msg":"Checking if can access","time":"2015-04-16T12:16:53.561Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"options":{"isAutoCompile":true},"project_id":"552f3b9fa9f645c304d49ddc","msg":"got compile request","time":"2015-04-16T12:16:53.563Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"canCompile":true,"opts":{"endpointName":"auto_compile","timeInterval":20,"subjectName":"everyone","throttle":25},"msg":"checking if auto compile limit has been hit","time":"2015-04-16T12:16:53.565Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","user_id":"55244c42f112c97008264bd3","msg":"compiling project","time":"2015-04-16T12:16:53.566Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.568Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"flushing project from document updater","time":"2015-04-16T12:16:53.570Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"doc_id":"552fa1f9a2293d8f046b9b1f","project_id":"552f3b9fa9f645c304d49ddc","msg":"receiving set document request from api (docupdater)","time":"2015-04-16T12:16:53.587Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.589Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552fa1f9a2293d8f046b9b1f","msg":"updating doc lines","time":"2015-04-16T12:16:53.589Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552fa1f9a2293d8f046b9b1f","msg":"telling docstore manager to update doc","time":"2015-04-16T12:16:53.591Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552fa1f9a2293d8f046b9b1f","msg":"updating doc in docstore api","time":"2015-04-16T12:16:53.591Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552fa1f9a2293d8f046b9b1f","msg":"update doc in docstore url finished","time":"2015-04-16T12:16:53.603Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552fa1f9a2293d8f046b9b1f","modified":false,"msg":"finished updating doc lines","time":"2015-04-16T12:16:53.603Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"doc_id":"552fa1f9a2293d8f046b9b1f","project_id":"552f3b9fa9f645c304d49ddc","msg":"finished receiving set document request from api (docupdater)","time":"2015-04-16T12:16:53.603Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"req":{"url":"/project/552f3b9fa9f645c304d49ddc/doc/552fa1f9a2293d8f046b9b1f","method":"POST","remote-addr":"127.0.0.1","content-length":"3226"},"res":{"statusCode":200},"response-time":18,"msg":"http request","time":"2015-04-16T12:16:53.604Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"doc_id":"552f3b9fa9f645c304d49ddd","project_id":"552f3b9fa9f645c304d49ddc","msg":"receiving set document request from api (docupdater)","time":"2015-04-16T12:16:53.612Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.613Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3b9fa9f645c304d49ddd","msg":"updating doc lines","time":"2015-04-16T12:16:53.613Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3b9fa9f645c304d49ddd","msg":"telling docstore manager to update doc","time":"2015-04-16T12:16:53.614Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3b9fa9f645c304d49ddd","msg":"updating doc in docstore api","time":"2015-04-16T12:16:53.614Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3b9fa9f645c304d49ddd","msg":"update doc in docstore url finished","time":"2015-04-16T12:16:53.619Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3b9fa9f645c304d49ddd","modified":false,"msg":"finished updating doc lines","time":"2015-04-16T12:16:53.619Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"doc_id":"552f3b9fa9f645c304d49ddd","project_id":"552f3b9fa9f645c304d49ddc","msg":"finished receiving set document request from api (docupdater)","time":"2015-04-16T12:16:53.619Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"req":{"url":"/project/552f3b9fa9f645c304d49ddc/doc/552f3b9fa9f645c304d49ddd","method":"POST","remote-addr":"127.0.0.1","content-length":"3226"},"res":{"statusCode":200},"response-time":9,"msg":"http request","time":"2015-04-16T12:16:53.620Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"doc_id":"552f3cd7a9f645c304d49de6","project_id":"552f3b9fa9f645c304d49ddc","msg":"receiving set document request from api (docupdater)","time":"2015-04-16T12:16:53.626Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.628Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3cd7a9f645c304d49de6","msg":"updating doc lines","time":"2015-04-16T12:16:53.628Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3cd7a9f645c304d49de6","msg":"telling docstore manager to update doc","time":"2015-04-16T12:16:53.629Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3cd7a9f645c304d49de6","msg":"updating doc in docstore api","time":"2015-04-16T12:16:53.629Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3cd7a9f645c304d49de6","msg":"update doc in docstore url finished","time":"2015-04-16T12:16:53.634Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","doc_id":"552f3cd7a9f645c304d49de6","modified":false,"msg":"finished updating doc lines","time":"2015-04-16T12:16:53.634Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"doc_id":"552f3cd7a9f645c304d49de6","project_id":"552f3b9fa9f645c304d49ddc","msg":"finished receiving set document request from api (docupdater)","time":"2015-04-16T12:16:53.635Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"req":{"url":"/project/552f3b9fa9f645c304d49ddc/doc/552f3cd7a9f645c304d49de6","method":"POST","remote-addr":"127.0.0.1","content-length":"3225"},"res":{"statusCode":200},"response-time":9,"msg":"http request","time":"2015-04-16T12:16:53.635Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"flushed project from document updater","time":"2015-04-16T12:16:53.639Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":0,"msg":"mongo request","time":"2015-04-16T12:16:53.641Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"55256dd52f29e2a1123e555c"},"query_type":"query","collection":"sharelatex.users","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.642Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":0,"msg":"mongo request","time":"2015-04-16T12:16:53.643Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"getting all docs for project","time":"2015-04-16T12:16:53.645Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"getting all docs for project in docstore api","time":"2015-04-16T12:16:53.645Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"getting all folders for project","time":"2015-04-16T12:16:53.652Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.653Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"count":11,"project_id":"552f3b9fa9f645c304d49ddc","msg":"returning docs for project","time":"2015-04-16T12:16:53.654Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"getting all files for project","time":"2015-04-16T12:16:53.654Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"getting all folders for project","time":"2015-04-16T12:16:53.655Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"query":{"_id":"552f3b9fa9f645c304d49ddc"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-04-16T12:16:53.656Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"sending compile to CLSI","time":"2015-04-16T12:16:53.658Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":30,"req":{"url":"/spelling/check","method":"POST","referrer":"http://sharelatex.imt.xyz.edu/project/552f3b9fa9f645c304d49ddc","remote-addr":"100.200.200.78","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17","content-length":"3470"},"res":{"statusCode":200},"response-time":11,"msg":"http request","time":"2015-04-16T12:16:54.789Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":50,"err":{"message":"CLSI returned non-success code: 500","name":"Error","stack":"Error: CLSI returned non-success code: 500\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Compile/ClsiManager.js:88:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"project_id":"552f3b9fa9f645c304d49ddc","msg":"CLSI returned failure code","time":"2015-04-16T12:18:53.920Z","v":0}
{"name":"web-sharelatex","hostname":"sharelatex","pid":2602,"level":50,"err":{"message":"CLSI returned non-success code: 500","name":"Error","stack":"Error: CLSI returned non-success code: 500\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Compile/ClsiManager.js:88:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"url":"/project/552f3b9fa9f645c304d49ddc/compile?auto_compile=true","method":"POST","msg":"error passed to top level next middlewear","time":"2015-04-16T12:18:53.922Z","v":0}

clsi.log:
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"msg":"CLSI listening on localhost:3013","time":"2015-04-16T12:16:34.948Z","v":0}
Executing (default): SELECT * FROM `Projects` WHERE `Projects`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
Executing (default): UPDATE `Projects` SET `project_id`='552f3b9fa9f645c304d49ddc',`lastAccessed`='2015-04-16 12:16:53',`id`=15,`createdAt`='2015-04-16 04:33:37',`updatedAt`='2015-04-16 12:16:53' WHERE `id`=15
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"project_id":"552f3b9fa9f645c304d49ddc","msg":"starting compile","time":"2015-04-16T12:16:53.828Z","v":0}
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"directory":"/var/lib/sharelatex/data/compiles/552f3b9fa9f645c304d49ddc","msg":"getting output files","time":"2015-04-16T12:16:53.829Z","v":0}
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"args":["/var/lib/sharelatex/data/compiles/552f3b9fa9f645c304d49ddc","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2015-04-16T12:16:53.829Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49dde' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49dde","lastModified":"2015-04-16T04:38:46.000Z","msg":"URL is up to date in cache","time":"2015-04-16T12:16:53.862Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49de0' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49de0","lastModified":"2015-04-16T04:38:46.000Z","msg":"URL is up to date in cache","time":"2015-04-16T12:16:53.870Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49de1' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49de1","lastModified":"2015-04-16T04:38:46.000Z","msg":"URL is up to date in cache","time":"2015-04-16T12:16:53.874Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49de2' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd6a9f645c304d49de2","lastModified":"2015-04-16T04:38:46.000Z","msg":"URL is up to date in cache","time":"2015-04-16T12:16:53.876Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd7a9f645c304d49de3' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd7a9f645c304d49de3","lastModified":"2015-04-16T04:38:47.000Z","msg":"URL is up to date in cache","time":"2015-04-16T12:16:53.878Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd7a9f645c304d49de4' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd7a9f645c304d49de4","lastModified":"2015-04-16T04:38:47.000Z","msg":"URL is up to date in cache","time":"2015-04-16T12:16:53.880Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd7a9f645c304d49de5' AND `UrlCaches`.`project_id`='552f3b9fa9f645c304d49ddc' LIMIT 1;
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"url":"http://localhost:3009/project/552f3b9fa9f645c304d49ddc/file/552f3cd7a9f645c304d49de5","lastModified":"2015-04-16T04:38:47.000Z","msg":"downloading URL","time":"2015-04-16T12:16:53.882Z","v":0}
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":50,"err":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at createHangUpError (http.js:1473:15)\n    at Socket.socketOnEnd [as onend] (http.js:1569:23)\n    at Socket.g (events.js:180:16)\n    at Socket.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:448:13)","code":"ECONNRESET"},"project_id":"552f3b9fa9f645c304d49ddc","msg":"error running compile","time":"2015-04-16T12:18:53.902Z","v":0}
Thu, 16 Apr 2015 12:18:53 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at app/js/CompileController.js:58:24
{"name":"clsi","hostname":"sharelatex","pid":2661,"level":30,"req":{"url":"/project/552f3b9fa9f645c304d49ddc/compile","method":"POST","remote-addr":"127.0.0.1","content-length":"52206"},"res":{"statusCode":500},"response-time":120240,"msg":"http request","time":"2015-04-16T12:18:53.912Z","v":0}

Thanks in advance!

**Comment by hulk1st** [comment]
Got it to work. There was a file included in the project that had 0 byte file size.

**Comment by eyildiz-ugoe** [comment]
I keep getting the same annoying error and I do not have a 0 byte file. I do have include .pdf and many images. What could be the reason?

**Comment by jbrant** [comment]
@eyildiz-ugoe same here - I think this project has been abandoned.

**Comment by jbrant** [comment]
I was getting this message as well, but it seems to have been because I wasn't running Overleaf as a privileged user.

**Comment by latifa1999** [comment]
I was getting the same message too. This problem may arise as a result of the internet connection. The simple way to resolve this problem is to reload the Overleaf editor by refreshing your browser.
