### ISSUE TITLE
sharelatex: Error opening document Sorry, something went wrong opening this document. Please try again.

### ISSUE THREAD

**Issue by aukauk** [sharelatex/sharelatex#304]
I have been working on an a document (~100 pages) in sharelatex over the past year or so. Out of seemingly nowhere, I am receiving the following error:
Error opening document: Sorry, something went wrong opening this document. Please try again.

The pdf compiles on the right hand side with no critical errors, however I am receiving the "loading" dial in my main document.tex. The last thing I recall editing was something in math mode of the sort $_{1}$, and now the page seems stuck. 

Please let me know if you have advice on recovering this document. I can provide the raw log file if desired. 

Thank you very much,
Steve

**Comment by jpallen** [comment]
Can you send us an email at team@sharelatex.com with the URL of the project please?

**Comment by aukauk** [comment]
I have sent the URL.

Forever in debt,
Steve
