### ISSUE TITLE
Enable downloading generated files such as *.bbl

### ISSUE THREAD

**Issue by staslev** [sharelatex/sharelatex#305]
Some sites require them upon submission (such as [arXiv](https://arxiv.org) for instance), and it's a shame one would have to set up an entire LaTeX environment just to obtain them, when he has your wonderful product already available.

**Comment by henryoswald** [comment]
this should already be possible buy going to the logs dropdown and then the Other logs & files button.

**Comment by staslev** [comment]
Thanks!

Can't believe I missed it!

**Comment by henryoswald** [comment]
np :)

On Thu, May 28, 2015 at 12:50 PM, Stas Levin <notifications@github.com>
wrote:

> Thanks!
>
> Can't believe I missed it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/305#issuecomment-106288413>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder
