### ISSUE TITLE
Sharelatex not showing latest file?

### ISSUE THREAD

**Issue by ilpepe** [sharelatex/sharelatex#309]
Hi,

Sharelatex does not show the latest file :-(.

I wanted to go into the mongo database, to check whether the file is stored in there somewhere.
But I have now idea how to.

Any help?

best regards,
Pieter

**Comment by henryoswald** [comment]
are you using the docker image? If not we recommend using that.

**Comment by ilpepe** [comment]
Hi,
It seemed in consistent. I lost all modification for 1 file somehow. But other projects did not have these kind of issues.

Closed
