### ISSUE TITLE
loading project never finishes on Safari

### ISSUE THREAD

**Issue by kobe2452** [sharelatex/sharelatex#310]
I had difficulty in opening an existing project using Safari. The loading page never finished. 
When I turned to Chrome, open the same project, it works pretty well.

Mac OS: 10.10.3
Safari: Version 8.0.6 (10600.6.3)

![qq20150510-1 2x](https://cloud.githubusercontent.com/assets/1767894/7556618/42fe7d30-f747-11e4-814d-ce1670103995.png)

**Comment by hulk1st** [comment]
Hi, do you run your service on http or https?

**Comment by kobe2452** [comment]
it is on https.

**Comment by hulk1st** [comment]
Ok, that's what I thought. I have a similar problem but no solution yet, unfortunately. Are you trying to forward all http requests to https? If you keep both ports running in parallel it works. Redirection http to https doesn't work for and somehow causes sharelatex not to find the sub-services anymore (it might look at the wrong ports). If someone else got it to work, I would be curious to see the respective nginx sharelatex.conf

**Comment by hulk1st** [comment]
By the way are you using nginx? For me it works if I have it running at both, https and http but as soon as I redirect http to https, I get the same error like you.

**Comment by jpallen** [comment]
Which version of Safari are you using? I believe there may be an issue in older versions where it rejects a secure connect to the websocket. What errors do you get in the javascript console?

**Comment by kobe2452** [comment]
I am using Safari Version 8.0.6 (10600.6.3) -- must be the newest version. And I did not seem to get errors in the console. So that have no idea how to track where the problem might be.

**Comment by henryoswald** [comment]
closing due to age.
