### ISSUE TITLE
io.js support?

### ISSUE THREAD

**Issue by blubbsy** [sharelatex/sharelatex#311]
Hi Sharelatex,

does sharelatex also run with io.js or are there compatiblity problems with io.js? Would be nice as the performance of io.js is most times better than of node.js

Blubbsy

**Comment by henryoswald** [comment]
Hi,

we have not tried it with io.js, it is unlikely we will ever will to be honest, the performance debatable and would only be seen under heavy load which most ShareLaTeX instances will not be under.
