### ISSUE TITLE
Costumize color of last changes 

### ISSUE THREAD

**Issue by blubbsy** [sharelatex/sharelatex#312]
Hi,

is it possible to somehow change the colours of the comments of the users? I have the problem that some users have very similar colours in the background and foreground or the colour combination is awful. 

Here an example for a bad colour combination: 
![unbenannt](https://cloud.githubusercontent.com/assets/8658377/7561497/b062fc86-f7cc-11e4-9b7d-0f5243d2b00b.png)

Blubbsy

**Comment by henryoswald** [comment]
Hey,

you will want to look at the ace editor which is where the colour themes are from, we just take what is set there - https://github.com/ajaxorg/ace
