### ISSUE TITLE
The built-in pdf viewer doesn't show OpenType Font (.otf)

### ISSUE THREAD

**Issue by LUXUV587** [sharelatex/sharelatex#314]
I find that TexLive provides lots of fonts, so that I don't need to upload font file. However, when I apply otf file, the built-in pdf viewer doesn't show these characters, which apply otf. These characters will show up only if I use the native pdf viewer.

**Comment by jpallen** [comment]
Thanks for the bug report. Does the same PDF work if you try it at https://mozilla.github.io/pdf.js/web/viewer.html? This is the PDF viewer that we use.

**Comment by LUXUV587** [comment]
It is a Chinese document. This is the result that I use built-in PDF viewer.
![360 20150518090148514](https://cloud.githubusercontent.com/assets/11599832/7673126/0d9de556-fd3f-11e4-8553-e3d44f21fab1.jpg)

This is the result that I use native PDF viewer.
![360 20150518090327968](https://cloud.githubusercontent.com/assets/11599832/7673129/1f909272-fd3f-11e4-96e0-c7b9a9f1fa1a.jpg)


I know that you use this PDF viewer, but it works. That's why I report my problem.
![360 20150518091031171](https://cloud.githubusercontent.com/assets/11599832/7673130/2a5a18a4-fd3f-11e4-864b-13985a1ca7c9.jpg)

**Comment by jpallen** [comment]
Thanks for the update. To help us debug this, it would be really useful if you could put together a small example document which you can share with us which shows the problem when compiled in ShareLaTeX. If you can make it public read only, and put the link here then that would be enough. Thank you!

**Comment by briangough** [comment]
Hi, we found that older versions of qpdf were occasionally producing corrupted PDF output in the tex pipeline on Sharelatex.com. We've now upgraded to qpdf-5.1.2 and embedded OTF fonts should now be working again.

**Comment by LUXUV587** [comment]
Thank you!
