### ISSUE TITLE
Redirect http to https causes sub-services to stop working

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#316]
Hi,

I've tried to enforce https by redirecting http to https. Here is a code snippet of the sharelatex.conf from the nginx conf.d directory. The remaining lines are identical according to the example from the Wiki:

```
server {
    listen 80;
    listen   [::]:80;
    listen 443 default_server ssl;

    server_name    sharelatex.host.org;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/cert.key;

    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }

    set $static_path /var/www/sharelatex/web/public;

...
```

Redirection works and I can log on to the ShareLaTeX system. However, opening a project does not show the editor or the directory tree. Furthermore, a number of settings are gone when clicking on the Menu button in the upper left corner.

In my opinion, it looks like it can not find the sub-services and therefore the issue is not related to nginx. If I uncomment the three lines corresponding for the redirection and allow both, http and https, everything works fine. However, in my opinion https makes little sense if it is optional. People can access a certain project using an encrypted and a non-encrypted connection at the same time. Also, you can not set the secureCookie flag since people accessing http will get an error message in that case.

I also tried to change the location of the services and pointed them to 

```
url: "https://localhost:#{Port}"
```

but without success.

Thanks in advance!

**Comment by jpallen** [comment]
You should have all the local services talk to each other via `http://localhost:PORT` (note the HTTP, not HTTPS). You should only put SSL in front of the public web service. The services all listen on http only, and rely on Nginx to handle SSL, hence internal https urls will not work.

**Comment by hulk1st** [comment]
Hi,

thanks a lot! I know, still I haven't found a way to only enforce https for the public web service while keeping http for the remaining ones. It only works when allowing both, http and https for the public service. I tried the scheme above but I also tried to put a redirect only explicitly for http://$server_name/login to https://$server_name/login but no success so far.

**Comment by jpallen** [comment]
Are all the services running on one box? In that case, have each service listen on localhost (this is the default), and leave the settings file as the default too, so they all talk to each other over localhost. Then use Nginx to forward 443/80 to localhost:3000, which is the web service. Make sure the public URL is configured with https:// in your settings.

If that still fails, can you please copy and paste the error log from the javascript console when loading up the editor?

**Comment by hulk1st** [comment]
Sorry, just for clarification: By public URL you mean the ```siteUrl : https://...``` variable, right? You are not talking about the section

```
        apis:
                web:
                        url: "http://localhost"
```
correct?

**Comment by jpallen** [comment]
Correct

**Comment by hulk1st** [comment]
So what you suggested of course works but in this case https:// is not enforced and I can still reach all pages using either http:// or https://. Sure, sharing projects, adding users and so on will create https:// urls  only, but if I manually type http://sharelatex.example.org, I can still access all pages and I am not automatically redirected to https://sharelatex.example.org

**Comment by psxlover** [comment]
You shouldn't listen on port 80 if you don't want to be able to access sharelatex without https. Or you could create a different rule that listens to port 80 and redirects to https http://serverfault.com/questions/250476/how-to-force-or-redirect-to-ssl-in-nginx

**Comment by hulk1st** [comment]
And that is exactly what I tried but as pointed out by jpallen, the services listen to http only but in case of the latter, every request is redirected to https

**Comment by hulk1st** [comment]
This is just an update what did NOT work so far. The following lines were placed in a seperate server block listening to port 80:

```
rewrite ^/(.*) https://$server_name/$1 permanent;
```
```
rewrite ^(/login.*) https://$server_name$1 permanent;
```
```
 location /login {
 rewrite https://$server_name/login permanent;
}
```
```
return         301 https://$server_name;
```
```
   if ( $request_filename ~ login/ ) {
      rewrite ^ https://$server_name/? permanent;
   }
```
```
    location /login {
        rewrite ^ https://$http_host$request_uri? permanent;
   }
```
```
location / {
   rewrite ^/.* https://$server_name permanent;
}
```
```
location /login {
   rewrite ^/.* https://$server_name/login permanent;
}
```

I also tried a combined port 80 port 443 block as posted in the beginning of the thread.
```
    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }
```
```
    if ($ssl_protocol = "") {
       rewrite ^   https://$server_name$request_uri? permanent;
    }
```

Still no success, unfortunately.

**Comment by henryoswald** [comment]
Going to close to keep the place tidy. Reopen if needed.

**Comment by hulk1st** [comment]
I think I got it finally working by placing the following inside the location / { statement:

```
if ($server_port = 80) {
    rewrite ^/login https://$host$request_uri permanent;
}
```
