### ISSUE TITLE
Autocompletion improvement

### ISSUE THREAD

**Issue by Kristian60** [sharelatex/sharelatex#319]
Is it a possibility to make autocompletion for both \citet and \cref such that Sharelatex automatically recognises all labels for figures, tabels and equations together with all references in the .bib file and make suggestions for these when using the commands?

as lables and Bibtex keys in bigger projects often are long and hard to remember, this would be a great improvement.

**Comment by henryoswald** [comment]
this is on our todo list, hopefully we will get to it this year

**Comment by henryoswald** [comment]
going to close this issue as we have a few duplicates of this around the place.
