### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by marcAC** [sharelatex/sharelatex#326]
Hello everybody,

is there a way to delete an user? Maybe directly in the mongodb?

Thanks for help!

Marc

**Comment by henryoswald** [comment]
Hi you can do it straight in mongodb or the logged in user can delete
themself via the settings page.

sent from my mobile.

**Comment by marcAC** [comment]
Hey,

the user forgot his password and something goes wrong with the reset-email in his case. So he can't delete himself.

How can I delete the user straight in the mongodb? I'm new to the mongodb.

Thank you!

**Comment by henryoswald** [comment]
use sharelatex
db.users.remove({email:their email})

sent from my mobile.

**Comment by marcAC** [comment]
When I try "db.users.remove({jan.nils.mustermann@test-aachen.de})" I get an error.
"SyntaxError: Unexpected token ILLEGAL"

**Comment by henryoswald** [comment]
You want

db.users.remove({email:"jan.nils.mustermann@test-aachen.de"})

Are you at aachen university? We have a lot of people from there, it would
be interesting to know if you are looking to move self hosted.

On Wed, Jun 17, 2015 at 2:12 PM, marcAC <notifications@github.com> wrote:

> When I try "db.users.remove({jan.nils.mustermann@test-aachen.de})" I get
> an error.
> "SyntaxError: Unexpected token ILLEGAL"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/326#issuecomment-112794471>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by marcAC** [comment]
I'm sorry, I wrote

db.users.remove({email:"jan.nils.mustermann@test-aachen.de"}).

Just forgot the "email:" in my post.

Yes, I am.

**Comment by henryoswald** [comment]
Going to close as this should be sorted now, reopen if it is not.

**Comment by bonanza123** [comment]
One more question that only somehow relates to this: How can I list the currently registered users and their email addresses?

**Comment by henryoswald** [comment]
DB.users.find()

sent from my phone.

**Comment by bonanza123** [comment]
Thanks for the fast response, in my case this gives:
```root@sharelatex:~# mongo
MongoDB shell version: 2.6.11
connecting to: test
> db.users.find()
> 
```
I.e. it shows no user at all, despite the administrator account is set up. Or is this normal and shows only non-admin accounts?

**Comment by henryoswald** [comment]
Try

Use sharelatex

sent from my phone.
