### ISSUE TITLE
Changes in Dropbox are not showing in ShareLatex

### ISSUE THREAD

**Issue by marcevrard** [sharelatex/sharelatex#328]
Hi!
I created a project in ShareLatex (SL), which is synced with Dropbox (DP), but when I replaced the main `.tex` file by a newer version in the DP project folder (and sync with DP) no changes appeared in SL.
An article in http://www.sharelatex.com/help/kb/dropbox-2 mentions that sync may take up to 15 minutes, though I waited for more that 12h without any results.

**Comment by henryoswald** [comment]
Hi, if you are still seeing this issue drop us an email.

**Comment by risjain** [comment]
I'm having the same problem starting today. Contact page is also not working. It states: Something went wrong..... ".
