### ISSUE TITLE
Firefox is blocking Mixed Content over SSL

### ISSUE THREAD

**Issue by deB4SH** [sharelatex/sharelatex#339]
Hey,
i tried to run a ssl encrypted proxy pass nginx in front of my sharelatex instance..
Mozilla is blocking socket.io because of mixed content
> https://developer.mozilla.org/de/docs/Sicherheit/MixedContent

Screenshot(http://cdn.b4sh.de/img/sharelatex_ssl_error.png)
Without ssl encryption on my nginx everything works fine.

My nginx config:http://paste.phcn.de/?i=1437233530

Is this a problem on my end or problem caused by firefox?

**Comment by henry4k** [comment]
I can confirm that.  Have the same problem here :(

**Comment by henryoswald** [comment]
Do you get this error on ShareLaTeX.com?


This is roughly what we use on ShareLaTeX.com:
Maybe X-Frame-Options SAMEORIGIN; is what you need?


	ssl on;
	ssl_certificate path;
	ssl_certificate_key otherpath;

	ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers   on;
	
	ssl_ciphers                 EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;

	add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
	server_tokens off;

	add_header X-Frame-Options SAMEORIGIN;

	location / {
		proxy_pass http://localhost;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_read_timeout 360; # Must be longer than 3 mins for timeout compiles
		proxy_send_timeout 360;
	}

**Comment by deB4SH** [comment]
Hey, sorry for the late answer.. was busy the last days :(
with your config i dont get the warning that iam trying to load mixed content but it still says 
"Error: io is not defined" + an popup which says "You need to upgrade your account to use the History feature."

**Comment by henryoswald** [comment]
Sounds like your static content might not be reaching your browser, are you getting some 404's?

**Comment by deB4SH** [comment]
Ok the problem seems to be fixed with release v.0.1.4. (seen that there is a new release)
the problem only occured in v0.1.3.
now everything works fine even with ssl... :+1: 
thanks for the help :)

**Comment by henryoswald** [comment]
great

**Comment by zeigerpuppy** [comment]
I am getting a mixed content warning with the latest sharelatex (docker) due to fonts which are external and served over http.

```
Blocked loading mixed active content “http://noshut.ru/wp-content/plugins/cresta-social-share-counter/font/csscfont.woff?96836143”[Learn More]
5af51e29e18aab007c64b07c
Blocked loading mixed active content “http://noshut.ru/wp-content/themes/yeahthemes-sparkle/fonts/fontawesome-webfont.woff?v=4.1.0”[Learn More]
5af51e29e18aab007c64b07c
Blocked loading mixed active content “http://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2”[Learn More]
5af51e29e18aab007c64b07c
Blocked loading mixed active content “http://fonts.gstatic.com/s/titilliumweb/v6/NaPecZTIAOhVxoMyOr9n_E7fdMPmDQ.woff2”[Learn More]
5af51e29e18aab007c64b07c
Blocked loading mixed active content “http://noshut.ru/wp-content/plugins/crayon-syntax-highlighter/fonts/consolas/consolas-webfont.woff”[Learn More]
```

Where would be the nest place to change these so they are served off my server instead?
