### ISSUE TITLE
How to promote users in the community version

### ISSUE THREAD

**Issue by Rjmoraza** [sharelatex/sharelatex#340]
Hi!
We have a server up and running, but our non-admin users cannot share the same document more than twice, how can I promote them so they can share to all the members of our group?

**Comment by henryoswald** [comment]
Hi,

it is likely the settings file has low threasholds for defaultFeatures you
want collaborators set to -1. You will need to update the users in mongo to
features.collaborators:-1 to have this retrospectively applied. You can
just do that as a large bulk update to everyone.

On Mon, Jul 20, 2015 at 10:19 PM, Rodolfo Mora <notifications@github.com>
wrote:

> Hi!
> We have a server up and running, but our non-admin users cannot share the
> same document more than twice, how can I promote them so they can share to
> all the members of our group?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/340>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by Rjmoraza** [comment]
Thanks for the fast response.
Yes, that did the trick.
In case someone needs the file where the default new users features are defined is
SHARELATEX_HOME/web/config/settings.defaults.coffee

And the command for the retrospective update is
```
mongo
use sharelatex
db.users.update({},{$set "features.collaborators":-1},{multi:true})
```
This will allow all existing users to share with an undefined number of collaborators.
