### ISSUE TITLE
Email not being produced

### ISSUE THREAD

**Issue by jlazerus** [sharelatex/sharelatex#343]
I am unable to make ShareLaTeX output any email at all, even though I have (it seems to me) correctly changed my config file to do so.
We're running ShareLaTeX on RedHat Enterprise Linux 6.5 (RHEL6) and I'm using Postfix as the MTA. I have successfully tested Postfix to send mail from my server to an outside mailbox, so I know that it is not the problem. Everything else in my ShareLaTeX install is working well except for this.
Here is the email section of my config file:
```javascript
        email:
                fromAddress: "latex@domain.gov"
                replyTo: "latex@domain.gov"
                transport: "SMTP"
                parameters:
                        host: "latex.domain.gov"
                        port: "25"
                        path: "/usr/sbin/postfix"
```
I set everything up, go to "Register New Users" on the site, type in the email adress and hit the "Register" button. THe web interface gives the correct message: "We've sent out welcome emails to the registered users..." but email is not produced, from what I can tell. 
What else can I do to get the application to send mails? Thanks for an excellent product!

**Comment by henryoswald** [comment]
The config options are taken by nodemailer so there is something breaking down there https://github.com/andris9/Nodemailer/tree/0.7

best thing todo for a quick test is clone nodemailer and get a working test with your config, then just paste it into ShareLaTeX

parameters doesn't look to be valid for SMTP - https://github.com/andris9/Nodemailer/tree/0.7#setting-up-smtp

**Comment by jlazerus** [comment]
Many thanks for the reply. I did get a clone of nodemailer to send mail. :mailbox: I pasted the appropriate part of that into my /etc/sharelatex/settings.coffee and still the same result. Is it possible that EmailSender.js is not linking my settings file for some reason? Notice this part of logger.log: the defaultFromAddress is not populating, but it is correct in my settings. 
```javascript
[2015-08-05T21:38:39.044Z]  INFO: web-sharelatex/29192 on latex.domain.gov: registering new user (email=jlazerus@domain.gov)
[2015-08-05T21:38:39.046Z]  INFO: web-sharelatex/29192 on latex.domain.gov: mongo request (query_type=query, collection=sharelatex.users, response-time=2)
    query: {
      "email": "jlazerus@domain.gov"
    }
[2015-08-05T21:38:39.047Z]  INFO: web-sharelatex/29192 on latex.domain.gov: user already exists, resending welcome email (email=jlazerus@domain.gov)
[2015-08-05T21:38:39.047Z]  INFO: web-sharelatex/29192 on latex.domain.gov: generating token for password reset (user_id=556dcd9a0bf7e06b63f23ef4)
[2015-08-05T21:38:39.048Z]  INFO: web-sharelatex/29192 on latex.domain.gov: sending email (receiver=jlazerus@domain.gov)
    subject: Activate your ShareLaTeX (Community Edition) Account
[2015-08-05T21:38:39.049Z]  INFO: web-sharelatex/29192 on latex.domain.gov: Would send email if enabled.
    options: {
      "to": "jlazerus@domain.gov",
      "from": "",
      "subject": "Activate your ShareLaTeX (Community Edition) Account",
      "html": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n\t<head>\n\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n\t\t<!-- Facebook sharing information tags -->\n\t\t<meta property=\"og:title\" />\n\t\t\n\t</head>\n\t<body>\n\t\t<p>Congratulations, you've just had an account created for you on ShareLaTeX (Community Edition) with the email address \"jlazerus@domain.gov\".</p>\n\n<p><a href=\"http://localhost:3000/user/password/set?passwordResetToken=8098506dc599a1ce51aaee3ca214ec81dc32f9665560f8bbd2056865fa87b8ca\">Click here to set your password and log in.</a></p>\n\n<p>Once you have reset your password you can <a href=\"http://localhost:3000/login\">log in here</a>.</p>\n\n<p>If you have any questions or problems, please contact <a href=\"mailto:placeholder@example.com\">placeholder@example.com</a>.</p>\n\t</body>\n</html>\n",
      "socketTimeout": 30000
    }
[2015-08-05T21:38:39.049Z]  INFO: web-sharelatex/29192 on latex.domain.gov: Message sent to jlazerus@domain.gov
```

**Comment by henryoswald** [comment]
Can you check you are using the same version of nodemailer as we use in
web. They changed the api at some point and we have not updated.

sent from my mobile.

**Comment by jlazerus** [comment]
package.json in web wants "nodemailer": "0.6.1"
I uninstalled a global version of nodemailer earlier that was at 1.4. 
Also, running "npm ls" in the /var/www/sharelatex/ folder found this: 
```javascript
npm ERR! extraneous: nodemailer-smtp-transport@1.0.3 /var/www/sharelatex/node_modules/nodemailer-smtp-transport
```
so I removed that -- apparently the module for smtp transport is already on board in the nodemailer pre-1.0 versions.
Here is "npm ls" inside /var/www/sharelatex/web/:
├─┬ nodemailer@0.6.1
│ ├── directmail@0.1.8
│ ├── he@0.3.6
│ ├─┬ mailcomposer@0.2.12
│ │ ├─┬ dkim-signer@0.1.2
│ │ │ └── punycode@1.2.4
│ │ ├── follow-redirects@0.0.3
│ │ ├── mime@1.2.11
│ │ └─┬ mimelib@0.2.19
│ │   ├── addressparser@0.3.2
│ │   └─┬ encoding@0.1.11
│ │     └── iconv-lite@0.4.10
│ ├── public-address@0.1.1
│ ├─┬ readable-stream@1.1.13
│ │ ├── core-util-is@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├── isarray@0.0.1
│ │ └── string_decoder@0.10.31
│ └─┬ simplesmtp@0.3.35
│   ├── rai@0.1.12
│   └── xoauth2@0.1.8
So we can say that the version is okay. 
I'm going to restart the system now I've removed some garbage. Hoping for a different result now.
Thanks.

**Comment by jlazerus** [comment]
Following up, I get the same results after taking these actions.

**Comment by jlazerus** [comment]
The actual settings file called by EmailSender.js is not in /etc/sharelatex, but in /var/web/config. I had been altering the global config file and getting no result. When I made my changes to the local config file /var/www/sharelatex/web/config/settings.defaults.coffee, everything worked as expected. I'd be happy to add this to the SMTP config instruction with a pull request, if you like.
Thanks!
