### ISSUE TITLE
Stuck at loading a project in Google Chrome and IE

### ISSUE THREAD

**Issue by Darkin47** [sharelatex/sharelatex#345]
First, it stopped working with Google Chrome. I tried to remove all my navigation log, cookies log and so on, nothing changed. So I switch to IE but now even in IE it stuck at loading...
I hope you'll find a solution as it is such a big issue.

![sharelatex](https://cloud.githubusercontent.com/assets/6085524/8957570/8d814670-35ff-11e5-9005-ede2b43c4d56.png)

If I could help in any ways, please don't hesitate to ask.

**Comment by henryoswald** [comment]
Do you have avast anti virus installed? That may be the cause.

sent from my mobile.

**Comment by Darkin47** [comment]
Yes I got it. I'll try asap with avast turning off. I'll let you know if it works or not. Thx.
On 29 Jul 2015 14:44, Henry Oswald <notifications@github.com> wrote:Do you have avast anti virus installed? That may be the cause.

sent from my mobile.

**Comment by Darkin47** [comment]
Re. I can confirm you that avast was the cause. Is there any solution to avoid this problem with Avast? Or should I always temporary disabled avast?

**Comment by henryoswald** [comment]
Hi,

Avast say they are working on a fix, if you report it to them as well it
should speed things up. There is no other way around at the moment.

Regards

Henry Oswald <http://www.twitter.com/henryoswald>

ShareLaTeX co-founder

On Thu, Jul 30, 2015 at 10:44 AM, Julien Grave <notifications@github.com>
wrote:

> Re. I can confirm you that avast was the cause. Is there any solution to
> avoid this problem with Avast? Or should I always temporary disabled avast?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/345#issuecomment-126248589>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by PedroSoldado** [comment]
This problem still remains?

I can't load my projects unless I disable Avast shields...

**Comment by henryoswald** [comment]
avast say they are pushing a fix soon.

On Wed, Aug 12, 2015 at 10:04 PM, PedroSoldado <notifications@github.com>
wrote:

> This problem still remains?
>
> I can't load my projects unless I disable Avast shields...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/345#issuecomment-130448689>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by erickmartinez** [comment]
I added an exclusion to https://www.sharelatex.com and fixed the problem

**Comment by muelli** [comment]
I also have this issue in both Firefox and Epiphany.
The sharelatex installation is behind a proxy.
Has the root issue of this bug been identified yet?

**Comment by muelli** [comment]
Seems it's about web sockets. https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy says that nginx needs to be at least 1.4.

When accessing the port 3000 directly, it works.

**Comment by henryoswald** [comment]
Avast have updated their code which fixes this problem now so closing.
