### ISSUE TITLE
Hint to prevent a possible security issue in sharelatex! 

### ISSUE THREAD

**Issue by Joehein** [sharelatex/sharelatex#346]
Sharelatex uses latexmk to compile the source code. By default latexmk reads in some initialization files, a global .latexmkrc, a user .latexmkrc, and a .latexmkrc in the current working directory. These files are interpreted by a Perl interpreter, so they may contain arbitrary Perl code. By defining a .latexmkrc file in the project's root directory (that is actually the working directory at compilation time!) you can execute this and therefore any code you want on the server every time a compilation step is done. While this is nice to control the latexmk processing step freely and differently for any project, it is as dangerous the same way as unlimited latex's \write18{} support. 
This can be prevented by stopping the invocation chain of the latexmk initialization files at any step by i) the -norc option at the command line (it can go to .../clsi/app/coffee/LatexRunner.coffee...compilation and restart of clsi), or ii) by setting $auto_rc_use = 0; in one of the .latexmkrc files (globally for the server or in the sharelatex user home directory). One should consult the docs where the files are searched OS dependent. 
A simple test case is creating a .latexmkrc in some project's root directory with some "dangerous" code like: exit 1; (this is not as dangerous as other examples I could provide as well :-) since it only stops the compilation, but not doing any nasty thing). If compilation fails, thank's to Perl, every user of the sharelatex system has full power over the sharelatex-user@sharelatex-server!

**Comment by har-wradim** [comment]
Have you seen [this post](https://github.com/sharelatex/sharelatex/issues/321)?

**Comment by henryoswald** [comment]
Thanks for the post, https://github.com/sharelatex/sharelatex/issues/321 as pointed out by @har-wradim is the same thing though.
