### ISSUE TITLE
Rich Text Mode 

### ISSUE THREAD

**Issue by koppor** [sharelatex/sharelatex#349]
For LaTeX newcomers and team members not so fluent in LaTeX commands, there should be a Rich Text Mode. Possibly similar to the one of [overleaf](https://www.overleaf.com/benefits).

**Comment by henryoswald** [comment]
Thanks, I'm actually going to close this issue to keep the place tidy. Although rich text would be great it is a massive undertaking which we don't plan on taking ShareLaTeX down.
