### ISSUE TITLE
some hints for the installation instructions

### ISSUE THREAD

**Issue by tobiasschweizer** [sharelatex/sharelatex#352]
I followed your advice abd installed the docker image. Works fine!

For Ubuntu, I have some hints regarding mongodb and redis. Maybe this is helpful.

* First, install `docker`: <http://docs.docker.com/linux/step_one/>
* Install the docker image for `sharelatex` by following the instructions given here: <https://github.com/sharelatex/sharelatex-docker-image>
* Additionally, check the following things:
   * Make sure that `mongodb` and `redis-server` are installed on your system (otherwise install them with `sudo apt-get install mongodb redis-server redis-tools`)
   * On Ubuntu, try to run `sudo mongod`. If it fails and says that `/data/db/` does not exist, create the dir and assign it to your user: 
```sudo mkdir -p /data/db/; sudo chown `id -u` /data/db```
   * Make sure `sudo mongod` runs properly and that there is only one instance running
   * change the default IPs of `mongodb` and `redis` to listen on (https://github.com/sharelatex/sharelatex-docker-image#mongo-and-redis)
   * Kill all `mongodb` processes and restart the service: `sudo /etc/init.d/mongodb start`
   * Stop and restart `redis-server`: `sudo /etc/init.d/redis-server restart`
* Do not forget to add an admin user: https://github.com/sharelatex/sharelatex-docker-image#creating-and-managing-users
* if you get the link to set the password, please add the port number 5000 after localhost

**Comment by henryoswald** [comment]
Thanks, going to close as its not an issue but google will still find it.
