### ISSUE TITLE
Missing Changelog/Release Notes for 0.2.0

### ISSUE THREAD

**Issue by moschlar** [sharelatex/sharelatex#356]
Hi there,

since there was a new tag 0.2.0 three weeks ago, I was trying to find out what had changed since 0.1.4 but couldn't find something in the Changelog or the Release Notes in the wiki.
Was I bad at searching or do those not exist?

Cheers,
Moritz

**Comment by blubbsy** [comment]
yeah i was also wondering. Some information would be nice.

**Comment by henryoswald** [comment]
Hey, 0.2.0 is still in pre release officially, once we have a few people have finished testing it out we will let you know more about it. This version requires some db migrations so don't upgrade until its officially out. The main new feature is wordcount, then a lot of internal refactoring & hidden improvements.

**Comment by moschlar** [comment]
Hey there,

is there any news on this front?

Regards,
Moritz

**Comment by henryoswald** [comment]
I will hopefully have it out within the next week or two

**Comment by ilpepe** [comment]
This on one is ready for production?
