### ISSUE TITLE
Can't access text files after restore

### ISSUE THREAD

**Issue by skruse** [sharelatex/sharelatex#362]
I tried to migrate data from backups to a new server. Including redis/mongo data and data_dir folder. (Mongo backup/restore with mongodump and mongorestore), Login is ok, projects are listed and I can access binary files. But I can't access any text file, it fails with:

"Sorry, something went wrong opening this document. Please try again."

In the logs: 
Exception: TypeError: Cannot call method 'join' of undefined
  at /var/www/sharelatex/web/app/js/Features/Compile/ClsiManager.js:158:36

which seems to be this line: https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Compile/ClsiManager.coffee#L82

I checked the mongo data and it looks intact. Any idea? Thanks!

**Comment by henryoswald** [comment]
Are you running the docker container?

On Tuesday, 20 October 2015, skruse <notifications@github.com> wrote:

> I tried to migrate data from backups to a new server. Including
> redis/mongo data and data_dir folder. (Mongo backup/restore with mongodump
> and mongorestore), Login is ok, projects are listed and I can access binary
> files. But I can't access any text file, it fails with:
>
> "Sorry, something went wrong opening this document. Please try again."
>
> In the logs:
> Exception: TypeError: Cannot call method 'join' of undefined
> at /var/www/sharelatex/web/app/js/Features/Compile/ClsiManager.js:158:36
>
> which seems to be this line:
> https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Compile/ClsiManager.coffee#L82
>
> I checked the mongo data and it looks intact. Any idea? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/362>.
>


-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by skruse** [comment]
Yes, i went from a "custom" install to a docker container.

**Comment by henryoswald** [comment]
It is likely you have different versions of some services running then. You
can either go back to a custom install or wait for the new container to be
released soon.

On Tuesday, 20 October 2015, skruse <notifications@github.com> wrote:

> Yes, i went from a "custom" install to a docker container.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/362#issuecomment-149586822>
> .
>


-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by skruse** [comment]
Thanks. Wouldn't have thought. Just tried to restore from a "very old" install, which worked.

**Comment by henryoswald** [comment]
If you drop me your email I might be able to get you a pre release of the
new docker container.

On Tuesday, 20 October 2015, skruse <notifications@github.com> wrote:

> Thanks. Wouldn't have thought. Just tried to restore from a "very old"
> install, which worked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/362#issuecomment-149591968>
> .
>


-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by skruse** [comment]
Thanks a lot! sebastian.kruse at hu-berlin.de
