### ISSUE TITLE
Apache as Reverse Proxy: websocket connection invalid

### ISSUE THREAD

**Issue by moschlar** [sharelatex/sharelatex#363]
I'm running ShareLaTeX behind an Apache 2.4 Reverse Proxy, but the WebSocket connection just doesn't work, the editor always falls back to xhr-polling.

Now I know that the ShareLaTeX developers themselves don't use Apache, but maybe they can shed some light on the issue since at least the warning "websocket connection invalid" comes from the ShareLaTeX app. :wink: 

### Apache Config:
```
                ProxyPreserveHost On

                ProxyPass /socket.io/ http://localhost:3026/socket.io/
                ProxyPassReverse /socket.io/ http://localhost:3026/socket.io/

                ProxyPass /socket.io/1/websocket/ ws://localhost:3026/socket.io/1/websocket/
                ProxyPassReverse /socket.io/1/websocket/ ws://localhost:3026/socket.io/1/websocket/

                ProxyPass / http://localhost:3000/
                ProxyPassReverse / http://localhost:3000/

                Alias "/stylesheets" "/var/www/sharelatex/web/public/stylesheets"
                Alias "/minjs" "/var/www/sharelatex/web/public/minjs"
                Alias "/img" "/var/www/sharelatex/web/public/img"
```
### Browser Console:
```
GET https://<domain>/socket.io/1/websocket/LU8bFWaXkb8nGjBfK-1h [HTTP/1.1 502 Proxy Error 62ms]
16:12:46.892 Firefox can't establish a connection to the server at wss://<somain>/socket.io/1/websocket/LU8bFWaXkb8nGjBfK-1h.1 socket.io.js:2:0
```
### Apache Log:
```
==> /var/log/apache2/error.log <==
[Fri Oct 30 16:12:46.817814 2015] [proxy_http:error] [pid 32271:tid 140010850260736] (20014)Internal error: [client 2001:4c80:40:4b3:226:b9ff:fe7c:59c7:37441] AH01102: error reading status line from remote server localhost:3026
[Fri Oct 30 16:12:46.817929 2015] [proxy:error] [pid 32271:tid 140010850260736] [client 2001:4c80:40:4b3:226:b9ff:fe7c:59c7:37441] AH00898: Error reading from remote server returned by /socket.io/1/websocket/LU8bFWaXkb8nGjBfK-1h

==> /var/log/apache2/access.log <==
2001:4c80:40:4b3:226:b9ff:fe7c:59c7 - - [30/Oct/2015:16:12:46 +0100] "GET /socket.io/1/websocket/LU8bFWaXkb8nGjBfK-1h HTTP/1.1" 502 974 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
2001:4c80:40:4b3:226:b9ff:fe7c:59c7 - - [30/Oct/2015:16:12:56 +0100] "GET /socket.io/1/xhr-polling/LU8bFWaXkb8nGjBfK-1h?t=1446217976675 HTTP/1.1" 200 402 "https://<domain>/project/55f34229e5ae2a4a714c9c14" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
```
### ShareLaTeX Realtime Log:
```
Oct 30 16:12:46 sharelatex-01 nodejs[620]: warn: websocket connection invalid
```

**Comment by henryoswald** [comment]
Hey,

you are best looking at this issue. https://github.com/sharelatex/sharelatex/issues/83

**Comment by moschlar** [comment]
I've read that thread, but I don't think it's the same issue at all.
Basically, my setup works, and it can be used, except for the fallback to XHR polling because the WebSocket connection can't be established.
There must be a subtle difference between the ways Apache and nginx proxy WebSocket connections.

**Comment by henryoswald** [comment]
We really don't know Apache sorry. I would look at generic apache websocket guides. I know they added websocket support only recently. If you find a good solution please pop your config in this thread.

**Comment by jowagner** [comment]
I think this may have something to do with the "upgrade" header manipulations in package/nginx/sharelatex.conf as code around "connection invalid" tests for these headers. I didn't spend much time trying to replicate this with apache httpd. Instead, I simply run nginx on *:3080 and reverseproxy to it in apache httpd as usual.

**Comment by sxu55** [comment]
I found a solution here:
https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel
Generally in the apache virtualhost setting, I add the following (given that the sharelatex is running on port 5000)

>  RewriteEngine On
>   RewriteCond %{HTTP:Upgrade} =websocket [NC]
>   RewriteRule /(.*)           ws://localhost:5000/$1 [P,L]
>   RewriteCond %{HTTP:Upgrade} !=websocket [NC]
>   RewriteRule /(.*)           http://localhost:5000/$1 [P,L]
> 
>   ProxyPassReverse / http://localhost:5000/

The websocket 502 error is resolved

**Comment by florealcab** [comment]
Not working for me : ERR_TOO_MANY_REDIRECTS

**Comment by florealcab** [comment]
For me, in ubuntu 20.04 I just found a solution:

```
ProxyRequests on
RequestHeader set X-Forwarded-Proto "http"
ProxyPass / http://localhost:3001/
ProxyPassReverse / http://localhost:3001/

RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://localhost:3001%{REQUEST_URI} [P]
```

(with sharelatex running on 3001 port)
