### ISSUE TITLE
nginx intermittent failures if IPv6 not enabled on the machine

### ISSUE THREAD

**Issue by Micket** [sharelatex/sharelatex#367]
Setting up a RHEL7.1 server using docker image to run sharelatex, I experienced intermittent failures of the nginx server (internal server error 500).

Seems this was due to IPv6 not being enabled on the machine. It was solvable through switching out "localhost" to IPv4 address "127.0.0.1" inside the docker image nginx conf.
Otherwise it was resolved to [::1] which was not understood by nginx (socket() failed (address family not supported by protocol)).

I don't know enough to tell for sure, but perhaps it's better to just use this IPv4 address from the start?

**Comment by henryoswald** [comment]
This seems to be a config choice you make when setting up?

**Comment by Micket** [comment]
I realize now this was the wrong project to report the issue to, I should have submitted it to sharelatex-docker-image.
Sorry for the noise.
