### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by darklunar** [sharelatex/sharelatex#368]
Hello!
I setup ShareLaTeX and currently having in issue in compiling. Whenever I create a new project it starts off by saying: "Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments."
I made sure redis-server and mongo are running. 

I looked at the sharelatex logs for clsi.log and noticed this issue:
{"name":"clsi","hostname":"machinetest.test.com","pid":2284,"level":50,"err":{"message":"SQLITE_CANTOPEN: unable to open database file","name":"SequelizeConnectionError","stack":"SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file\n    at Database.<anonymous> (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:38:59)","parent":{"errno":14,"code":"SQLITE_CANTOPEN"},"original":"[Circular]"},"msg":"server error","time":"2015-11-10T21:17:33.625Z","v":0}

I'm not sure where to look for on this one.

**Comment by henryoswald** [comment]
There is something wrong with it talking to the sqlite database, try the docker image as that is the easiest way to get setup rather than doing it this way.
