### ISSUE TITLE
Webserver connection refused, no errors.

### ISSUE THREAD

**Issue by chriskvik** [sharelatex/sharelatex#373]
Hi, I'm unsure if this is a bug or a configuration problem. To be honest I have no idea what's wrong.

*  NodeJS v0.10.37 global install in path : /usr/bin/nodejs (both node and nodejs) 
*  npm is version 1.4.28 also added to path.
*  libkrb5-dev, qpdf, texlive, and grunt installed with no errors.
* MongoDB v2.6.11
* Redis server v=3.0.5

MongoDB / Redis working and accessible. No erros in the logs. 
npm install / grunt install in /var/sharelatex produced no erros. 

I'm using the provided upstart scripts and added the share-latex user according to the production-setup guide. The services are starting, and running on reboot.

Logs are created, without errors.

**Web.log shows**
```
$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"Generating file fingerprints...","time":"2015-11-27T13:51:16.172Z","v":0}
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/require.js: 0cb51c1a5e8e978cbe069c07f3b8d16d",$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/ide.js: 7283038af2506e78236ce9c5fb43eadc","time":"2$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/main.js: d5affae000b48cfeab835d66d42d32b3","time":"$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs.js: 1e6cd62b1845edbe84857a25f009bfcb","time":"$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/ace/ace.js: 1449b6cdb7a9bc543c1b0e571e5ad2d1","time$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/pdfjs-1.0.1040/pdf.js: a3a59941d92a979430bd602$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/pdfjs-1.0.1040/pdf.worker.js: d087c7de7657499f$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/pdfjs-1.0.1040/compatibility.js: 3f15343591bd9$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/stylesheets/style.css: af309e1dc7d2c65e3e74060ba0d00c8$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"tpdsworker is not enabled, request will not be sent to it","time":"2015-11-27T13:51:1$
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"Production Enviroment","time":"2015-11-27T13:51:18.040Z","v":0}
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"","time":"2015-11-27T13:51:18.128Z","v":0}
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"web starting up, listening on localhost:3000","time":"2015-11-27T13:51:18.150Z","v":0}
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"300 sockets enabled","time":"2015-11-27T13:51:18.150Z","v":0}
{"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"url":"mongodb://127.0.0.1/sharelatex","msg":"mongoose default connection open","time":"2015$
```
All other log files (for all the other services show the same, no errors).

The web-server binds to port :3000 on localhost, but the page is not accessible from remote machine on the same network. No firewall / routing issues, quadruple checked. 

The node process are running fine.

I'm lost without any error output to debug on. As stated I do not know if this is an appropriate place to ask for help. But due to the lack of "error-messages" I guess it could be classified as  a bug / enhancement? 

This is my second try, with a fresh Ubuntu 14.04 Server.

**Comment by henryoswald** [comment]
I would try using the docker image, that is a much easier setup.

On Fri, Nov 27, 2015 at 2:08 PM, chriskvik <notifications@github.com> wrote:

> Hi, I'm unsure if this is a bug or a configuration problem. To be honest I
> have no idea what's wrong.
>
>    - NodeJS v0.10.37 global install in path : /usr/bin/nodejs (both node
>    and nodejs)
>    - npm is version 1.4.28 also added to path.
>    - libkrb5-dev, qpdf, texlive, and grunt installed with no errors.
>    - MongoDB v2.6.11
>    - Redis server v=3.0.5
>
> MongoDB / Redis working and accessible. No erros in the logs.
> npm install / grunt install in /var/sharelatex produced no erros.
>
> I'm using the provided upstart scripts and added the share-latex user
> according to the production-setup guide. The services are starting, and
> running on reboot.
>
> Logs are created, without errors.
>
> *Web.log shows*
>
> $
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"Generating file fingerprints...","time":"2015-11-27T13:51:16.172Z","v":0}
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/require.js: 0cb51c1a5e8e978cbe069c07f3b8d16d",$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/ide.js: 7283038af2506e78236ce9c5fb43eadc","time":"2$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/main.js: d5affae000b48cfeab835d66d42d32b3","time":"$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs.js: 1e6cd62b1845edbe84857a25f009bfcb","time":"$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/ace/ace.js: 1449b6cdb7a9bc543c1b0e571e5ad2d1","time$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/pdfjs-1.0.1040/pdf.js: a3a59941d92a979430bd602$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/pdfjs-1.0.1040/pdf.worker.js: d087c7de7657499f$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/js/libs/pdfjs-1.0.1040/compatibility.js: 3f15343591bd9$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"/var/www/sharelatex/web/public/stylesheets/style.css: af309e1dc7d2c65e3e74060ba0d00c8$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"tpdsworker is not enabled, request will not be sent to it","time":"2015-11-27T13:51:1$
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"Production Enviroment","time":"2015-11-27T13:51:18.040Z","v":0}
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"","time":"2015-11-27T13:51:18.128Z","v":0}
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"web starting up, listening on localhost:3000","time":"2015-11-27T13:51:18.150Z","v":0}
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"msg":"300 sockets enabled","time":"2015-11-27T13:51:18.150Z","v":0}
> {"name":"web-sharelatex","hostname":"web","pid":4561,"level":30,"url":"mongodb://127.0.0.1/sharelatex","msg":"mongoose default connection open","time":"2015$
>
> All other log files (for all the other services show the same, no errors).
>
> The web-server binds to port :3000 on localhost, but the page is not
> accessible from remote machine on the same network. No firewall / routing
> issues, quadruple checked.
>
> The node process are running fine.
>
> I'm lost without any error output to debug on. As stated I do not know if
> this is an appropriate place to ask for help. But due to the lack of
> "error-messages" I guess it could be classified as a bug / enhancement?
>
> This is my second try, with a fresh Ubuntu 14.04 Server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/373>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by chriskvik** [comment]
Sure, I did. Ant it works as it should. I just got carried away making it work this way. The host itself is already a ESXi VM, thus making it a docker host seems a bit.. yeah, and since I have used (way to many hours) I wanted to make it trough! :+1:
