### ISSUE TITLE
github downloads should be handled by npm, not grunt, to make BSD package possible

### ISSUE THREAD

**Issue by yurivict** [sharelatex/sharelatex#374]
I am trying to make the FreeBSD package for sharelatex. It is required (contrary to what LInux does) that the package is fetched and built separately, and no fetch is allowed in the build phase.

Why don't you add all required github projects to package.json, and they can be downloaded by 'npm install --ignore-scripts' in a standard way?

You are re-writing code to fetch git repository in Gruntfile.coffee, that is already in npm -)

Currently you make 'npm install' run first, then you run grunt that downloads more and performs build and check steps. This grunt stage has fetch and build mixed.

**Comment by henryoswald** [comment]
Hi, we had several problems with using npm install which is why we had to use grunt, reluctantly. We recommend using docker to get setup generally which might work for you.
