### ISSUE TITLE
Feynman diagram intermittently fails to render.

### ISSUE THREAD

**Issue by yurivict** [sharelatex/sharelatex#377]
This document intermittently fails to show the figure (Feynman diagram). It first shows it, but next "Recompile" produces an error:
Font \f@ynmf: dipl1=dipl1 not loadable: Metric (TFM) file not shown.
Later when documents are switched back and force it succeeds again.

As I understand, latex creates some extra files dipl1.* for this document. Not sure what causes sharelatex to not be deterministic.

```
\documentclass{article}
\usepackage{feynmf}
\begin{document}

\begin{figure}[h]
\begin{fmffile}{dipl1}
\begin{fmfgraph*}(140,100)
  \fmftop{p}
  \fmfbottom{f1,f2}
  \fmf{fermion}{f1,v,f2}
  \fmfblob{.22w}{v}
  \fmf{photon}{v,p}
\end{fmfgraph*}
\end{fmffile}
\label{fig_amm}
\end{figure}

\end{document}
```

**Comment by henryoswald** [comment]
Sorry this is going to be a latex or latex install issue not related to ShareLaTeX so will close.
