### ISSUE TITLE
Latexmk:  Bad options specified

### ISSUE THREAD

**Issue by aaronst** [sharelatex/sharelatex#378]
I'm having a hard time trying to figure this error out that's stopping sharelatex from compiling documents.  Here's the relevant portion of the clsi.log file:

```
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","msg":"starting compile","time":"2015-12-07T20:14:55.792Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","msg":"getting output files","time":"2015-12-07T20:14:55.792Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"args":["/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2015-12-07T20:14:55.792Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"url":"http://localhost:3009/project/5664b0da973da19103a43044/file/5664b0da973da19103a43047","lastModified":"2015-12-06T22:04:10.000Z","msg":"URL is up to date in cache","time":"2015-12-07T20:14:55.807Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","time_taken":19,"msg":"written files to disk","time":"2015-12-07T20:14:55.811Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","compiler":"pdflatex","timeout":60000,"mainFile":"main.tex","msg":"starting compile","time":"2015-12-07T20:14:55.812Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","command":["latexmk","-cd","-f","-jobname=output","-auxdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-outdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-pdf","-e","$pdflatex='pdflatex -synctex=1 -interaction=batchmode %O %S'","/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/main.tex"],"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","msg":"running command","time":"2015-12-07T20:14:55.812Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2015-12-07T20:14:55.813Z","v":0}
Latexmk: -auxdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044 bad option
Latexmk: -outdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044 bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","time_taken":57,"msg":"done compile","time":"2015-12-07T20:14:55.868Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","msg":"getting output files","time":"2015-12-07T20:14:55.868Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"args":["/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2015-12-07T20:14:55.868Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"req":{"url":"/project/5664b0da973da19103a43044/compile","method":"POST","remote-addr":"127.0.0.1","content-length":"1414"},"res":{"statusCode":200},"response-time":137,"msg":"http request","time":"2015-12-07T20:14:55.881Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"cache":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/.cache/clsi","dir":"1517dea36c9","msg":"removed expired cache dir","time":"2015-12-07T20:14:55.882Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":40,"err":{"message":"ENOENT, lstat '/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log'","name":"Error","stack":"Error: ENOENT, lstat '/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log'","errno":34,"code":"ENOENT","path":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log"},"requestedFsPath":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log","path":"output.log","project_id":"5664b0da973da19103a43044","msg":"error checking file access","time":"2015-12-07T20:14:55.917Z","v":0}
{"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"req":{"url":"/project/5664b0da973da19103a43044/output/output.log","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":404},"response-time":3,"msg":"http request","time":"2015-12-07T20:14:55.918Z","v":0}
```

**Comment by henryoswald** [comment]
I would check the readme for the latexmk version

On Mon, Dec 7, 2015 at 8:25 PM, Aaron Stephens <notifications@github.com>
wrote:

> I'm having a hard time trying to figure this error out that's stopping
> sharelatex from compiling documents. Here's the relevant portion of the
> clsi.log file:
>
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","msg":"starting compile","time":"2015-12-07T20:14:55.792Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","msg":"getting output files","time":"2015-12-07T20:14:55.792Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"args":["/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2015-12-07T20:14:55.792Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"url":"http://localhost:3009/project/5664b0da973da19103a43044/file/5664b0da973da19103a43047","lastModified":"2015-12-06T22:04:10.000Z","msg":"URL is up to date in cache","time":"2015-12-07T20:14:55.807Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","time_taken":19,"msg":"written files to disk","time":"2015-12-07T20:14:55.811Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","compiler":"pdflatex","timeout":60000,"mainFile":"main.tex","msg":"starting compile","time":"2015-12-07T20:14:55.812Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","command":["latexmk","-cd","-f","-jobname=output","-auxdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-outdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-pdf","-e","$pdflatex='pdflatex -synctex=1 -interaction=batchmode %O %S'","/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/main.tex"],"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","msg":"running command","time":"2015-12-07T20:14:55.812Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2015-12-07T20:14:55.813Z","v":0}
> Latexmk: -auxdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044 bad option
> Latexmk: -outdir=/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044 bad option
>
> Latexmk: Bad options specified
> Use
>    latexmk -help
> to get usage information
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"project_id":"5664b0da973da19103a43044","time_taken":57,"msg":"done compile","time":"2015-12-07T20:14:55.868Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"directory":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","msg":"getting output files","time":"2015-12-07T20:14:55.868Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"args":["/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2015-12-07T20:14:55.868Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"req":{"url":"/project/5664b0da973da19103a43044/compile","method":"POST","remote-addr":"127.0.0.1","content-length":"1414"},"res":{"statusCode":200},"response-time":137,"msg":"http request","time":"2015-12-07T20:14:55.881Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"cache":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/.cache/clsi","dir":"1517dea36c9","msg":"removed expired cache dir","time":"2015-12-07T20:14:55.882Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":40,"err":{"message":"ENOENT, lstat '/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log'","name":"Error","stack":"Error: ENOENT, lstat '/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log'","errno":34,"code":"ENOENT","path":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log"},"requestedFsPath":"/var/lib/sharelatex/data/compiles/5664b0da973da19103a43044/output.log","path":"output.log","project_id":"5664b0da973da19103a43044","msg":"error checking file access","time":"2015-12-07T20:14:55.917Z","v":0}
> {"name":"clsi","hostname":"ip-10-10-102-133","pid":4148,"level":30,"req":{"url":"/project/5664b0da973da19103a43044/output/output.log","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":404},"response-time":3,"msg":"http request","time":"2015-12-07T20:14:55.918Z","v":0}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/378>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by aaronst** [comment]
Nevermind, I think I had also installed texlive from the repos, and so there was a dual installation bug going on.  The following fixed the issue for me:

```
$ sudo apt-get remove texlive*
```
