### ISSUE TITLE
Project list doesn't appear until after window resize

### ISSUE THREAD

**Issue by nicobrinkkemper** [sharelatex/sharelatex#381]
![image](https://cloud.githubusercontent.com/assets/1597349/11932042/949a9f78-a7f2-11e5-9c06-2650f6c877d0.png)

When I resized my window the project list appeared. This bug gave me a heart attack :) I died

**Comment by henryoswald** [comment]
Does it happen every time?

On Mon, Dec 21, 2015 at 1:55 PM, Nico Brinkkemper <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1597349/11932042/949a9f78-a7f2-11e5-9c06-2650f6c877d0.png>
>
> When I resized my window, my project list appeared. This bug gave me a
> heart attack :) I died
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/381>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by nicobrinkkemper** [comment]
Sorry, I did a cross browser check and found out it only happens in Chrome Canary. I suppose it's still a bug, but not a big one. Phew

**Comment by henryoswald** [comment]
cool, let me know if you see it in other browsers.

On Mon, Dec 21, 2015 at 2:05 PM, Nico Brinkkemper <notifications@github.com>
wrote:

> Sorry, I did a cross browser check and found out it only happens in Chrome
> Canary. I suppose it's still a bug, but not a big one. Phew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/381#issuecomment-166312096>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by nicobrinkkemper** [comment]
Will do

**Comment by henryoswald** [comment]
great

**Comment by edwinksl** [comment]
I can confirm this is a problem on Google Chrome on the dev channel (specifically Version 49.0.2612.0 dev (64-bit)) on Ubuntu 15.10.
