### ISSUE TITLE
new mongodb structure

### ISSUE THREAD

**Issue by Joehein** [sharelatex/sharelatex#382]
I have tried a rebuild of sharelatex (new download) with node.js 5.4.0 what seems to work after manual installation of bcrypt and sqlite3 to their latest versions. Additionally, I applied what was mentioned in https://github.com/sharelatex/web-sharelatex/issues/216 as a workaround and to avoid a bson c++ extension missing warning I have copied all bson.js files I have found from browser_build to build/Release. 
I can generate new projects and compile them as usual.
But deploying the newly compiled version to an already existing server previously running with node 0.10.31 I get a document not found error. (previous installation was also sharelatex 0.1.4, dated July 12, 2015). 
Looking to the mongo database a different document structure is to be seen. In the previous installation all documents living as subdocuments directly inside the projects collection. In the newer version they are referenced to documents in the docs collection. (what in principle would allow a document to be part of several projects, something I would like to see manageable with the software...) That's why they are not found with the new sharelatex version using the old database, whereas newly created projects work. 

Question is now: In order to migrate all old projects to work with the new sharelatex I need to know what exactly has changed, so one can probably write a tool to do the necessary changes in the database (if not existing yet?!). Is there any idea how this could be accomplished maybe with the mongo console?
Would it be enough to move the ObjectID, lines, rev into a document in the docs collection or are there more changes required that I haven't seen so far? This could probably best answered by the developers of the docstore.

Thank you!

**Comment by henryoswald** [comment]
Hi,

I have created a wiki page detailing the process. https://github.com/sharelatex/sharelatex/wiki/Database-migrations hopefully that answers all your questions.
