### ISSUE TITLE
Enabling Email Settings Result in 502 Bad Gateway Errors

### ISSUE THREAD

**Issue by bonanza123** [sharelatex/sharelatex#384]
Hi,
I do have a working sharelatex installation on Ubuntu 14.04 (not from the docker image). However, when I either copy and paste the email settings from https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email or comment out the default settings in /etc/sharelatex/settings.coffee I get "502 Bad Gateway" errors when browsing the website. Disabling / commenting out the settings again yield again a working sharelatex website. 

What could be the root of the problem? A syntax error?
Thanks for your help in advance!

**Comment by gawlowiczp** [comment]
Hi, 
I had the same problem. Check if the indentations are uniform over the entire config file. 
-Piotr

**Comment by bonanza123** [comment]
Thanks a lot! That is really the last thing I thought of.
