### ISSUE TITLE
Preview looks wrong, but PDF is OK

### ISSUE THREAD

**Issue by NYKevin** [sharelatex/sharelatex#387]
Here's a minimal example:

    \documentclass{article}
    \usepackage[utf8]{inputenc}
    \usepackage{amsmath}
    \usepackage{mathtools}
    
    \begin{document}
    
    \begin{align*}
    2^{k}-1 &\ne \sum_{i=0}^{k-2} \big{(}2^i\big{)} + 2^{k-1} \\
    2^{k}-2 &\ne \sum_{i=0}^{k-2} \big{(}2^i\big{)} + 2^{k-1} - 1 \\
    2\big{(}2^{k-1}-1\big{)} &\ne \sum_{i=0}^{k-2} \big{(}2^i\big{)} + 2^{k-1} - 1 \\
    2\big{(}2^{k-1}-1\big{)} &\ne \sum_{i=1}^{k-2} \big{(}2^i\big{)} + 2^{k-1} \\
    2^{k-1}-1 &\ne \sum_{i=1}^{k-2} \big{(}2^{i-1}\big{)} + 2^{k-2} \\
    2^{k-1}-1 &\ne \sum_{j=0}^{k-3} \big{(}2^{j}\big{)} + 2^{k-2} \\
    2^{k-1}-1 &\ne \sum_{j=0}^{k-2} \big{(}2^{j}\big{)}
    \end{align*}
    
    \begin{align*}
    2^k &= 1\!\underbrace{00\ldots00_{\mathrlap{2}}}_{k \text{ zeros}} \\
    2^k - 1 &= \underbrace{11\ldots11_{\mathrlap{2}}}_{k \text{ ones}} 
    \end{align*}
    
    \end{document}

As you can see in this image, the limits under the sums are running into the sigmas:

![bad sum limits](https://cloud.githubusercontent.com/assets/1929766/12704811/0bc6afe8-c818-11e5-9e72-20bdd0e5b782.png)

I don't see this behavior in the downloaded PDF:

![good sum limits](https://cloud.githubusercontent.com/assets/1929766/12704826/5706af26-c818-11e5-9799-60972888a779.png)

It looks as if we're using a totally different set of fonts in the preview than in the final document.  Is this a problem with WOFF links, or something else?

Since this may be a browser issue, here's my User-Agent:

    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by bajo** [comment]
I tested this on my fresh sharelatex docker installation with full texlive 2014 installed. The issue shows up for me as well. My User-Agent is:
```Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36```

**Comment by henryoswald** [comment]
Hi,

this will be todo with the pdf viewer. Its in a permanent state of "trying to render pdf's correctly" as its quite experimental stuff. If you change the viewer (left menu) it should be perfect. 

We are going to update the pdf lib soon which might make a difference. Im going to close for now.
