### ISSUE TITLE
502 bad gateway. apache conf ?

### ISSUE THREAD

**Issue by benoitldr** [sharelatex/sharelatex#389]
Hello,

I want to install sharelatex on a debian server jessie 8 to work with colleagues. 

I read this topic https://github.com/sharelatex/sharelatex/issues/83 and your topic on apache reverse proxy but I still have this 502 Bad Gateway.

All dependencies for sharelatex are installed and the installation by docker is without error.

mod_proxy is loaded on apache too.

here is my conf for this site (I have owncloud, emby and others stuff on apache working so the apache server is well configured).

[https://framabin.org/?0e3b451b46b0b69e#cuhhZnyxN9gpSnupGHpWzETMgUaNxxpDZIzW7vwwMS8=]

Thanks you in advance.

Benoit

**Comment by zeigerpuppy** [comment]
Hi @benoitldr,
please check your module settings, you also need to enable mod_proxy_wstunnel
to run sharelatex behind an apache proxy.

also your proxypass statements are broken 
they'll need to be something like the following

But I would suggest to try running nginx as it looks like you're on a local install anyway.

```
ProxyPass / http://localhost:3026/
ProxyPassReverse http://localhost:3026/
```

**Comment by benoitldr** [comment]
Hello

My system was not clean, so I decided to install from scratch to have a clean system, I decided to use nginx for better integration with sharelatex. I am in the middle of installation but I have to learn nginx because I am a apache user...

I try to install with git method instead of docker I will see...

Thank you anyway !

**Comment by zeigerpuppy** [comment]
sounds like a good idea, I don't much like docker myself, git install is probably a good way to go and there are good docs here for nginx in the wiki.

**Comment by benoitldr** [comment]
Still have this 502 Bad Gateway grr!!!

My nginx configuration :
https://framabin.org/?7f2524680dc157b9#enJew0IUevaeYYf1ivhiEDokbqC45TTyNOeO/JUqkLY=

I discover nginx so it is difficult for me.

I hope I will find a solution, 4h for installing sharelatex...

Benoit

**Comment by benoitldr** [comment]
other configuration find in the internet

[https://framabin.org/?4c65e23d83e2fe44#t+d3kvSysJrhysSXhhVLmSuffozUfX6vokuPcPwZBP8=](url)

**Comment by MarcoMeter** [comment]
@benoitldr Could you post your config again?
