### ISSUE TITLE
nginx config new install on xubuntu 15.10 clean

### ISSUE THREAD

**Issue by benoitldr** [sharelatex/sharelatex#391]
Hello

I still try to install sharelatex on xubuntu clean from scratch...

I install the dependencies and sharelatex via docker.

I still have 502 bad gateway and impossible to start service nginx with the nginx.conf on https://github.com/sharelatex/sharelatex/wiki/HTTPS-reverse-proxy-using-Nginx

Really need help...

**Comment by henryoswald** [comment]
any errors in the nginx logs?

**Comment by benoitldr** [comment]
`
-- L'unité (unit) nginx.service a terminé son arrêt.
févr. 11 17:59:39 rollo systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: L'unité (unit) nginx.service a commencé à démarrer
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- L'unité (unit) nginx.service a commencé à démarrer.
févr. 11 17:59:39 rollo nginx[1530]: nginx: [emerg] "server" directive is not allowed here in /etc/nginx/nginx.conf:5
févr. 11 17:59:39 rollo nginx[1530]: nginx: configuration file /etc/nginx/nginx.conf test failed
févr. 11 17:59:39 rollo systemd[1]: nginx.service: Control process exited, code=exited status=1
févr. 11 17:59:39 rollo systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: L'unité (unit) nginx.service a échoué
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- L'unité (unit) nginx.service a échoué, avec le résultat failed.
févr. 11 17:59:39 rollo systemd[1]: nginx.service: Unit entered failed state.
févr. 11 17:59:39 rollo systemd[1]: nginx.service: Failed with result 'exit-code'.
févr. 11 17:59:39 rollo sudo[1517]: pam_unix(sudo:session): session closed for user root
févr. 11 17:59:39 rollo polkitd(authority=local)[634]: Unregistered Authentication Agent for unix-process:1518:1997 (system bus name :1.53, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale fr_FR.UTF-8) (disconnected fr
févr. 11 17:59:54 rollo dbus[524]: [system] Failed to activate service 'org.bluez': timed out
févr. 11 17:59:58 rollo systemd-timesyncd[518]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
févr. 11 17:59:58 rollo systemd[1]: Time has been changed
-- Subject: Changement d'heure
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- L'horloge système a été modifiée et positionnée à REALTIME microsecondes
-- après le 1er janvier 1970.
févr. 11 17:59:58 rollo systemd[1059]: Time has been changed
-- Subject: Changement d'heure
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- L'horloge système a été modifiée et positionnée à REALTIME microsecondes
-- après le 1er janvier 1970.
`

**Comment by henryoswald** [comment]
im not sure what is wrong sorry.

**Comment by benoitldr** [comment]
@henryoswald 

thanks you I will search on the web on the nginx configuation...

**Comment by benoitldr** [comment]
@henryoswald 

in fact I found the solution :
`#/bin/bash
docker run -d --name sharemongo mongo:latest
docker run -d --name shareredis redis:latest
docker run -d -P -p 5000:80 -v /opt/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_ADMIN_EMAIL=admin@blandrieu.fr --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex`

Now I still have problem to create admin user

**Comment by flop25** [comment]
sry to disturb you guys but @benoitldr what did you effectively change?
