### ISSUE TITLE
Issues when upgrading from 0.1.4 to 0.2.0

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#393]
Hi, 

I am running Ubuntu 12.04 and so far ShareLaTeX 0.1.4 (manually installed) worked like a charm. I moved the the 0.1.4 version in /var/www to a backup folder and installed 0.2.0 in /var/www/sharelatex using git clone ... sudo npm install and sudo grunt install.

After restarting ShareLaTeX everything works fine, however, when I try to open a project I get one of the following error messages:

"Error opening document. Sorry, something went wrong opening this document. Please try again."
"LaTeX error: file xy not found."

For some projects I see at least the LaTeX code but for some I only see the spinning "Loading" symbol in the editor window.

Interestingly, when I create a new project, everything works fine, so the issue is only with the old, existing project. When I switch back to the old 0.1.4 version by exchanging the 'sharelatex' folder in /var/www/ with the old one, all the old projects still compile, but I instead get the same error with the test project, recently created under 0.2.0, i.e.:

"Error opening document. Sorry, something went wrong opening this document. Please try again."
and no text in the editor, while the Loading symbol keeps spinning.

Is that somehow an expected behavior and is there a workaround? Are project files among v.0.2.0 and v.0.1.4 incompatible?

Thanks and regards!

**Comment by henryoswald** [comment]
Hi you need to run grunt migrate. The docker instance will auto do this.

sent from my phone.

**Comment by hulk1st** [comment]
1) Incredibly fast reply - thanks a lot for this!!
2) Works perfectly - thank you very much!
3) For some reason the docker image never worked on my system, that's why I stuck to the manual installation procedure.

Again, thank you!

**Comment by henryoswald** [comment]
great!

On Thu, Feb 11, 2016 at 9:38 PM, hulk1st <notifications@github.com> wrote:

> 1) Incredibly fast reply - thanks a lot for this!!
> 2) Works perfectly - thank you very much!
> 3) For some reason the docker image never worked on my system, that's why
> I stuck to the manual installation procedure.
>
> Again, thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/393#issuecomment-183068497>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by hulk1st** [comment]
Hi Henry,

I think I just killed my ShareLaTeX installation by messing around with my LaTeX installation.

- I changed the path in the init scripts from 2014 to 2015
- I ran "tlmgr update --self --all --reinstall-forcibly-removed" to update latex.
- I deleted the 2014 folder.
- I ran "export PATH=/usr/local/texlive/2015/bin/x86_64-linux:$PATH"

When I started ShareLaTeX again i only saw the spinning loading symbol. For some projects It does show the code but gives an instant compile error, for some it can not even open the project but gives 

"Sorry, something went wrong opening this document. Please try again."

I tried to revert my changes and copied back the texlive/2014 folder from a backup. I ran "export PATH=/usr/local/texlive/2014/bin/x86_64-linux:$PATH" again and I changed back the 2015 path in the init scripts to 2014.

Still no success. Any idea? Would grunt migrate help here or could it even destroy something? I'm quite desperate at the moment cause there is really important stuff on the machine ...

Thank you very much in advance for your help!!!

**Comment by hulk1st** [comment]
Update: It runs with a lot of warnings using "sudo grunt run:all --force"

**Comment by hulk1st** [comment]
closed as problem is not related to the original issue.

**Comment by hulk1st** [comment]
Got it working again. The solution was to re-run ./install-tl first in the 2014 and then in the 2015 folder.
