### ISSUE TITLE
Changes in Dropbox being ignored by ShareLaTeX (similar to #328)

### ISSUE THREAD

**Issue by MicaelCarvalho** [sharelatex/sharelatex#394]
Hello,

I believe the Dropbox integration may have some sort of bug; I deleted a bunch of old images from the ShareLaTeX-Dropbox project folder, but they were not removed from ShareLaTeX. Furthermore, I added new things to the project directly through the ShareLaTeX website, and they were successfully upload to Dropbox. So, it seems that the issue happens only when changes _come from_ Dropbox.

Reference, project number : 56c1c98995d0290516100181
This happens both in folders and in the root dir.

Cheers and keep up the good work ! :+1:

**Comment by henryoswald** [comment]
Hi,

can you please send this via support@sharelatex.com rather than here please.
