### ISSUE TITLE
Kaspersky Endpoint Security interfering with ShareLaTeX loading

### ISSUE THREAD

**Issue by spikecurtis** [sharelatex/sharelatex#401]
I'm hitting the same issue as #345 but I'm confident Kaspersky Endpoint Security is the culprit, since temporarily disabling it solves my issue.

I'm on Community Edition, version 0.2.0 (Docker image).

Can you share some technical details about why Avast was blocking ShareLaTeX?  I suspect Kaspersky is doing something similar and it'd be nice to know where to start in terms of config.

**Comment by henryoswald** [comment]
Avast was injecting a custom ssl cert on the web page, but their implementation just plain broke websockets.

**Comment by spikecurtis** [comment]
Thanks for the info!
