### ISSUE TITLE
VCS integration (git etc.)

### ISSUE THREAD

**Issue by exislow** [sharelatex/sharelatex#406]
There is already a build in kind of VCS system. A version point is set on every compile. Why you do not replace it by an interface for a real VCS like git at least provide the option, to use ones own VCS system for revision history?

Another possibility is to develop a VCS sync (like Dropbox sync but to a VCS). Is it possible for you?

**Comment by henryoswald** [comment]
we have github integration, we might look at git integration in the future (there are other issues open)

**Comment by stefnotch** [comment]
Relevant issue https://github.com/overleaf/overleaf/issues/10
