### ISSUE TITLE
Latex templates are missing?

### ISSUE THREAD

**Issue by apus2016** [sharelatex/sharelatex#412]
Hi, 

i just installed sharelatex from github.

For whatever reason there are no templates listed in the dropdown menu when pressing NewProject.

Can somebody please tell me where they went?

https://de.sharelatex.com/learn/Creating_a_project_from_a_template
https://de.sharelatex.com/templates/

Thanks for your help!

**Comment by henryoswald** [comment]
The templates on ShareLaTeX are not included as part of the open source release.

**Comment by apus2016** [comment]
Wow, fast reply!
How can I include them?

**Comment by henryoswald** [comment]
They are not available for the community version I'm afraid.

**Comment by apus2016** [comment]
Ok, is there then a way to include my own packages somehow? Like I have a lot of stuff in my ~/.texmf directory. I need that stuff somewhere global, so I don't have to add it to each project manually.

**Comment by apus2016** [comment]
Nevermind, i just have to put the stuff in /var/www/sharelatex/texmf if the output of "tlmgr conf" is correct.

**Comment by hulk1st** [comment]
Normally you place custom packages, fonts, styles, etc. in ```/usr/local/texlive/texmf-local/``` and the corresponding sub-directories, typically ```/tex/latex/```. Then they are system-wide available and also survive upgrades to newer texlive versions. After upgrading you should then run a ```sudo mktexlsr```, or if your texlive binaries are not in your path, ```sudo /usr/local/texlive/2015/bin/x86_64-linux/mktexlsr```.
