### ISSUE TITLE
Install Docker; /etc/my_init.d/99_migrate.sh failed with status 6

### ISSUE THREAD

**Issue by ilpepe** [sharelatex/sharelatex#428]
Hi,

I get this error when trying to start the docker image.

'connect ECONNREFUSED
Warning: Command failed:  Use --force to continue.

Aborted due to warnings.
*** /etc/my_init.d/99_migrate.sh failed with status 6

*** Killing all processes...'

I'm coming from github 0.13 going to docker.
However I already deleted the github folder. which makes it hard to do a 'grunt migrate'. 
Should I reinstall from github

best regards,
Pieter

**Comment by henryoswald** [comment]
It will be because docker can't see mongodb.

sent from my phone.

**Comment by ilpepe** [comment]
Thanks for the fast reply. 
Indeed I now saw that mongodb was not able to run anymore after I changed the IP_bind.
It does however work when set to 127.0.0.1

firewall is down...

Any suggestions?
