### ISSUE TITLE
Docker installation sees projects, not files

### ISSUE THREAD

**Issue by ilpepe** [sharelatex/sharelatex#430]
Hi,
I coming from github 0.14 to docker 0.2 on debian jessie.

As this was quiet a big step, I decided to test this installation first on a sandbox server.

I did a mongodump of the running sharelatex instance and did a mongorestore on the sandbox server.
I copied the user_files (./data and ./tmp) to the location that was in the script (/root/sharelatex_data) as the docker instance is run as root. I decided to change the ownership of all these to root:root.

'docker run -d \
        -v ~/sharelatex_data:/var/lib/sharelatex \
        -p 5000:80 \
        --name=sharelatex \
        sharelatex/sharelate'

When I then restart sharelatex, I can all my projects (from the older installation). I can open the project and see all the files. However I can not open the files and get a 
"Sorry, something went wrong opening this document. Please try again."

I probably set some rights wrong, but I don't now which ones.
any help?

**Comment by ilpepe** [comment]
Relevant log? document-updater

{"name":"documentupdater","hostname":"08181d738200","pid":75,"level":50,"err":{"message":"error accessing web API: http://localhost:3000/project/56bde727144dfe59034bf951/doc/56bdf022144dfe59034bf957 500","name":"Error","stack":"Error: error accessing web API: http://localhost:3000/project/56bde727144dfe59034bf951/doc/56bdf022144dfe59034bf957 500\n  at Request._callback (/var/www/sharelatex/document-updater/app/js/PersistenceManager.js:91:27)\n  at Request.self.callback (/var/www/sharelatex/document-updater/node_modules/request/index.js:148:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/document-updater/node_modules/request/index.js:891:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/document-updater/node_modules/request/index.js:842:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickCallback (node.js:448:13)\n"},"msg":"request errored","time":"2016-05-20T15:07:10.323Z","v":0}

**Comment by henryoswald** [comment]
is there an error in the web logs?

**Comment by ilpepe** [comment]
indeed an error popped up:

'name":"web-sharelatex","hostname":"6ad4e24ff063","pid":85,"level":50,"err":{"message":"no root document exists","name":"Error","stack":"Error: no root document exists\n'

**Comment by mujeeb2** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Less Than 2 Hours! We’re coming down to the wire…http://bit.ly/1s061Pr

Sent from Yahoo Mail for iPhone


On Saturday, May 21, 2016, 1:44 AM, Henry Oswald <notifications@github.com> wrote:


is there an error in the web logs?

**Comment by ilpepe** [comment]
I now also added
--env SHARELATEX_SITE_URL=http://localhost:5000 \
To the script because i'll have to use nginx as proxy on the host.

**Comment by henryoswald** [comment]
Hi,

it looks like there isn't a root document set for the project, if you go into the left menu and set it does that fix the issue?

**Comment by ilpepe** [comment]
Nope.
I also loaded different the value for all dropdown menu, just to be sure.
A main document was selected (the correct on).

**Comment by ilpepe** [comment]
{"name":"web-sharelatex","hostname":"6ad4e24ff063","pid":85,"level":50,"err":{"message":"docstore api responded with non-success code: 404","name":"Error","stack":"Error: docstore api responded with non-success code: 404\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:108:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"project_id":"5447736100b5dc485ec5aa3e","doc_id":"5447736100b5dc485ec5aa42","msg":"error getting doc from docstore","time":"2016-05-22T19:14:33.201Z","v":0}
{"name":"web-sharelatex","hostname":"6ad4e24ff063","pid":85,"level":50,"err":{"message":"docstore api responded with non-success code: 404","name":"Error","stack":"Error: docstore api responded with non-success code: 404\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:108:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"doc_id":"5447736100b5dc485ec5aa42","project_id":"5447736100b5dc485ec5aa3e","msg":"error finding element for getDocument","time":"2016-05-22T19:14:33.201Z","v":0}
{"name":"web-sharelatex","hostname":"6ad4e24ff063","pid":85,"level":50,"err":{"message":"docstore api responded with non-success code: 404","name":"Error","stack":"Error: docstore api responded with non-success code: 404\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:108:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"url":"/project/5447736100b5dc485ec5aa3e/doc/5447736100b5dc485ec5aa42","method":"GET","msg":"error passed to top level next middlewear","time":"2016-05-22T19:14:33.201Z","v":0}
{"name":"web-sharelatex","hostname":"6ad4e24ff063","pid":85,"level":30,"req":{"url":"/project/5447736100b5dc485ec5aa3e/doc/5447736100b5dc485ec5aa42","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":500},"response-time":11,"msg":"http request","time":"2016-05-22T19:14:33.205Z","v":0}

**Comment by ilpepe** [comment]
document-updater.log:
{"name":"documentupdater","hostname":"d4694c992769","pid":72,"level":50,"err":{"message":"error accessing web API: http://localhost:3000/project/56ceefa7144dfe59034bf9a6/doc/56ceefa7144dfe59034bf9a7 500","name":"Error","stack":"Error: error accessing web API: http://localhost:3000/project/56ceefa7144dfe59034bf9a6/doc/56ceefa7144dfe59034bf9a7 500\n  at Request._callback (/var/www/sharelatex/document-updater/app/js/PersistenceManager.js:91:27)\n  at Request.self.callback (/var/www/sharelatex/document-updater/node_modules/request/index.js:148:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/document-updater/node_modules/request/index.js:891:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/document-updater/node_modules/request/index.js:842:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickCallback (node.js:448:13)\n"},"msg":"request errored","time":"2016-05-22T20:13:32.092Z","v":0}

there was a port 3000 hard coded so I changed everything back to port 3000 (instead of 5000). didn't help...

**Comment by henryoswald** [comment]
Do you configure mongodb via env vars?

**Comment by ilpepe** [comment]
Hi,
Nope.
Do you mean: 
'--env SHARELATEX_MONGO_URL=mongodb://dockerhost/sharelatex \' 
?

Because the files can be seen, I suppose sharelatex knows where mongo is?
Mongo ip_bind was done.

**Comment by henryoswald** [comment]
yeah. If you go into mongodb and find a project, do the documents inside the project have the content in them? (no content in them is good news)

db.projects.find({_id:ObjectId('MY_PROJECT_ID')})

**Comment by ilpepe** [comment]
Hi, 
There is content. I actually can read the tex text. (this is performed on dockerhost, not inside the docker (just to make things clear).
I'll try with the env vars then. I suppose I'll have to do the same for Redis?

Do I have to redownload the whole image, with the env vars or can I just rerun

'docker run -d \
-v ~/sharelatex_data:/var/lib/sharelatex \
-p 5000:80 \
--name=sharelatex \
sharelatex/sharelatex'

with the env attached?

**Comment by henryoswald** [comment]
it sounds like the migrations have not run. Try killing the container and starting it again.

**Comment by ilpepe** [comment]
I remove the complete docker, I removed the image, and redownloaded it.

Reran the docker.

I checked again if there was content in a file, and there is.

Could there be a permission problem when transferring the database? (as I dumped on the original machine and restored it on the sandbox).

Can I try to run the migrate manually in /var/www/sharelatex with grunt migrate? or doesn't this make any sense?

Best regards,
Pieter

**Comment by ilpepe** [comment]
In the docker i was browsing through the settings.development.coffee, and there the mongo url is 

url : 'mongodb://127.0.0.1/sharelatex'


      redis:
                web:
                        host: "localhost"
                        port: "6379"
                        password: ""

which doesn't seem right, or is this overwritten by the env?

**Comment by ilpepe** [comment]
In the end it seems to have been a firewall issue...
