### ISSUE TITLE
Baremetal Install Guide

### ISSUE THREAD

**Issue by storrgie** [sharelatex/sharelatex#436]
If possible, it would be nice to have a baremetal install guide for one of the common distros. Docker is great for those who are willing to use it, but it would be nice to be able to see the fully dependency chain and instructions.

**Comment by henryoswald** [comment]
You could follow the docker file to see what is needed, that documents everything. ShareLaTeX is quite complex so we strongly recommend using docker. https://github.com/sharelatex/sharelatex-docker-image
