### ISSUE TITLE
sharelatex/releases still maintained?

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#437]
Hi,

I noticed the v0.3.0 release notes appeared in the wiki some time ago but the latest version in the releases branch is still v0.2.0, hence I wondered if this branch is still maintained or do you now focus on the docker image solely?

Thanks!

**Comment by henryoswald** [comment]
Hi. We just focus on docker now. Tags and branches are not used.

sent from my phone.

**Comment by hulk1st** [comment]
Thanks!

**Comment by dpantele** [comment]
Hello @henryoswald,

Which revisions are safe-to-use now? I build my own docker images, because for me it is much easier to maintain the service using docker-compose without any in-the-container init. But looks like using the release branch will not work now...
