### ISSUE TITLE
sharelatex CDNs down ?

### ISSUE THREAD

**Issue by saru95** [sharelatex/sharelatex#455]
This is what I get on opening the website . Pages dont load ! 
![screen shot 2016-08-07 at 5 12 55 pm](https://cloud.githubusercontent.com/assets/6523503/17462181/3f800016-5cc2-11e6-8f43-06e93538dc2c.png)

**Comment by henryoswald** [comment]
Hi it's possible your network connection is blocking our cdn. We have seen
that come up a bit recently since setting up cdn.sharelatex.com. Generally
whoever runs your network can unblock it.

sent from my phone.

**Comment by saru95** [comment]
@henryoswald do you happen to know any workaround ?

**Comment by henryoswald** [comment]
Just asking why it is being blocked by your networks firewall. There isn't
a lot we can do if our connections are being blocked I'm afraid.

sent from my phone.

**Comment by henryoswald** [comment]
I assume you are on a university or company connection?

sent from my phone.
