### ISSUE TITLE
Register users

### ISSUE THREAD

**Issue by jordanandres1** [sharelatex/sharelatex#461]
I want that everyone can register in the register page and I don't want the message Please contact example@email.com to create an account.

How can I change that?

PS: I am using docker

**Comment by henryoswald** [comment]
Hi,

this is not possible with the open source release, the person running the instance has to manage who has access. Server Pro has the feature as it is designed for larger groups of people.

**Comment by OrnithOrtion** [comment]
It is very disappointing.
It should be a function that can be set available or not via overleaf.rc, as it was functionnal in former versions.

**Comment by scmanjarrez** [comment]
I've implemented a very basic register. I'll leave it here for future reference: https://gist.github.com/scmanjarrez/a318a2ef8a0861a13b3643a4ea5ff052
