### ISSUE TITLE
ShareLatex Docker start does not work

### ISSUE THREAD

**Issue by DaGeRe** [sharelatex/sharelatex#464]
I am currently trying to start the docker image with 

docker run -d   -v /var/lib/sharelatex_data:/var/lib/sharelatex   -p 8400:80   --name=sharelatex   sharelatex/sharelatex

The folder /var/lib/sharelatex_data is empty and accessible and the port 8400 is free. Nevertheless, the container is existing printing the following output:

> Initializing
> Command-line options: --verbose
> 
> Reading "Gruntfile.coffee" Gruntfile...OK
> 
> Registering Gruntfile tasks.
> 
> Registering "grunt-bunyan" local Npm module tasks.
> Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
> Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
> Loading "bunyan.js" tasks...OK
> + bunyan
> 
> Registering "grunt-execute" local Npm module tasks.
> Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
> Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
> Loading "execute.js" tasks...OK
> + execute
> 
> Registering "grunt-available-tasks" local Npm module tasks.
> Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
> Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
> Loading "available_tasks.js" tasks...OK
> + availabletasks
> 
> Registering "grunt-concurrent" local Npm module tasks.
> Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
> Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
> Loading "concurrent.js" tasks...OK
> + concurrent
> 
> Registering "grunt-contrib-coffee" local Npm module tasks.
> Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
> Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
> Loading "coffee.js" tasks...OK
> + coffee
> 
> Registering "grunt-shell" local Npm module tasks.
> Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
> Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
> Loading "shell.js" tasks...OK
> + shell
> Initializing config...OK
> Loading "Gruntfile.coffee" tasks...OK
> + build:upstart_scripts, check, check:aspell, check:fs, check:latexmk, check:make, check:redis, check:s3, default, help, install, install:all, install:chat, install:clsi, install:dirs, install:docstore, install:document-updater, install:filestore, install:real-time, install:spelling, install:tags, install:track-changes, install:web, migrate, release:chat, release:clsi, release:docstore, release:document-updater, release:filestore, release:real-time, release:spelling, release:tags, release:track-changes, release:web, run, run:all, run:chat, run:clsi, run:docstore, run:document-updater, run:filestore, run:real-time, run:spelling, run:tags, run:track-changes, run:web, update, update:all, update:chat, update:clsi, update:docstore, update:document-updater, update:filestore, update:real-time, update:spelling, update:tags, update:track-changes, update:web
> 
> Running tasks: migrate
> 
> Running "migrate" task
> 
> Running "coffee:migrate" (coffee) task
> Verifying property coffee.migrate exists in config...OK
> Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
> Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
> Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
> Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
> Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
> Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
> Reading migrations/2_doc_lines_delete_from_project.coffee...OK
> Writing migrations/2_doc_lines_delete_from_project.js...OK
> Reading migrations/3_pack_docHistory_collection.coffee...OK
> Writing migrations/3_pack_docHistory_collection.js...OK
> 
> Running "shell:migrate" (shell) task
> Verifying property shell.migrate exists in config...OK
> File: [no files]
> Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
> Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex
> 
> /var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
> 	this.db.close(callback);
> 	        ^
> TypeError: Cannot call method 'close' of undefined
>     at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:10)
>     at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
>     at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
>     at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:148:20)
>     at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
>     at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
>     at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:155:17)
>     at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
>     at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
>     at /var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:69:17
> Warning: Command failed: 
> /var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
> 	this.db.close(callback);
> 	        ^
> TypeError: Cannot call method 'close' of undefined
>     at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:10)
>     at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
>     at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
>     at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:148:20)
>     at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
>     at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
>     at next (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:155:17)
>     at Group.done (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:30:16)
>     at Group.error (/var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:34:7)
>     at /var/www/sharelatex/node_modules/east/node_modules/twostep/lib/twoStep.js:69:17
>  Use --force to continue.
> 
> Aborted due to warnings.
> *** /etc/my_init.d/99_migrate.sh failed with status 6
> 
> *** Killing all processes...
> 

I could not find any other issue representing this problem. Is there a solution / workaround for this?

**Comment by henryoswald** [comment]
it can't talk to mongo

**Comment by michalwidera** [comment]
Clean new system, same issue after instalation of sharelatex by docker.

**Comment by michalwidera** [comment]
Solution found.
Need to install and start mongod manualy.

**Comment by bean5** [comment]
@michalwidera where did you install mongod manually? Inside the mongo container?

**Comment by michalwidera** [comment]
Outside container.
