### ISSUE TITLE
Feature Request: Comment Layer

### ISSUE THREAD

**Issue by jmaddock** [sharelatex/sharelatex#486]
We use sharelatex in my lab frequently, but inline commenting gets messy after multiple edit cycles with multiple collaborators.  This is especially true when comments need to be inserted into the middle of a paragraph.  An additional comment layer like the one included in MS Word or Google Docs would help solve this problem.

**Comment by henryoswald** [comment]
thanks, closing as it a dup of https://github.com/sharelatex/web-sharelatex/issues/8
