### ISSUE TITLE
Code Checker fails inside listing

### ISSUE THREAD

**Issue by mrdrozdov** [sharelatex/sharelatex#488]
Using a modulus symbol % seems to throw the code checker off.

![screenshot 2016-11-12 11 45 22](https://cloud.githubusercontent.com/assets/1575034/20239424/a7503c86-a8cd-11e6-9b3d-83233cab0e93.png)

**Comment by briangough** [comment]
Thanks for the bug report, minted was missing from the list of 'verbatim'-like environments in the code checker.  I've added it now so this should fix the problem.

**Comment by mrdrozdov** [comment]
Thanks!
