### ISSUE TITLE
[Wiki] deprecated documentation for deleting user

### ISSUE THREAD

**Issue by gelim** [sharelatex/sharelatex#490]
Hi,

the documentation at [Creating-and-managing-users](https://github.com/sharelatex/sharelatex/wiki/Creating-and-managing-users#deleting-users) references the command `grunt delete-user --email joe@example.com` while it should be ([code ref.](https://github.com/sharelatex/sharelatex/blob/master/grunt/CreateAndDestoryUsers.coffee#L38)) `grunt` user:delete --email joe@example.com`

Cheers

**Comment by henryoswald** [comment]
Thanks, thats fixed now.
