### ISSUE TITLE
Documentation proposition for raw install on a ubuntu server 16.04

### ISSUE THREAD

**Issue by gelim** [sharelatex/sharelatex#491]
Hi, this is not a bug, more a proposition to references what I did recently, try to document the non docker install of sharelatex: https://gist.github.com/gelim/a840a99d15cb765cb7b65105b72f00c4

Maybe that can be of any use for devs, or admins that don't want to add the burden of managing docker containers. Don't hesitate to remove this BR, and move the info to a more appropriate location.

Cheers

**Comment by henryoswald** [comment]
Hi,

thanks a lot for doing those docs. Feel free to support them but I want to only support Docker from our side as it becomes unmanageable otherwise with different init scripts, proxies, install issues etc.
