### ISSUE TITLE
Cannot access sharelatex server from outside

### ISSUE THREAD

**Issue by hankook** [sharelatex/sharelatex#492]
```bash
$ sudo docker run -d \
    -v ~/sharelatex_data:/var/lib/sharelatex \
    -p 5000:80 --name=sharelatex \
    --env SHARELATEX_SITE_URL=http://[url]:5000
    sharelatex/sharelatex
```

I use this command for run sharelatex. If I'm in the same network with my server, I can access the server. However, If I'm out of the network(I tested by using my iPhone via LTE), then I cannot access.

The `[url]` is a public domain I already have. Also I have used the `[url]:80` for another hompage. I can access this homapage from outside.

I want to access my sharelatex server from outside such as the homepage. How do I fix it?
Does I use the `SHARELATEX_SITE_URL` environment variable correctly?

**Comment by henryoswald** [comment]
Hi,

if you can access it from inside the network but not outside there is something at a level above ShareLaTeX blocking it.
