### ISSUE TITLE
Backup in the cloud

### ISSUE THREAD

**Issue by gianvito** [sharelatex/sharelatex#501]
- Official Docker version being run: 1.12.5 build 7392c3b
- URL to appropriate logs: none

Hi all,
I succesfully installed and configured sharelatex community, through docker-compose.
I read that dropbox sync is currently unavailable. However, I do not need collaborative (offline) editing, but just a safe continuous (that is, for each change) backup in the cloud.

Any suggestion? 
Thank you.

**Comment by henryoswald** [comment]
Not really sorry. You can manually use ShareLaTeX with dropbox but not with the auto integration. If you are going to work on ShareLaTeX the best thing is to use it 100% of the time. Offline sync with a real time editor is very complex.
