### ISSUE TITLE
Domain name in e-mails

### ISSUE THREAD

**Issue by gianvito** [sharelatex/sharelatex#504]
Official Docker version being run: 1.12.5 build 7392c3b
URL to appropriate logs: none

Hi all,
sorry for the probably naive question, but I cannot find the way to change the IP which appears in links of invitation to register and/or to collaborate to projects.

In particular, they are: "http://localhost/project/ ...."
I just want to change them to "http://myip/project/ ...."

I could not find any environment variable in the docker-compose file.

Thank you

**Comment by henryoswald** [comment]
Hi,

you want SHARELATEX_SITE_URL https://github.com/sharelatex/sharelatex/wiki/Configuring-ShareLaTeX
