### ISSUE TITLE
More than one admin user

### ISSUE THREAD

**Issue by gianvito** [sharelatex/sharelatex#508]
- Official Docker version being run: 1.12.5 build 7392c3b
- URL to appropriate logs: none

Is it possible to have more than one admin user?
If I execute the command:
`docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email joe@example.com"`

when there is already an admin user, will they be both admins?

Thank you

**Comment by tiagodanielff** [comment]
+1 for this feature. 
When you are within an organization you need to breakdown responsibilities and assign different roles, without losing control of the projects in the pipeline. Sharelatex still doesn't support anything in this area.

**Comment by henryoswald** [comment]
Yes you can have multiple admin users.
