### ISSUE TITLE
Git rename does not rename files in Sharelatex

### ISSUE THREAD

**Issue by HalfLeif** [sharelatex/sharelatex#531]
I sync my Sharelatex project against Github. After syncing a commit that includes a git file rename, the file still keeps the old name in Sharelatex and hence causes the corresponding \input{} to fail.

[Commit with renames](https://github.com/HalfLeif/Master-Thesis---Waypointing/commit/9ae942ace0df1a660383a005d0e786c4871878e5)

In this case I did
git mv background_htr.tex alternative_methods.tex

but in Sharelatex there is now an empty file called background_htr.tex while alternative_methods.tex does not exist at all! So I have to manually create a new file and copy the text into Sharelatex, push to Github and sync again in order to fix it...

Using git version 2.10.1 (Apple Git-78)

**Comment by rmaguire31** [comment]
Second this. Wondered for a while why old renamed files kept reappearing in our github repo. Turns it it was sharelatex

**Comment by jpallen** [comment]
We had a bug that would have caused this, but it was fixed at the beginning of last week. Sorry for any trouble. If you see an issue again on www.sharelatex.com, please contact us at support@sharelatex.com. Thanks!
