### ISSUE TITLE
Docker 0.6.2 - Track changes and comments  does not work

### ISSUE THREAD

**Issue by bott0r** [sharelatex/sharelatex#533]
Docker image 0.6.2 Track changes and comments does not work.

**Comment by bott0r** [comment]
only available in pro edition.

**Comment by tarheels100** [comment]
But the complete source for ShareLaTeX is available here, correct?  If I compile my own docker container, shouldn't all features be available?

**Comment by zeigerpuppy** [comment]
Really disappointing that track changes and comments are pro-edition only.
I can understand why user management and sandboxing would be pro but this just seems mean!

**Comment by henryoswald** [comment]
We have to draw a line in the sand somewhere I'm afraid. It takes a lot of developer time to build these new features meaning we can't afford to make every feature free.

**Comment by gitfortat** [comment]
I am very disappointed that tracking changes is actually not available in the normal version. Is it really ok to still say this software is under AGPL? I think you should point out that there are two versions. One under AGPL, with less features, one under whatever (proprietary?) license. I am not against making money with software; but it should still be free (libre). I would pay for development of features that I need and I would also donate money, but only for free software.

**Comment by henryoswald** [comment]
Hi,

this is a very common pattern used by many companies to build a business. ShareLaTeX is still AGPL, there is also a handful of premium features which we offer on ShareLaTeX.com and via premium self install (server pro).

**Comment by gitfortat** [comment]
Sorry, but this needs some further clarification for me. You are saying ShareLatex is under AGPL. If I upgrade a free account to "Collaborator" or "Professional", I will be able to use features for which I am not allowed to see the source code, which in turn violates AGPL. Am I mistaken here?

**Comment by Craskermasker** [comment]
Agreed, this sounds like an AGPL violation to me. Does the company have any intention of changing this - or must the community build their own tool for this?
