### ISSUE TITLE
Chromebook stuck loading project

### ISSUE THREAD

**Issue by joelmm** [sharelatex/sharelatex#542]
My Acer Chromebook 15, running Chrome version 58.0.3029.140 (64 bit) is getting permanently stuck while loading any project on Sharelatex. In the past, I've been able to use this machine to work on Sharelatex with no issues, so this is a recent development. I've tried standard solutions (clearing cache, restarting), and testing on other systems works with no problems. I'd appreciate any suggestions anyone could provide. See also the final comment in this closed issue for evidence that this is an ongoing problem: https://github.com/sharelatex/sharelatex/issues/253.

![screenshot 2017-06-16 at 2 13 34 pm](https://user-images.githubusercontent.com/6687114/27239217-083c2760-529e-11e7-9b0e-40213b72d984.png)

**Comment by ShaneKilkelly** [comment]
Can you check the browser console for errors?

Open the development tools (menu -> more tools -> development tools), and switch to the "Console" tab. Any errors shown there will help us figure out what's going wrong.

**Comment by joelmm** [comment]
Thanks for the suggestion. I tried checking the console, but nothing shows up after ten minutes or so. It seems like it just spins forever. It doesn't appear that any errors or exceptions are being thrown.

**Comment by ShaneKilkelly** [comment]
Thanks, that's useful info :)

This could be hard to test depending on circumstances, but does the project load ok from another computer on the same network?

**Comment by joelmm** [comment]
Yes, the network doesn't seem to be the issue, I've loaded it from a phone and another computer. I am also unable to load on my chromebook on a different network.

**Comment by ShaneKilkelly** [comment]
Thanks, one more thing, does this affect all projects, or just one?

**Comment by henryoswald** [comment]
I see you have a few browser extensions, can you try disabling some of them.

**Comment by ShaneKilkelly** [comment]
^ In particular, any extension which blocks websocket connections will prevent ShareLaTeX from working.

**Comment by joelmm** [comment]
I didn't make any changes, but whatever the issue was seems to have gone away, as I can now load projects. Thanks for all the suggestions, and I'm sorry I don't have a more satisfying explanation for what was going on.

**Comment by ShaneKilkelly** [comment]
Oh well, glad it's fixed :)
