### ISSUE TITLE
admin password set link always expire before using it

### ISSUE THREAD

**Issue by Erichliu00** [sharelatex/sharelatex#550]
## Problem
I installed sharelatex following the instruction by using docker-image, and used docker-compose.yml to start the ShareLaTeX. Not sure it is correct, but I assume it was correct.
To set admin password, I run the command:

`docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email myemail@gmail.com"`,
then I was told to visit a localhost to set a password, but every time I visit the link(by replacing localhost with IP address and port number) I was redirected to `http://IP address:5000/user/password/set` and was told that

> Your password reset token has expired. Please request a new password reset email and follow the link there.

## Install type

Docker Image

## Version

Docker version 17.06.0-ce, build 02c1d87

## Logs and errors

When I run the email config command it outputs the following information:

```
Running "user:create-admin" task
Set UV_THREADPOOL_SIZE=16
{"name":"default-sharelatex","hostname":"fa405cddc872","pid":17993,"level":40,"msg":"Email transport and/or parameters not defined. No emails will be sent.","time":"2017-07-30T12:38:07.734Z","v":0}
{"name":"default-sharelatex","hostname":"fa405cddc872","pid":17993,"level":30,"value":"597d81435a3a920c00a6d4d2","msg":"generating token for password reset","time":"2017-07-30T12:38:07.782Z","v":0}

Successfully created uestcliuhao@gmail.com as an admin user.

Please visit the following URL to set a password for uestcliuhao@gmail.com and log in:

        http://localhost/user/password/set?passwordResetToken=7e0a3804e1be27b9e6c1d756e05d79dd7c72213e9dbb9f9d652413cc15ede473


Done, without errors.

```

**Comment by Erichliu00** [comment]
solved

**Comment by jpallen** [comment]
Would you mind sharing the problem and solution in case anyone has a similar issue? Thanks!

**Comment by Erichliu00** [comment]
Sure, I followed the following instructions:

- install docker
- install sharelatex as in quick-guide
- modify yml file accordingly
- run `sudo docker-compose up -d`

Then things work smoothly.
