### ISSUE TITLE
LaTeX Error: File `biblatex.sty' not found.

### ISSUE THREAD

**Issue by jtatria** [sharelatex/sharelatex#555]
I'm trying to setup shrelatex for collaborative work, but when I tried to compile one of my projects, I get the fatal error:

LaTeX Error: File `biblatex.sty' not found.

normally, I wold assume this is because biblatex is not installed, but I was under the impression that shrelatex supported biblatex/biber as bibliography managers.

I'm using the recommended docker container method; I am a total novice with docker, I set it up on a debian machine just to try out sharelatex, so I have no idea how to check whether biblates is installed, etc.

Any help appreciated. Thanks!

**Comment by jpallen** [comment]
Have you followed the instructions at https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide#latex-environment to set up a complete TeXLive environment in the container?

**Comment by jtatria** [comment]
Aaah, I see. thanks for the heads up; I had so much trouble setting up docker on debian jessie/stretch that Ihad forgotten about the quickstart guide.

Would it be out of place to recommend that missing package errors included a suggestion about a way to install latex packages?

Sorry for the docker newbee question :)

**Comment by jpallen** [comment]
Sadly the error messages come for LaTeX itself, not ShareLaTeX, so it's not very feasible for us to change these. Interesting idea though!

**Comment by jtatria** [comment]
Oh I meant the wrapped message:
"The compiler cannot find the file you want to include. Make sure that you have uploaded the file and specified the file location correctly."

you have control over that one... so it may make sense to suggest how to fix it; I don't know if sharelatex should make assumptions about docker etc though.

an alternative would be to provide a frontend to texmgr in the admin section... I was kindy surprised by the lack of configuration options available, considering the many many options there are for a latex build chain.
