### ISSUE TITLE
xelatex complie error!

### ISSUE THREAD

**Issue by Hzzone** [sharelatex/sharelatex#567]
![](http://omoitwcai.bkt.clouddn.com/2017-10-29-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-10-29%20%E4%B8%8B%E5%8D%883.52.38.png)

**Comment by bonanza123** [comment]
Do you really expect someone to provide assistance without any kind of log/debug information?

**Comment by Hzzone** [comment]
@bonanza123 lol I have solved  this problem by `tlmgr install scheme-full` again

**Comment by bonanza123** [comment]
Then you probably wanna close this issue
