### ISSUE TITLE
Improvement: Proper handling of fonts, font encoding, input encoding and babel

### ISSUE THREAD

**Issue by ivankokan** [sharelatex/sharelatex#579]
Hi,

I have been dealing with multi-script and multi-lingual documents, and based on my experience I suggest you edit your recommendations on **all pages** related to `pdflatex`, e.g. [Using more than one language in a document](https://www.sharelatex.com/learn/International_language_support#Using_more_than_one_language_in_a_document) (all pages mentioning fonts, `fontenc`, `inputenc` or `babel`).

Let me explain thoroughly...

Proper way of doing it in order to support multi-script and multi-lingual is this:

1. loading font(s)
2. loading `fontenc`
3. loading `inputenc`
4. loading `babel`.

"1. before 2." is explained here: [LaTeX 2ε font selection](https://www.latex-project.org/help/documentation/fntguide.pdf).

> Warning: If you wish to use T1-encoded fonts other than the 'cmr' family then you may need to load the package (e.g. `times`) that selects the fonts before loading `fontenc` (this prevents the system from attempting to load any T1-encoded fonts from the 'cmr' family).

"2. before 3." is explained here: [In which order should I load inputenc and fontenc?](https://tex.stackexchange.com/questions/97252/in-which-order-should-i-load-inputenc-and-fontenc). Although it says

> No the order doesn't matter as `inputenc` contains some code to avoid "order problems".

such order was historically very important and I suggest you adopt it in your recommendations.

"4. after 2. and 3.": This is very important because many `babel` language definitions (still) depend on (previously) selected font encoding and input encoding.

Now the example of mixing English, Serbian and Lithuanian using Latin Modern (with fallback to Computer Modern for Serbian/Cyrillic), making English and corresponding settings the default in the document:

1. Computer Modern is loaded by default.
2. However, one might want to use Latin Modern instead.
```
\usepackage{lmodern}
```
3. T2A for (Serbian) Cyrillic, L7x for Lithuanian (script not fully covered within T1), T1 for English.
```
\usepackage[T2A,L7x,T1]{fontenc} % will make T1 (the last one in the list) selected by default
```
4. In order to support bold, sans and typewriter for Cyrillic script, one must instruct compiler not to use Latin Modern for T2A but Computer Modern instead (fallback).
```
\usepackage{substitutefont}
\substitutefont{T2A}{lmr}{cmr}
\substitutefont{T2A}{lmss}{cmss}
\substitutefont{T2A}{lmtt}{cmtt}
```
5.
```
\usepackage[utf8]{inputenc}
```
6.
```
\usepackage[serbianc,lithuanian,english]{babel} % will make english (the last one in the list) selected by default
```

All contents under document environment will be considered English/T1 by default. Once change is needed, the proper way/order is this:
1) Change language context, e.g. using `\selectlanguage{serbianc}` or other similar `babel` commands
2) ...and then change font encoding and font itself (if necessary) for the following contents, e.g. `\fontencoding{T2}\fontfamily{cmr}\selectfont`. (Note that `\fontfamily{cmr}` is not mandatory here due to font substitution in 4., but it is mandatory not having font substitution.)

Since these recommendations affect several pages, it might be easier if I propose a pull request? (Not sure about the repository, though.)

Kind regards, Ivan

**Comment by jdleesmiller** [comment]
Hello, thanks for getting in touch. Are these the pages you would like to propose changing under https://www.sharelatex.com/learn ? Or are there pages in other places?

**Comment by ivankokan** [comment]
Yes!

**Comment by ivankokan** [comment]
I added more explanations to the original post. Are [https://www.sharelatex.com/learn](https://www.sharelatex.com/learn) pages versioned somewhere so we move this improvement proposal there and discuss it further?

**Comment by jdleesmiller** [comment]
Sorry for the silence on this. The /learn pages aren't publicly editable, but I will pass this on to our latex support team for review. One of the key people is on holiday at the moment, but I hope that we'll be able to get back to you next week.

**Comment by ivankokan** [comment]
Sure thing. I can list all pages for which this proposal is relevant by then.

**Comment by jdleesmiller** [comment]
Sorry for the silence. I ran this past our support team and got some feedback:

- "such order was historically very important" Historically, yes, but we don't think that is true anymore. See https://tex.stackexchange.com/questions/241452/generating-a-template/241479#comment828002_241479 (2016)

- The `times` package is very badly outdated and buggy, capable of causing all sorts of problems (e.g. we've had users complaining that all the equal signs in their math environments are missing), so we are reluctant to recommend it.

- There are some inconsistencies in the order in which packages are loaded on https://www.sharelatex.com/learn/International_language_support , which we'll have a look at.

- Overall, using a modern, Unicode-capable TeX engine, such as XeTeX or LuaTeX, with OpenType fonts is the path of least resistance. We'll probably push people more in that direction.

If you have a list of other pages we should look at, that would be very welcome; feel free to reopen.

Thanks again for writing this in.

**Comment by ivankokan** [comment]
> * The `times` package is very badly outdated and buggy, capable of causing all sorts of problems (e.g. we've had users complaining that all the equal signs in their math environments are missing), so we are reluctant to recommend it.

I used `times` just to exemplify, with no idea you recommend it.




> * There are some inconsistencies in the order in which packages are loaded on https://www.sharelatex.com/learn/International_language_support , which we'll have a look at.

Have you, and what has changed?


I also made some edits about the font substitution because the `substitutefont` has been obsolete since 2020.
