### ISSUE TITLE
Modification of existing user e-mail address

### ISSUE THREAD

**Issue by kgmavridis** [sharelatex/sharelatex#583]
Is the following, a proper way to change the e-mail address of an existing (non-administrative) user, without affecting anything else, including own projects, shared projects, password etc?

```
sudo mongo --host 172.17.0.1
use sharelatex
db.users.update({email:"old-email@example.com"}, {$set:{email:"new-email@example.com"}}
```
I am using the docker image for ShareLatex community edition, whereas redis-server and mongodb are installed "directly" on Ubuntu 16.04.4 LTS.

Thank you for making this project freely available.

**Comment by shahdloo** [comment]
I would expect that this question receives at least a yes/no answer from the developers...

**Comment by shahdloo** [comment]
Sure, it’s obviously safer. On a side note, I was wondering if there is a way to list the registered users?

**Comment by jdleesmiller** [comment]
That's one place where using the database is pretty safe. I think you can run
```
mongoexport -d sharelatex -c users --type=csv --fields email --out users.csv
```
to get a list in CSV form.

I'll close this out for now.
