### ISSUE TITLE
Release notes for open source edition.

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/sharelatex#584]
I am trying to find the latest release notes for the current docker version of sharelatex (open-source).  Is there a current listing of changelogs by version?

**Comment by jdleesmiller** [comment]
Thanks for getting in touch!

We have some (sparse) release notes on the wiki, which also apply to the open source releases: https://github.com/sharelatex/sharelatex/wiki

And there is a list of tags for the open source docker releases here:
https://hub.docker.com/r/sharelatex/sharelatex/tags/

This is something we're hoping to improve (e.g. to get them into the info on dockerhub for each release).
