### ISSUE TITLE
enable review function

### ISSUE THREAD

**Issue by guolinke** [sharelatex/sharelatex#586]
It seems the "review" function is not available in open-source version. 
Is that by design or I need to enable it manually ?

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. The review features are currently on our paid plans, so they are not in the open source version.

**Comment by tianyu-su** [comment]
> Thanks for getting in touch. The review features are currently on our paid plans, so they are not in the open source version.

Hi, do you have any progress of the review function in the open-source version?
