### ISSUE TITLE
Login Page broken in all my browser

### ISSUE THREAD

**Issue by rickstaa** [sharelatex/sharelatex#592]
## Problem

I am unable to log in into sharelatex of overleaf v2. I tried running into incognito mode in three different browsers and clearing the cookies.

## Install type

Web:
- Chrome: Version 67.0.3396.99 (Official Build) (64-bit)
- Firefox: 61.0 (64-bit)
- Edge: Microsoft Edge 42.17134.1.0

## Logs and errors

Loading failed for the <script> with source “https://cdn.sharelatex.com/minjs/mathjax.js”. www.sharelatex.com:1
[Show/hide message details.] Error: Script error for: mathjax
http://requirejs.org/docs/errors.html#scripterror require.0cb51c1a5e8e978cbe069c07f3b8d16d.js:8:220
B
https://cdn.sharelatex.com/minjs/libs/require.0cb51c1a5e8e978cbe069c07f3b8d16d.js:8:220
onScriptError
https://cdn.sharelatex.com/minjs/libs/require.0cb51c1a5e8e978cbe069c07f3b8d16d.js:29:432
d
https://cdn.sharelatex.com/minjs/libs/raven-3.15.0.min.js:2:6300
Source map error: request failed with status 404
Resource URL: https://cdn.sharelatex.com/minjs/libs/raven-3.15.0.min.js
Source Map URL: raven.min.js.map[Learn More]

## Screenshots

![image](https://user-images.githubusercontent.com/17570430/41986768-5d9daf3c-7a37-11e8-968b-b5a45f8749d5.png)

**Comment by rickstaa** [comment]
Seems to be fixed in firefox now

**Comment by jdleesmiller** [comment]
Thanks for reporting this. It was indeed a bug, which we rolled back quickly.
