### ISSUE TITLE
Next time inform about maintenance/downtime

### ISSUE THREAD

**Issue by SomeSomeUser** [sharelatex/sharelatex#595]
## Problem

Can't work on my paper

## Install type

https://www.sharelatex.com/

## Version

None

## Logs and errors

Also none

## Screenshots

You have probably seen "request timed out" many times by now.

**Comment by jdleesmiller** [comment]
Thanks for getting in touch, and I'm sorry you're having trouble. We are aware of an issue with one of our service providers (see https://status.linode.com/), which is affecting both ShareLaTeX and Overleaf v2. Our development team is monitoring the situation, and we hope to have an update soon. I'd like to apologize for any inconvenience this is causing, and we'll keep you updated as things progress.

See also http://status.overleaf.com/.
