### ISSUE TITLE
Modifying pdflatex command

### ISSUE THREAD

**Issue by blubbsy** [sharelatex/sharelatex#598]
Hi,

is there any way to change the pdflatex (or any other building tool) command sharelatex executes to build the documents? I would like to try out texliveonfly to automatically download packages that are missing in the texlive installation as a full-scheme installation is not possible without changing the docker container space limit from 10gb to a higher one. 

BR,
Blubbsy

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. I don't think there's any officially supported way, but it's worth noting that you can provide a custom `latexmkrc` file in your project, and that allows you to change the command that the build system runs. See http://personal.psu.edu/jcc8/software/latexmk/ for more information about latexmk.
