### ISSUE TITLE
Add ConteXt support

### ISSUE THREAD

**Issue by PhML** [sharelatex/sharelatex#66]
[ConTeXt](http://wiki.contextgarden.net/Main_Page) is a TeX macro package similar to LaTeX. It is included into TeXlive although it has its own standalone installation (more often updated and ["is self-contained and can happily coexist alongside another installed TeX distribution"](http://wiki.contextgarden.net/ConTeXt_Standalone)).
It is based on LuaTeX (it has the same authors) and compiles to a pdf file simply by running "context myfile".
Having the choice to run either LaTeX or ConTeXt in ShareLaTeX would be nice.

**Comment by heitzmann** [comment]
Any news on Context support in Shalatex? It's the only feature holding me back from using it to write classroom material and share with colleagues.

**Comment by jpallen** [comment]
This isn't as simple as we original hoped, sorry. It's unlikely that we'll implement this in ShareLaTeX in near future as there hasn't been much demand for it. Sorry.

**Comment by ripcurldane** [comment]
I'd also love Context support. :-)

**Comment by zeigerpuppy** [comment]
one very useful feature of ConTeXt support is the external figure support (which allows images from a URL without the use of -shell-escape)

http://wiki.contextgarden.net/Using_Graphics
```
\externalfigure[http://tug.org/images/logobw.jpg]
```

**Comment by ripcurldane** [comment]
ConTeXt would be awesome!! 
I use both, they are good for different things.

Jan

**Comment by ripcurldane** [comment]
I also now use sharelatex exclusively rather than my PC for Latex. 
So ConText on share latex would be so good, I would pay more just for that.
If people knew how good it was many would convert.

**Comment by rosikand** [comment]
Any update on this in 2021?

**Comment by subimal** [comment]
Adding ConTeXt support would be great.

**Comment by AnadeB** [comment]
Try to setup it like this:

1. Create a new project,
2. rename main.tex to output.tex,
3. set the Compiler to LaTeX (using the project menu),
4. create a new file, name it latexmkrc and put the following line into it:
`$latex = 'context --luatex --synctex --batchmode %S'`
5. edit output.tex and put there eg.
`\starttext
This is \CONTEXT.
\stoptext`
6. compile

**Comment by subimal** [comment]
Thank you @AnadeB, I will try it.

**Comment by tie-ling** [comment]
ConTeXt LMTX shipped with TeX Live 2023 is broken on Overleaf.

To get any output, use the older ConTeXt Mark IV from TeX Live 2022.

Or one can try the official [ConTeXt on Web](https://context-on-web.eu/).
